## Setup común para los tests del generador

Este bloque importa `generate_case.py`, fija el orden de las 9 configuraciones y define
helpers pequeños para liberar memoria entre casos.

Si `generate_case.py` no está en el mismo directorio del notebook, ajusta `MODULE_DIR`.

In [1]:
from pathlib import Path
import sys

REPO_ROOT = Path("../../..").resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

In [2]:
from __future__ import annotations

from pathlib import Path
import sys
import gc as py_gc
import json
import tempfile

import pandas as pd
from pandas.testing import assert_frame_equal


from experiments.persistence_formats.generate_case import (
    PREDEFINED_CONFIGS,
    DEFAULT_SEED,
    compute_expected_fingerprint,
    generate_experiment_case,
    get_predefined_config,
)

CONFIG_IDS = ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9"]


def _cleanup_case(case):
    del case
    py_gc.collect()


def _print_ok(msg: str) -> None:
    print(f"Ok: {msg}")

## Test 1 - Smoke test completo de las 9 configuraciones

Objetivo:
- generar las 9 configuraciones sin error,
- verificar que respetan `(C, R, k)`,
- verificar que producen el número correcto de columnas,
- verificar la cardinalidad correcta de `exp_cat_a_k` y `exp_cat_b_k`,
- verificar que el fingerprint esperado queda construido con la estructura mínima esperada.

In [3]:
results = []

for config_id in CONFIG_IDS:
    config = get_predefined_config(config_id)
    case = generate_experiment_case(config, seed=DEFAULT_SEED)

    df = case.trips.data
    fp = case.expected_fingerprint
    manifest = case.manifest

    # 1) shape y cantidad de columnas
    assert df.shape == (config.n_rows, config.n_cols), (
        f"{config_id}: shape incorrecto. "
        f"esperado={(config.n_rows, config.n_cols)}, obtenido={df.shape}"
    )
    assert len(df.columns) == config.n_cols, (
        f"{config_id}: número de columnas incorrecto. "
        f"esperado={config.n_cols}, obtenido={len(df.columns)}"
    )

    # 2) manifest coherente con config
    assert manifest["config_id"] == config.config_id
    assert manifest["n_rows"] == config.n_rows
    assert manifest["n_cols"] == config.n_cols
    assert manifest["k"] == config.k

    # 3) fingerprint con estructura mínima esperada
    assert fp["config_id"] == config.config_id
    assert fp["seed"] == DEFAULT_SEED
    assert fp["n_rows"] == config.n_rows
    assert fp["n_cols"] == config.n_cols
    assert fp["k"] == config.k
    assert isinstance(fp["columns_order"], list)
    assert isinstance(fp["dtypes_expected"], dict)
    assert isinstance(fp["column_fingerprints"], dict)
    assert isinstance(fp["dataset_fingerprint"], str)
    assert len(fp["columns_order"]) == config.n_cols
    assert len(fp["column_fingerprints"]) == config.n_cols

    # 4) cardinalidad observada de los 2 campos controlados
    card_a = df["exp_cat_a_k"].nunique(dropna=True)
    card_b = df["exp_cat_b_k"].nunique(dropna=True)
    assert card_a == config.k, (
        f"{config_id}: exp_cat_a_k cardinalidad incorrecta. "
        f"esperado={config.k}, obtenido={card_a}"
    )
    assert card_b == config.k, (
        f"{config_id}: exp_cat_b_k cardinalidad incorrecta. "
        f"esperado={config.k}, obtenido={card_b}"
    )

    # 5) cardinalidad de categorías declaradas
    assert len(df["exp_cat_a_k"].cat.categories) == config.k, (
        f"{config_id}: exp_cat_a_k categories incorrectas"
    )
    assert len(df["exp_cat_b_k"].cat.categories) == config.k, (
        f"{config_id}: exp_cat_b_k categories incorrectas"
    )

    results.append(
        {
            "config_id": config_id,
            "shape": df.shape,
            "card_a": card_a,
            "card_b": card_b,
            "dataset_fingerprint_prefix": fp["dataset_fingerprint"][:12],
        }
    )

    _cleanup_case(case)

results_df = pd.DataFrame(results)
display(results_df)
_print_ok("Test 1 superado: generación, shape, columnas, cardinalidades y fingerprint mínimo.")

  config_id           shape  card_a  card_b dataset_fingerprint_prefix
0        C1    (200000, 36)      10      10               3f9af838fb90
1        C2   (200000, 156)      10      10               62c82cac6a35
2        C3   (200000, 256)      10      10               238689ae5886
3        C4    (20000, 156)      10      10               178d9db5a094
4        C5  (1000000, 156)      10      10               fb3689520649
5        C6   (200000, 156)    1000    1000               2f733085a0fe
6        C7   (200000, 156)   10000   10000               16caee5ebfb3
7        C8  (1000000, 256)      10      10               ec28f3789f43
8        C9  (1000000, 156)   10000   10000               803537920bb2

Ok: Test 1 superado: generación, shape, columnas, cardinalidades y fingerprint mínimo.

## Test 2 - Verificación del contrato del TripSchema y del schema_effective

Objetivo:
- comprobar que el `TripSchema` contiene los campos base esperados,
- comprobar que `schema_effective` refleja el DataFrame generado,
- comprobar que los campos categóricos controlados y fijos quedaron tipados como `categorical`.

In [4]:
BASE_REQUIRED_FIELDS = [
    "movement_id",
    "user_id",
    "origin_longitude",
    "origin_latitude",
    "destination_longitude",
    "destination_latitude",
    "origin_h3_index",
    "destination_h3_index",
    "origin_time_utc",
    "destination_time_utc",
    "trip_id",
    "movement_seq",
]

EXPECTED_FIXED_CATEGORICALS = ["mode", "purpose", "day_type", "time_period"]
EXPECTED_CONTROLLED_CATEGORICALS = ["exp_cat_a_k", "exp_cat_b_k"]

for config_id in CONFIG_IDS:
    config = get_predefined_config(config_id)
    case = generate_experiment_case(config, seed=DEFAULT_SEED)

    df = case.trips.data
    schema = case.schema
    schema_eff = case.trips.schema_effective

    # 1) required del schema
    for field in BASE_REQUIRED_FIELDS:
        assert field in schema.required, f"{config_id}: falta required {field}"
        assert field in schema.fields, f"{config_id}: falta FieldSpec para {field}"

    # 2) coherencia entre schema_effective y dataframe
    assert schema_eff.fields_effective == list(df.columns), (
        f"{config_id}: fields_effective no coincide con columnas del DataFrame"
    )

    for col in df.columns:
        assert col in schema_eff.dtype_effective, (
            f"{config_id}: falta dtype_effective para columna {col}"
        )

    # 3) tipado lógico de categóricos
    for field in EXPECTED_FIXED_CATEGORICALS + EXPECTED_CONTROLLED_CATEGORICALS:
        assert schema.fields[field].dtype == "categorical", (
            f"{config_id}: {field} no quedó como categorical en TripSchema"
        )
        assert field in schema_eff.domains_effective, (
            f"{config_id}: {field} no quedó en domains_effective"
        )

    _cleanup_case(case)

_print_ok("Test 2 superado: TripSchema y schema_effective coherentes.")

Ok: Test 2 superado: TripSchema y schema_effective coherentes.

## Test 3 - Construcción y persistencia del fingerprint esperado

Objetivo:
- comprobar que el fingerprint esperado se puede recomputar,
- comprobar que `persist_fingerprint_dir` escribe un JSON por configuración,
- comprobar que el JSON persistido coincide exactamente con el fingerprint retornado.

In [5]:
with tempfile.TemporaryDirectory() as tmpdir:
    tmpdir_path = Path(tmpdir)

    persisted = []

    for config_id in CONFIG_IDS:
        config = get_predefined_config(config_id)
        case = generate_experiment_case(
            config,
            seed=DEFAULT_SEED,
            persist_fingerprint_dir=tmpdir_path,
        )

        print("\nDataframe generado y fingerprint generado")
        display(case.trips.data)
        display(case.expected_fingerprint)

        # 1) archivo generado
        assert case.fingerprint_path is not None, f"{config_id}: fingerprint_path es None"
        assert case.fingerprint_path.exists(), f"{config_id}: no existe el JSON persistido"

        # 2) contenido persistido = fingerprint retornado
        persisted_payload = json.loads(case.fingerprint_path.read_text(encoding="utf-8"))
        assert persisted_payload == case.expected_fingerprint, (
            f"{config_id}: JSON persistido distinto del fingerprint retornado"
        )

        # 3) recomputación directa del fingerprint sobre el DF
        recomputed = compute_expected_fingerprint(
            case.trips.data,
            config=config,
            seed=DEFAULT_SEED,
        )
        assert recomputed == case.expected_fingerprint, (
            f"{config_id}: fingerprint recomputado distinto del original"
        )

        persisted.append(
            {
                "config_id": config_id,
                "path": str(case.fingerprint_path),
                "dataset_fingerprint_prefix": case.expected_fingerprint["dataset_fingerprint"][:12],
            }
        )

        _cleanup_case(case)

persisted_df = pd.DataFrame(persisted)
display(persisted_df)
_print_ok("Test 3 superado: fingerprint construido, recomputable y persistible.")

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_016  extra_bool_017
0       m000000000  u0000000  ...           False           False
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...           False            True
3       m000000003  u0000003  ...           False            True
4       m000000004  u0000004  ...            True           False
...            ...       ...  ...             ...             ...
199995  m000199995  u0039995  ...           False            True
199996  m000199996  u0039996  ...           False           False
199997  m000199997  u0039997  ...            True           False
199998  m000199998  u0039998  ...            True           False
199999  m000199999  u0039999  ...           False            True

[200000 rows x 36 columns]

{'config_id': 'C1',
 'seed': 20260415,
 'n_rows': 200000,
 'n_cols': 36,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean'},
 'column_fingerprints': {'movement_id': 'c849c4d592b0c980c478ace6741348badcf57b22f7989ad748630d694c4f2da0',
  'user_id': 'eaeb890a4223d17c8be054d6859a701241b2051e13433adafa451cdc3e696302',
  'origin_longitude': '6410224b15e201ac842f4dca6592fc1da1dc52f4f291b38c8138974e179ca593',
  'origin_latitude': 'dd4293a55298471ecf743903c2c0534afdd456fdbb9303b7a2a19cb001c6b19d',
  'destination_longitude': 'ead1565a3117e609d20a9935b67d181235f872b5ef196c5814e2cdc831b887af',
  'destination_latitude': 'eb1d7202f964ea34b0d64fbba49c96e839cc76306c268ac40c1217bd68a1ec32',
  'origin_h3_index': '0cfd22b3e177154b186d59629e1d93a6b1f113a3f33a267c208968496ae501de',
  'destination_h3_index': '0d87fd7f869a5e38d03e721d32990ea6d3c5501935fc14f7a2f99450c02ab7b1',
  'origin_time_utc': '73b4cdf1c90dd44800773a6c11f3d1f453553333b4cf113a3b7de3231828c005',
  'destination_time_utc': '8ea92714080120fdb8ebc28d0a221d1253e13da81550061dc9b838bf74c67728',
  'trip_id': '1dafc82c67b6342629f51f6fbefc56a31d22cd78a808e5ee060492eaa42224c5',
  'movement_seq': '58e0a2f7c0e88d03332c57054d218a14ea5c2b4a408cc7a5f7780f04298ba981',
  'trip_weight': '7617eb641c10cb0168d26d3100c2f17577e68a931fba705a3daf7d0a7c7c2a09',
  'mode': '47f9de0d959ca111a9b0d414f5e82a972f53557a2c88b1dd64c4f02cb3786f5e',
  'purpose': 'c1197ec9097b9a1b764915f769a6c73222b89e1744f962ab8fffc8d5fc690722',
  'day_type': 'ba2bd9112828c4746f5edab87b01b9f7b5eb79e9fbc1a748225bb614c75f1b3b',
  'time_period': 'b5ca0460a13679fb5e0e568b74218569c1d313ed5fd97c8cb731c7c642dea477',
  'exp_cat_a_k': 'd092f9951900325040da73d09c95f29b2de08e28ee5130b39eb5bbd405cd9600',
  'exp_cat_b_k': '0fae4eb8c7780fe670332999904ed68c68c7f6e344b63ab0431e111f80864e07',
  'extra_float_001': '490613f5e5def96196598bb5d6d9585170191c047b3971b3f310f907dac355a6',
  'extra_float_002': '086fe1137a8313abd08d3ce00694ad8279d93b0c404796a9398e14b7e9e8df78',
  'extra_float_003': 'f812c4240cf0dea6d66476d754aa3ef6339295785de0d5181419899db4ef5a1d',
  'extra_float_004': '5f9f0360980d72241306edc163fa6a4429d116ac3cd1b6a5958a440c6b4d75ba',
  'extra_float_005': '87e9e006c858ea1ef80de89eb35e058d09c904435752c476ebb1dbdfefd5fe33',
  'extra_float_006': '750e92355b54c02e371f7e1b2b2df71e216b706f6b7c249ab7191f7fe405e22c',
  'extra_float_007': 'a9edf5d62e7c6447b4eead894debecaf2d77da777a5bed0e0ede2e48627b4be4',
  'extra_float_008': '149acac0a238441aabc19a923fa534e26c5760b77c94d3a181efbad654d4ba6e',
  'extra_float_009': '1f45ab72a1be5ae7c0e9667e3c3dab83dd740591b55dcc89ae9d61ae909c3220',
  'extra_float_010': '690e7353ddc260b3bcb5dc3d0b6af541c205bcf2a31268184c3d53d7747fd644',
  'extra_int_011': '915b1db6a56f4ccb00accb7db50a29e17be66aeddb3e54642a1659820fc82268',
  'extra_int_012': '7334ce1d803f356bb4d76a50cf2073191e4b661072e0773ffbbda6a2e487b691',
  'extra_int_013': '4bca3b928f258d31812f38675374309a88d026b66f4994f95c1dd3526301029a',
  'extra_int_014': 'c1c2c1f82cf4d0e11443a5d5db8d431253e60b07dd51fd6ad42d3f0e7f15122c',
  'extra_int_015': '7264debbd2528462ab33646b9a4dea45b65cd9acf242b083d7a7d682637f4991',
  'extra_bool_016': '7a2280a777894891a83b62c022b665a2c9022178b9af7dc221fb15c07b75f467',
  'extra_bool_017': 'd8a0bc303497b2363ad3cc0e39bd3c6f7b4a7d0e5c01ce29be9dfc4ffe1730f8'},
 'dataset_fingerprint': '3f9af838fb90cc6551425c38e68704efb1468c90ae979e85e60b8e3db2947381'}

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_136  extra_bool_137
0       m000000000  u0000000  ...           False           False
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...           False            True
3       m000000003  u0000003  ...           False            True
4       m000000004  u0000004  ...           False           False
...            ...       ...  ...             ...             ...
199995  m000199995  u0039995  ...           False            True
199996  m000199996  u0039996  ...           False           False
199997  m000199997  u0039997  ...            True            True
199998  m000199998  u0039998  ...           False            True
199999  m000199999  u0039999  ...           False           False

[200000 rows x 156 columns]

{'config_id': 'C2',
 'seed': 20260415,
 'n_rows': 200000,
 'n_cols': 156,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'c849c4d592b0c980c478ace6741348badcf57b22f7989ad748630d694c4f2da0',
  'user_id': 'eaeb890a4223d17c8be054d6859a701241b2051e13433adafa451cdc3e696302',
  'origin_longitude': '6410224b15e201ac842f4dca6592fc1da1dc52f4f291b38c8138974e179ca593',
  'origin_latitude': 'dd4293a55298471ecf743903c2c0534afdd456fdbb9303b7a2a19cb001c6b19d',
  'destination_longitude': 'ead1565a3117e609d20a9935b67d181235f872b5ef196c5814e2cdc831b887af',
  'destination_latitude': 'eb1d7202f964ea34b0d64fbba49c96e839cc76306c268ac40c1217bd68a1ec32',
  'origin_h3_index': '0cfd22b3e177154b186d59629e1d93a6b1f113a3f33a267c208968496ae501de',
  'destination_h3_index': '0d87fd7f869a5e38d03e721d32990ea6d3c5501935fc14f7a2f99450c02ab7b1',
  'origin_time_utc': '73b4cdf1c90dd44800773a6c11f3d1f453553333b4cf113a3b7de3231828c005',
  'destination_time_utc': '8ea92714080120fdb8ebc28d0a221d1253e13da81550061dc9b838bf74c67728',
  'trip_id': '1dafc82c67b6342629f51f6fbefc56a31d22cd78a808e5ee060492eaa42224c5',
  'movement_seq': '58e0a2f7c0e88d03332c57054d218a14ea5c2b4a408cc7a5f7780f04298ba981',
  'trip_weight': '7617eb641c10cb0168d26d3100c2f17577e68a931fba705a3daf7d0a7c7c2a09',
  'mode': '47f9de0d959ca111a9b0d414f5e82a972f53557a2c88b1dd64c4f02cb3786f5e',
  'purpose': 'c1197ec9097b9a1b764915f769a6c73222b89e1744f962ab8fffc8d5fc690722',
  'day_type': 'ba2bd9112828c4746f5edab87b01b9f7b5eb79e9fbc1a748225bb614c75f1b3b',
  'time_period': 'b5ca0460a13679fb5e0e568b74218569c1d313ed5fd97c8cb731c7c642dea477',
  'exp_cat_a_k': 'd092f9951900325040da73d09c95f29b2de08e28ee5130b39eb5bbd405cd9600',
  'exp_cat_b_k': '0fae4eb8c7780fe670332999904ed68c68c7f6e344b63ab0431e111f80864e07',
  'extra_float_001': '490613f5e5def96196598bb5d6d9585170191c047b3971b3f310f907dac355a6',
  'extra_float_002': '086fe1137a8313abd08d3ce00694ad8279d93b0c404796a9398e14b7e9e8df78',
  'extra_float_003': 'f812c4240cf0dea6d66476d754aa3ef6339295785de0d5181419899db4ef5a1d',
  'extra_float_004': '5f9f0360980d72241306edc163fa6a4429d116ac3cd1b6a5958a440c6b4d75ba',
  'extra_float_005': '87e9e006c858ea1ef80de89eb35e058d09c904435752c476ebb1dbdfefd5fe33',
  'extra_float_006': '750e92355b54c02e371f7e1b2b2df71e216b706f6b7c249ab7191f7fe405e22c',
  'extra_float_007': 'a9edf5d62e7c6447b4eead894debecaf2d77da777a5bed0e0ede2e48627b4be4',
  'extra_float_008': '149acac0a238441aabc19a923fa534e26c5760b77c94d3a181efbad654d4ba6e',
  'extra_float_009': '1f45ab72a1be5ae7c0e9667e3c3dab83dd740591b55dcc89ae9d61ae909c3220',
  'extra_float_010': '690e7353ddc260b3bcb5dc3d0b6af541c205bcf2a31268184c3d53d7747fd644',
  'extra_int_011': '915b1db6a56f4ccb00accb7db50a29e17be66aeddb3e54642a1659820fc82268',
  'extra_int_012': '7334ce1d803f356bb4d76a50cf2073191e4b661072e0773ffbbda6a2e487b691',
  'extra_int_013': '4bca3b928f258d31812f38675374309a88d026b66f4994f95c1dd3526301029a',
  'extra_int_014': 'c1c2c1f82cf4d0e11443a5d5db8d431253e60b07dd51fd6ad42d3f0e7f15122c',
  'extra_int_015': '7264debbd2528462ab33646b9a4dea45b65cd9acf242b083d7a7d682637f4991',
  'extra_bool_016': '7a2280a777894891a83b62c022b665a2c9022178b9af7dc221fb15c07b75f467',
  'extra_bool_017': 'd8a0bc303497b2363ad3cc0e39bd3c6f7b4a7d0e5c01ce29be9dfc4ffe1730f8',
  'extra_bool_018': 'c8bf5bad07aaad8c10643db06c7171398bb5952428084cd2b9d7e613f82ba6ca',
  'extra_string_019': '5866b462402b027e11c621971bd5e5abd928c9525169dfdcdb1de53fdb80639b',
  'extra_datetime_020': 'b16385727d126b2f6364e619f9d7aed5751bf526f447b505873363993f8ac636',
  'extra_float_021': '447b08ab5eb5f6ca2f2724a4c52962dfdefeffd5470918b66f2835d67d105ca6',
  'extra_float_022': '7b7b182818da3f22651bafecba3fc6ff09d40a3a30a7c6ed1da04f936b6c8f51',
  'extra_float_023': 'bf2f567bfa731320168ccfc85d0f8ab7790e121b05962ca83e11c9a9aa615600',
  'extra_float_024': 'd7d38a115c4a08fd09b0e0617ae7988812bd119f9a86e46c5676960ada0a998e',
  'extra_float_025': '78c24cd40c37f3fee0e380bd535d3b1b1ea25928b0db58c9a0b5b524281a5580',
  'extra_float_026': '83d0baf2c6e434494cd80afd635bf3fd4c0c19c375ac2e7610bc9e91e82a3497',
  'extra_float_027': '3994a19be5ca59608175c52807f7e055775f776066873ee7650fa8df26d0cbbf',
  'extra_float_028': 'bf37c2ac2a5500340de4f9dce2b131faa8752efc4cc309e149d4b5f8bed03249',
  'extra_float_029': '2200a824bede7e49401afa00235b1580f420a7053384d8e63f0a9b3cc33e4f99',
  'extra_float_030': 'a79d9d410d397ac23dfe7f29a4edd8d6e97e94864f663ea244fef308578a23af',
  'extra_int_031': '20c4368451dabd0aa5aa9954ea60aa2b998af1f11a833b33c4d97a32d26f8f0e',
  'extra_int_032': 'abe3d645b3119c75d5c61f70ee5846d91732f521e54ba1520a10bb6c267d79f3',
  'extra_int_033': '2023fb53d1060c39737b1b45906ae6de4296c4061f73e27c0d355dfe43af8984',
  'extra_int_034': 'fccf570f84da5941557b85922a7f4a8ed0b5e50498d1ef38d77afe1c9f624547',
  'extra_int_035': '18237987502b05c8a05060fc5b0212c55f3ce77cf1b89f626ef1530b6d894ac6',
  'extra_bool_036': '4a703a07afe16fda8ce2a86387b9438eeee462d87600a4d1a45df00d49c24c0f',
  'extra_bool_037': 'fe6ca639ac3e5f624014bef4ece7cdddf727c6500a0ec0e5fdc955c874173983',
  'extra_bool_038': '4977ceb5a0155695ac6b87077c8808608a0fd8edafdb1c9479d27fcb9b3440a6',
  'extra_string_039': '19f1a9b33f1d50515805c7bb44b0a5292e34daf1555c2c6a2ab821ca0ec22772',
  'extra_datetime_040': 'd86e67cecf6879c3e4188216564fd80b8ad4b077ddf2aa3545cbde94ac78a69a',
  'extra_float_041': '0361d7c40b956fabf46bbc30d8397adb646f0011ed2aef7276b6440ef62bfdd6',
  'extra_float_042': 'cc9faafa1a07875058fb6373900e6e80a300019bf1fa58ee3e5da79b2e166a2a',
  'extra_float_043': 'fba679c12bc2b405d56ef6a09fc1df5915f797cf66276b6acf2d2dbe9dae8811',
  'extra_float_044': 'b8370d5f6301cd24f25457f30f0b997743d0e26d77d396cb13752d7d2884560c',
  'extra_float_045': '0a8c3d58705dce0cbeb3d087c53930ff34b48471aadbe551f2b2d4fb88320674',
  'extra_float_046': '11ed4bbc9c8b1d6ba8cbd086bece2a1e0daf5dbcdd900e115244737bd4b1e693',
  'extra_float_047': 'e7adce33656f08fbeb5efdad373bddefeba68ad91fb6c62042b447453c7a9131',
  'extra_float_048': 'dea2d805241ac502d3257566473e4b9920d73d0e44e27c30b29e7bbcb48aebdd',
  'extra_float_049': '678e97046eba996acd4f39d59019561fc5c9deb4770579ebea6a7865f2103898',
  'extra_float_050': '5ff3aea2427341efb89182b6431b106d8489380cb309ca3eb8685b981f722b9a',
  'extra_int_051': '038a0020cdb2b281f81dcd6e74235428ef52c0e67cda16cf128c2a90d3ad6459',
  'extra_int_052': '7322d996495cdd6c9458b84034e79af3012c6cf01b990be91a4ead1fa0d25809',
  'extra_int_053': '19027b5359f06192eec80dcf01ebee6433135398dab0c2250aefbf53c36e5580',
  'extra_int_054': 'f04fdd366967310eebc4153d06ede7969eef4f3e313a25c10eca231e73d66a87',
  'extra_int_055': '05d3cf1e03b002af3c6a4490f3b096d297fb1211368f4d09af0be192a767749a',
  'extra_bool_056': '30641ac51b745cbbfa72f04ff5f5fe8ab84645ced7b3e964320b1f7d062dcbe5',
  'extra_bool_057': '0b29a842277ed1d1b84d13d46730510406fde816fe2e9f7b462be3ec2e3504dd',
  'extra_bool_058': '75fe46dc79dadcaf245945d5b5227204602e98b9b01cc7d522115a23ac1af6d3',
  'extra_string_059': '3de183912d8c111c33fc041c2c4205fb6660d448955645b726bb0a0edaab00f8',
  'extra_datetime_060': '3bf8df226fb72730397b6087a0be0bf07906959ccf8c743dc5607981db08b7c7',
  'extra_float_061': 'e1cf3adf94e6185a745c9c584ffc9a6cb31f0904dd3c481a97e87814bea20bc7',
  'extra_float_062': '64178a79a55eb29421e18ab1259756d4a5106d9868487d8ce4a61b92edd8335a',
  'extra_float_063': 'de9af0c44ec2522908d7576be762dcee4ae02d91c5b54ca00b04fdf216db6e9a',
  'extra_float_064': '319efcc3a5a3c5722f01cf28d72f2eb9a39c622e9ac6bb2ed1016fabd5616f78',
  'extra_float_065': 'e23b689b0b962227b9677527bb610f2bf9ada910b93150d8833d0ca21c82af6a',
  'extra_float_066': 'ae38f57653e89b965eb7ccf8a5f93a27399bd0d068aebabf8c17fbf9c103626d',
  'extra_float_067': '44beedf91bb78710e9a21f5c307f587fd7506d4e3bafa388ea499c92726c1581',
  'extra_float_068': 'c0889df3ecba4536ccc9f38dc266023b72bf292ed14d8cda7603d55e522675e8',
  'extra_float_069': '7e3838973aa21b801b2146fe71aaa855ecf17443a076b43e1ca3ea1ae700c144',
  'extra_float_070': 'e0c27ab608f6f6a3ae86ab9501166d9b2f76e2e8a23b2ef5282883f3017e02e3',
  'extra_int_071': '753f877bf071accd172c63248ddc1e13c5f2f664c94688ddc743ff3be98188d8',
  'extra_int_072': '6fa1e46fce8b3740d234384219253f1e6dc363e4ad343535084bb0668cca45e4',
  'extra_int_073': 'd9ccf1e8653fdc9b79accb3fdd7cf0ae8c1ea5189b2ec5c01a89980322eaf9bf',
  'extra_int_074': 'd92256606efd60adf4a1180b832c1c4958ed6c26c07622f4353ecc7ce24ee554',
  'extra_int_075': 'a770a7d51fb921375728d03f5b282f75e9bb5fdf2d0d2f368b519cfbdb3b0fe7',
  'extra_bool_076': 'c5aa5a43e66d45b7a650a6364c51a52c0835acb407428929c26ba0093907cc99',
  'extra_bool_077': '8003510534bda296373e0aabd99b0358a94a5c0d69a6438d4ae545289f852e17',
  'extra_bool_078': 'afa2e00572991f018a8b1af75f8c0fe5eb2dcf5d94f326b3891665b85e9bfc24',
  'extra_string_079': '3ebca6c9f996873681bb9491a9dd025c529a09847acd5fdfbdea3c9dc1b9da9f',
  'extra_datetime_080': '43156b6e80e8c2f8aa0b15e25bd88af811faf0fa77df1a306f233e40416d6c79',
  'extra_float_081': 'eff6f7239ec29c821c30810ff033ebf185b94c3ba0af3e59ebc9b784efbf97cc',
  'extra_float_082': '945729a24f522755c77658ca718fbbee991f05229f648dbafd608ec6495e91fb',
  'extra_float_083': '0d1e097e3805fdc8cfbaa3bbe59371de3c6040cb38356b60b2242d3fb0733939',
  'extra_float_084': 'a5d7cfe1da461b59c76db61ff3d147236e781e670935f3ba97a9707949639ba3',
  'extra_float_085': '32c39df7d46c74c9de50735241b5d78488e3302bcfed41a175745d4ecb33bdfc',
  'extra_float_086': '9ed94b4ccaa01d837c7cfb6a2f79aae7e2f476312c3f05ae10c6f35d904a5939',
  'extra_float_087': '2756227eec346f0f5435c8c6c97edf5647b48ef38babe46847d63022c591b6a3',
  'extra_float_088': '2090919261c1ed13eef95d0f14b06b25855008edc7163db3ab511620b0eb18b9',
  'extra_float_089': '942f7ce296fa8c87bfdaa82ec4699e4ad0ed4af049e6ae990449f3e9a0ea2583',
  'extra_float_090': '60176cd4ca9161576272bbc17baa1917eac2a24b2fef8d44c939546056f9f1ef',
  'extra_int_091': 'de68caa2dbf93507bae00ecd146b902df49c1d31c550d2c73625773e72152393',
  'extra_int_092': 'e9a8ed17f49b63e7bbef3c67f4f43c764ac0bb590212c37a122bd5d7f0e619b9',
  'extra_int_093': '67528ca3d8fa06014cb68f1c63f82d9ecfeee4e3b5620b6cd564c58fb3745545',
  'extra_int_094': '77b17a4fac32b25aac3a2f3d1171680340a299be504e68b30ae9da05c2e1e59e',
  'extra_int_095': 'cd4711d503d6bf4eb73bb0078bdd020776e25b8ce0d8d6aec8613198fb470b08',
  'extra_bool_096': 'bb9b17fc628ab8a90b65e5cd6827a20397f85a8e1ba3df5f593d2166ea2bd75f',
  'extra_bool_097': '78fe50fd0a4276493df50ab00ab949084444fc261e861c0ce324da8cac20f8f2',
  'extra_bool_098': '7bbfa8504669cbb6a5b3bd155e79157555b12ed1d1c3a47e227ed202e13772ee',
  'extra_string_099': '1e19e6fe60c4a28b6d83abd7a1e6ae18f218e0af0a015db934a5bf862c5fc730',
  'extra_datetime_100': '00060a1e36bddb3592ceb51c3ea6d45c01c03205b78d4e1bc2cbe1b91ba1cd6b',
  'extra_float_101': '14765350f8e0c2e34410243f12d514932802933c14107b868d87a73693d716ff',
  'extra_float_102': '5e4e191f436db12623f9c0f3dfd0b603e2335e58e13f9268e566ac055cad1f68',
  'extra_float_103': '5121fed186481a710db9bade91619de652fd9f5d9ad1435e7d88d6062ffb36c5',
  'extra_float_104': '56bf3bea2be57b91cb6ebde74c93406df00de36d960aed5cd654032c2faf9c5b',
  'extra_float_105': '1bcb3a59b9d906f274a26a8a0053013f4ec5fe58f196e00c4147a094d8476da8',
  'extra_float_106': '49f8b27817fe5d1a7a89a05683447b5c307f6c9482dee95f6d12e4cc5063e29b',
  'extra_float_107': '25eaa368c2cc9c6162ad4af456eb79849e4ffab951b4c08544806a856a99dfb7',
  'extra_float_108': 'ff7e9649c5729bf4cd7e9a73f4cb318ea9c70aba4ae9ee68e351d4a7fc712827',
  'extra_float_109': '5b0936099e67043bbb8ec363f19cf288a6c330f7cfb375e0c59de293084de010',
  'extra_float_110': '1438c596210c72bc887e5480053ba12539076131a380df41f52f6610e5a9a846',
  'extra_int_111': '676c789b110486e4b096c1f1e4a8a6329605e8710c1fec30bcbcdd788e413eab',
  'extra_int_112': 'c57e667c441ad6f5ae579d9168c8a6388b746bcb15abc38e66b7be3a7880183e',
  'extra_int_113': '78d955ec4299018b377e469f437f50745a11a2b34b1e8da55ad66048869c35b7',
  'extra_int_114': '973908c004ac6b136779f6392d97be14220c32ff0ef4fbe7f9e03a3eb105ca53',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_236  extra_bool_237
0       m000000000  u0000000  ...           False            True
1       m000000001  u0000001  ...           False            True
2       m000000002  u0000002  ...            True            True
3       m000000003  u0000003  ...           False           False
4       m000000004  u0000004  ...            True           False
...            ...       ...  ...             ...             ...
199995  m000199995  u0039995  ...            True           False
199996  m000199996  u0039996  ...            True            True
199997  m000199997  u0039997  ...            True           False
199998  m000199998  u0039998  ...            True            True
199999  m000199999  u0039999  ...           False           False

[200000 rows x 256 columns]

{'config_id': 'C3',
 'seed': 20260415,
 'n_rows': 200000,
 'n_cols': 256,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137',
  'extra_bool_138',
  'extra_string_139',
  'extra_datetime_140',
  'extra_float_141',
  'extra_float_142',
  'extra_float_143',
  'extra_float_144',
  'extra_float_145',
  'extra_float_146',
  'extra_float_147',
  'extra_float_148',
  'extra_float_149',
  'extra_float_150',
  'extra_int_151',
  'extra_int_152',
  'extra_int_153',
  'extra_int_154',
  'extra_int_155',
  'extra_bool_156',
  'extra_bool_157',
  'extra_bool_158',
  'extra_string_159',
  'extra_datetime_160',
  'extra_float_161',
  'extra_float_162',
  'extra_float_163',
  'extra_float_164',
  'extra_float_165',
  'extra_float_166',
  'extra_float_167',
  'extra_float_168',
  'extra_float_169',
  'extra_float_170',
  'extra_int_171',
  'extra_int_172',
  'extra_int_173',
  'extra_int_174',
  'extra_int_175',
  'extra_bool_176',
  'extra_bool_177',
  'extra_bool_178',
  'extra_string_179',
  'extra_datetime_180',
  'extra_float_181',
  'extra_float_182',
  'extra_float_183',
  'extra_float_184',
  'extra_float_185',
  'extra_float_186',
  'extra_float_187',
  'extra_float_188',
  'extra_float_189',
  'extra_float_190',
  'extra_int_191',
  'extra_int_192',
  'extra_int_193',
  'extra_int_194',
  'extra_int_195',
  'extra_bool_196',
  'extra_bool_197',
  'extra_bool_198',
  'extra_string_199',
  'extra_datetime_200',
  'extra_float_201',
  'extra_float_202',
  'extra_float_203',
  'extra_float_204',
  'extra_float_205',
  'extra_float_206',
  'extra_float_207',
  'extra_float_208',
  'extra_float_209',
  'extra_float_210',
  'extra_int_211',
  'extra_int_212',
  'extra_int_213',
  'extra_int_214',
  'extra_int_215',
  'extra_bool_216',
  'extra_bool_217',
  'extra_bool_218',
  'extra_string_219',
  'extra_datetime_220',
  'extra_float_221',
  'extra_float_222',
  'extra_float_223',
  'extra_float_224',
  'extra_float_225',
  'extra_float_226',
  'extra_float_227',
  'extra_float_228',
  'extra_float_229',
  'extra_float_230',
  'extra_int_231',
  'extra_int_232',
  'extra_int_233',
  'extra_int_234',
  'extra_int_235',
  'extra_bool_236',
  'extra_bool_237'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean',
  'extra_bool_138': 'boolean',
  'extra_string_139': 'string',
  'extra_datetime_140': 'datetime64[ns]',
  'extra_float_141': 'float32',
  'extra_float_142': 'float32',
  'extra_float_143': 'float32',
  'extra_float_144': 'float32',
  'extra_float_145': 'float32',
  'extra_float_146': 'float32',
  'extra_float_147': 'float32',
  'extra_float_148': 'float32',
  'extra_float_149': 'float32',
  'extra_float_150': 'float32',
  'extra_int_151': 'int32',
  'extra_int_152': 'int32',
  'extra_int_153': 'int32',
  'extra_int_154': 'int32',
  'extra_int_155': 'int32',
  'extra_bool_156': 'boolean',
  'extra_bool_157': 'boolean',
  'extra_bool_158': 'boolean',
  'extra_string_159': 'string',
  'extra_datetime_160': 'datetime64[ns]',
  'extra_float_161': 'float32',
  'extra_float_162': 'float32',
  'extra_float_163': 'float32',
  'extra_float_164': 'float32',
  'extra_float_165': 'float32',
  'extra_float_166': 'float32',
  'extra_float_167': 'float32',
  'extra_float_168': 'float32',
  'extra_float_169': 'float32',
  'extra_float_170': 'float32',
  'extra_int_171': 'int32',
  'extra_int_172': 'int32',
  'extra_int_173': 'int32',
  'extra_int_174': 'int32',
  'extra_int_175': 'int32',
  'extra_bool_176': 'boolean',
  'extra_bool_177': 'boolean',
  'extra_bool_178': 'boolean',
  'extra_string_179': 'string',
  'extra_datetime_180': 'datetime64[ns]',
  'extra_float_181': 'float32',
  'extra_float_182': 'float32',
  'extra_float_183': 'float32',
  'extra_float_184': 'float32',
  'extra_float_185': 'float32',
  'extra_float_186': 'float32',
  'extra_float_187': 'float32',
  'extra_float_188': 'float32',
  'extra_float_189': 'float32',
  'extra_float_190': 'float32',
  'extra_int_191': 'int32',
  'extra_int_192': 'int32',
  'extra_int_193': 'int32',
  'extra_int_194': 'int32',
  'extra_int_195': 'int32',
  'extra_bool_196': 'boolean',
  'extra_bool_197': 'boolean',
  'extra_bool_198': 'boolean',
  'extra_string_199': 'string',
  'extra_datetime_200': 'datetime64[ns]',
  'extra_float_201': 'float32',
  'extra_float_202': 'float32',
  'extra_float_203': 'float32',
  'extra_float_204': 'float32',
  'extra_float_205': 'float32',
  'extra_float_206': 'float32',
  'extra_float_207': 'float32',
  'extra_float_208': 'float32',
  'extra_float_209': 'float32',
  'extra_float_210': 'float32',
  'extra_int_211': 'int32',
  'extra_int_212': 'int32',
  'extra_int_213': 'int32',
  'extra_int_214': 'int32',
  'extra_int_215': 'int32',
  'extra_bool_216': 'boolean',
  'extra_bool_217': 'boolean',
  'extra_bool_218': 'boolean',
  'extra_string_219': 'string',
  'extra_datetime_220': 'datetime64[ns]',
  'extra_float_221': 'float32',
  'extra_float_222': 'float32',
  'extra_float_223': 'float32',
  'extra_float_224': 'float32',
  'extra_float_225': 'float32',
  'extra_float_226': 'float32',
  'extra_float_227': 'float32',
  'extra_float_228': 'float32',
  'extra_float_229': 'float32',
  'extra_float_230': 'float32',
  'extra_int_231': 'int32',
  'extra_int_232': 'int32',
  'extra_int_233': 'int32',
  'extra_int_234': 'int32',
  'extra_int_235': 'int32',
  'extra_bool_236': 'boolean',
  'extra_bool_237': 'boolean'},
 'column_fingerprints': {'movement_id': 'c849c4d592b0c980c478ace6741348badcf57b22f7989ad748630d694c4f2da0',
  'user_id': 'eaeb890a4223d17c8be054d6859a701241b2051e13433adafa451cdc3e696302',
  'origin_longitude': '6410224b15e201ac842f4dca6592fc1da1dc52f4f291b38c8138974e179ca593',
  'origin_latitude': 'dd4293a55298471ecf743903c2c0534afdd456fdbb9303b7a2a19cb001c6b19d',
  'destination_longitude': 'ead1565a3117e609d20a9935b67d181235f872b5ef196c5814e2cdc831b887af',
  'destination_latitude': 'eb1d7202f964ea34b0d64fbba49c96e839cc76306c268ac40c1217bd68a1ec32',
  'origin_h3_index': '0cfd22b3e177154b186d59629e1d93a6b1f113a3f33a267c208968496ae501de',
  'destination_h3_index': '0d87fd7f869a5e38d03e721d32990ea6d3c5501935fc14f7a2f99450c02ab7b1',
  'origin_time_utc': '73b4cdf1c90dd44800773a6c11f3d1f453553333b4cf113a3b7de3231828c005',
  'destination_time_utc': '8ea92714080120fdb8ebc28d0a221d1253e13da81550061dc9b838bf74c67728',
  'trip_id': '1dafc82c67b6342629f51f6fbefc56a31d22cd78a808e5ee060492eaa42224c5',
  'movement_seq': '58e0a2f7c0e88d03332c57054d218a14ea5c2b4a408cc7a5f7780f04298ba981',
  'trip_weight': '7617eb641c10cb0168d26d3100c2f17577e68a931fba705a3daf7d0a7c7c2a09',
  'mode': '47f9de0d959ca111a9b0d414f5e82a972f53557a2c88b1dd64c4f02cb3786f5e',
  'purpose': 'c1197ec9097b9a1b764915f769a6c73222b89e1744f962ab8fffc8d5fc690722',
  'day_type': 'ba2bd9112828c4746f5edab87b01b9f7b5eb79e9fbc1a748225bb614c75f1b3b',
  'time_period': 'b5ca0460a13679fb5e0e568b74218569c1d313ed5fd97c8cb731c7c642dea477',
  'exp_cat_a_k': 'd092f9951900325040da73d09c95f29b2de08e28ee5130b39eb5bbd405cd9600',
  'exp_cat_b_k': '0fae4eb8c7780fe670332999904ed68c68c7f6e344b63ab0431e111f80864e07',
  'extra_float_001': '490613f5e5def96196598bb5d6d9585170191c047b3971b3f310f907dac355a6',
  'extra_float_002': '086fe1137a8313abd08d3ce00694ad8279d93b0c404796a9398e14b7e9e8df78',
  'extra_float_003': 'f812c4240cf0dea6d66476d754aa3ef6339295785de0d5181419899db4ef5a1d',
  'extra_float_004': '5f9f0360980d72241306edc163fa6a4429d116ac3cd1b6a5958a440c6b4d75ba',
  'extra_float_005': '87e9e006c858ea1ef80de89eb35e058d09c904435752c476ebb1dbdfefd5fe33',
  'extra_float_006': '750e92355b54c02e371f7e1b2b2df71e216b706f6b7c249ab7191f7fe405e22c',
  'extra_float_007': 'a9edf5d62e7c6447b4eead894debecaf2d77da777a5bed0e0ede2e48627b4be4',
  'extra_float_008': '149acac0a238441aabc19a923fa534e26c5760b77c94d3a181efbad654d4ba6e',
  'extra_float_009': '1f45ab72a1be5ae7c0e9667e3c3dab83dd740591b55dcc89ae9d61ae909c3220',
  'extra_float_010': '690e7353ddc260b3bcb5dc3d0b6af541c205bcf2a31268184c3d53d7747fd644',
  'extra_int_011': '915b1db6a56f4ccb00accb7db50a29e17be66aeddb3e54642a1659820fc82268',
  'extra_int_012': '7334ce1d803f356bb4d76a50cf2073191e4b661072e0773ffbbda6a2e487b691',
  'extra_int_013': '4bca3b928f258d31812f38675374309a88d026b66f4994f95c1dd3526301029a',
  'extra_int_014': 'c1c2c1f82cf4d0e11443a5d5db8d431253e60b07dd51fd6ad42d3f0e7f15122c',
  'extra_int_015': '7264debbd2528462ab33646b9a4dea45b65cd9acf242b083d7a7d682637f4991',
  'extra_bool_016': '7a2280a777894891a83b62c022b665a2c9022178b9af7dc221fb15c07b75f467',
  'extra_bool_017': 'd8a0bc303497b2363ad3cc0e39bd3c6f7b4a7d0e5c01ce29be9dfc4ffe1730f8',
  'extra_bool_018': 'c8bf5bad07aaad8c10643db06c7171398bb5952428084cd2b9d7e613f82ba6ca',
  'extra_string_019': '5866b462402b027e11c621971bd5e5abd928c9525169dfdcdb1de53fdb80639b',
  'extra_datetime_020': 'b16385727d126b2f6364e619f9d7aed5751bf526f447b505873363993f8ac636',
  'extra_float_021': '447b08ab5eb5f6ca2f2724a4c52962dfdefeffd5470918b66f2835d67d105ca6',
  'extra_float_022': '7b7b182818da3f22651bafecba3fc6ff09d40a3a30a7c6ed1da04f936b6c8f51',
  'extra_float_023': 'bf2f567bfa731320168ccfc85d0f8ab7790e121b05962ca83e11c9a9aa615600',
  'extra_float_024': 'd7d38a115c4a08fd09b0e0617ae7988812bd119f9a86e46c5676960ada0a998e',
  'extra_float_025': '78c24cd40c37f3fee0e380bd535d3b1b1ea25928b0db58c9a0b5b524281a5580',
  'extra_float_026': '83d0baf2c6e434494cd80afd635bf3fd4c0c19c375ac2e7610bc9e91e82a3497',
  'extra_float_027': '3994a19be5ca59608175c52807f7e055775f776066873ee7650fa8df26d0cbbf',
  'extra_float_028': 'bf37c2ac2a5500340de4f9dce2b131faa8752efc4cc309e149d4b5f8bed03249',
  'extra_float_029': '2200a824bede7e49401afa00235b1580f420a7053384d8e63f0a9b3cc33e4f99',
  'extra_float_030': 'a79d9d410d397ac23dfe7f29a4edd8d6e97e94864f663ea244fef308578a23af',
  'extra_int_031': '20c4368451dabd0aa5aa9954ea60aa2b998af1f11a833b33c4d97a32d26f8f0e',
  'extra_int_032': 'abe3d645b3119c75d5c61f70ee5846d91732f521e54ba1520a10bb6c267d79f3',
  'extra_int_033': '2023fb53d1060c39737b1b45906ae6de4296c4061f73e27c0d355dfe43af8984',
  'extra_int_034': 'fccf570f84da5941557b85922a7f4a8ed0b5e50498d1ef38d77afe1c9f624547',
  'extra_int_035': '18237987502b05c8a05060fc5b0212c55f3ce77cf1b89f626ef1530b6d894ac6',
  'extra_bool_036': '4a703a07afe16fda8ce2a86387b9438eeee462d87600a4d1a45df00d49c24c0f',
  'extra_bool_037': 'fe6ca639ac3e5f624014bef4ece7cdddf727c6500a0ec0e5fdc955c874173983',
  'extra_bool_038': '4977ceb5a0155695ac6b87077c8808608a0fd8edafdb1c9479d27fcb9b3440a6',
  'extra_string_039': '19f1a9b33f1d50515805c7bb44b0a5292e34daf1555c2c6a2ab821ca0ec22772',
  'extra_datetime_040': 'd86e67cecf6879c3e4188216564fd80b8ad4b077ddf2aa3545cbde94ac78a69a',
  'extra_float_041': '0361d7c40b956fabf46bbc30d8397adb646f0011ed2aef7276b6440ef62bfdd6',
  'extra_float_042': 'cc9faafa1a07875058fb6373900e6e80a300019bf1fa58ee3e5da79b2e166a2a',
  'extra_float_043': 'fba679c12bc2b405d56ef6a09fc1df5915f797cf66276b6acf2d2dbe9dae8811',
  'extra_float_044': 'b8370d5f6301cd24f25457f30f0b997743d0e26d77d396cb13752d7d2884560c',
  'extra_float_045': '0a8c3d58705dce0cbeb3d087c53930ff34b48471aadbe551f2b2d4fb88320674',
  'extra_float_046': '11ed4bbc9c8b1d6ba8cbd086bece2a1e0daf5dbcdd900e115244737bd4b1e693',
  'extra_float_047': 'e7adce33656f08fbeb5efdad373bddefeba68ad91fb6c62042b447453c7a9131',
  'extra_float_048': 'dea2d805241ac502d3257566473e4b9920d73d0e44e27c30b29e7bbcb48aebdd',
  'extra_float_049': '678e97046eba996acd4f39d59019561fc5c9deb4770579ebea6a7865f2103898',
  'extra_float_050': '5ff3aea2427341efb89182b6431b106d8489380cb309ca3eb8685b981f722b9a',
  'extra_int_051': '038a0020cdb2b281f81dcd6e74235428ef52c0e67cda16cf128c2a90d3ad6459',
  'extra_int_052': '7322d996495cdd6c9458b84034e79af3012c6cf01b990be91a4ead1fa0d25809',
  'extra_int_053': '19027b5359f06192eec80dcf01ebee6433135398dab0c2250aefbf53c36e5580',
  'extra_int_054': 'f04fdd366967310eebc4153d06ede7969eef4f3e313a25c10eca231e73d66a87',
  'extra_int_055': '05d3cf1e03b002af3c6a4490f3b096d297fb1211368f4d09af0be192a767749a',
  'extra_bool_056': '30641ac51b745cbbfa72f04ff5f5fe8ab84645ced7b3e964320b1f7d062dcbe5',

Dataframe generado y fingerprint generado

      movement_id   user_id  ...  extra_bool_136  extra_bool_137
0      m000000000  u0000000  ...           False           False
1      m000000001  u0000001  ...           False           False
2      m000000002  u0000002  ...           False           False
3      m000000003  u0000003  ...            True            True
4      m000000004  u0000004  ...           False            True
...           ...       ...  ...             ...             ...
19995  m000019995  u0009995  ...            True           False
19996  m000019996  u0009996  ...           False            True
19997  m000019997  u0009997  ...            True           False
19998  m000019998  u0009998  ...           False            True
19999  m000019999  u0009999  ...            True            True

[20000 rows x 156 columns]

{'config_id': 'C4',
 'seed': 20260415,
 'n_rows': 20000,
 'n_cols': 156,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'b1b17e904695af05a6a58a94e0f5f90476753f9036d5b2baa51058b3eace4e3a',
  'user_id': '614c58becff94a9893595bc8b5cd8fde750773c6691f339fbc8785623d955a22',
  'origin_longitude': '12725f5124d0f79574d48de11d7d81edf8d163a442d78e33d154e6da9ad671a7',
  'origin_latitude': 'b31b5ef627bbe93a2558480a9d9d2012179e055a767924dee5cea31a93e9443e',
  'destination_longitude': '2b344caad2dc42ed2dfe2f30cc469da61e62118ccc9c13094dbe3227165fb267',
  'destination_latitude': 'f303ef541d530ce628f3a5dec1b90fb94c40ac967752d704bdc82b1dea62c105',
  'origin_h3_index': 'c64dfaab0f1072b36b539654e78f3d8e1d5fe788eddd2184acea98e8db570798',
  'destination_h3_index': '3a756dd900db2c8c532858914e46bdc9689a4917c1d5c381da600da7b00c2531',
  'origin_time_utc': 'd22b76a2340b2c08f401637ed9e9fb5a02f2db48e3acd73a88ba343029bedc53',
  'destination_time_utc': 'b447e4cb28b41d806d8e6701deb07b56616ce77cf49fe21146b90d26f79e783a',
  'trip_id': '77c75a6df8edf04cb6630db250b5d044043683141ef821203f1f471ba54045ac',
  'movement_seq': 'b9ce164d30e4101b009fe4be765a070593cfbdd48f897853de159a8c177fabe8',
  'trip_weight': 'a62b4a7feb049ac60a23db363e18188a21cfa59e7652cbbcaff2f2fc91a713c5',
  'mode': '07c860669b6dfe977b5b7da09753c5ef1197a4892fb99249965248efb880755c',
  'purpose': '12ccb795a05868208c782e873c6aa7ceddce67feb04ee46b8c99b42c65537a21',
  'day_type': 'edafe01c454773ca7d7ea9fac3afa369830d479ad2cee66a99af4861096d9ba7',
  'time_period': 'c177b7f60ffbbbd550c6e261ba16e408680c23c299e78ddbaa44611925688c05',
  'exp_cat_a_k': 'd43043ab2f1249bad569fa5db7f94e72e8dd3af85b463ea2d514f5b20f4bedbc',
  'exp_cat_b_k': '53ca5eda7b82ab0a565d4d8f89120e7b7059375ece28c77036b0a92a2e3d0790',
  'extra_float_001': '41646ec588b76755276df3b4d2a77d409276301f147db181cde379a59c4355ee',
  'extra_float_002': '8e7d3470825d69403eb8cf8cc99d79d69caff67bc786e2474d5bf7fa903b04b8',
  'extra_float_003': '68be569be76368060d7364a58a6d86577df3bb7ef17dc94067d36274c2a202a4',
  'extra_float_004': '38b5e47b72f2e3c66fdcbc2b132ab60c3bdbb5a9e71c7e772e4c59ffaf0a0561',
  'extra_float_005': '1ce1d672619021fb18314650ec9a1ef0a5459f606b8790f80e8f067116bfcad7',
  'extra_float_006': '9f39bd9a0faa0bc2a871ab3464fb2dcbfb3e98fe696dea9f13ea908c23929877',
  'extra_float_007': 'f9cda95ff3e2ab5026f8cecd515fa2f7a27b3068b318f04e1734193a78ee38a9',
  'extra_float_008': '14beac7ba737cbe49b3d2371d604b8ecd3f4ea6d299fc3244cf3aaa672e127a1',
  'extra_float_009': '439c41cb9d3376296d032f4e166a85cd526ed4042473f5712832494a42d50aa4',
  'extra_float_010': '79ccb7c87025403e6fb3d2d77f5ce0e32cbf0be302ec30a357843e2ae2862ff1',
  'extra_int_011': 'f1217c093ba385ee1a3899c4048e39f82fc7ed43ac759c906ae142e0e8368f24',
  'extra_int_012': '4a5f43099a496ab916d36fe9e9b1cb2fe69bf6ca4cc4c1ddc1cecb4a7748fb80',
  'extra_int_013': '919d91e5f0e520a721f024a35f7a490554ef9a54d07d46a97ff932cf459dc829',
  'extra_int_014': 'aba7262ff644c6b688e12631fe8325c2aec4e6d0a735a4361361c7f1727adb0f',
  'extra_int_015': 'b99030f94dc3b5d9dbb9843314fef2f1f074dfcab96bfce5fcda4cbbc1c4c06c',
  'extra_bool_016': 'e6f48e8d37c78744df91d8ec9c384596f3ab7c72c1e3ceecabc868f4acf0f87e',
  'extra_bool_017': '6a3b58c6ce77ac9d45f38f88fa71fedd279a196f2c17775db976f2ee976100d2',
  'extra_bool_018': '8e9d8064dbcc88ba14861eae2183808d7bab6f0bab7a60add22c0ff0411c617d',
  'extra_string_019': '5147eb00af2b7e9d819bb86870e1f7d65e2a5a44c139bda502df111d357259c0',
  'extra_datetime_020': '9ebdaf816f9a4c7e4dffff43e81a763462a4dec6ef51e4044a32127fdc6c4cf1',
  'extra_float_021': '0500b08243d0eea195a6a95cf22caabec411a1470eb5dcb512970755e39f47ea',
  'extra_float_022': '35e0b182ec7ddf984c3996372408f9a9d02d49a2c13dc45c53d842225aab21dc',
  'extra_float_023': '7fbd65aa7b8d96563034d72012f7f7dd3ff18b12dac9545e01e615bf8867a7ee',
  'extra_float_024': '0ed567e5f1925120d8bb7ae584f6d7811f1d0b4582b669d66419f735cc20e07f',
  'extra_float_025': 'fe624bf3eb1e282c7727acfce27e9211f7243542b1d31675275e019525fa467c',
  'extra_float_026': '8e6a2391852f7d03781fa9d63182ce723b7f573ff8de43f50bc42200e3dd513e',
  'extra_float_027': '5a7051e8c0dbd71cdd8c3619fc8a3e3e5a42402cbb6306763ad191323b410445',
  'extra_float_028': '7d35e85582b573f4b2188c705cd32f3681dd241dbad3f60dbe91fb2917f9d729',
  'extra_float_029': '5a9c583c4de997f249b6bd81d914f3c15176e70a28f8cee4baa35b37bbef3d31',
  'extra_float_030': 'cf589a3b163d74635c19dd0b727c3ea83db8b06c4c51b42a4e9b5ad745c98c4d',
  'extra_int_031': 'c6c1d8ff7a9c0cb30991a3ef33caf65d178cd06dea8690d327441727c8ec1858',
  'extra_int_032': '839f4f0ce45d945ddda2605e630d00948ce5071631184ca24427f7da2b65e2e4',
  'extra_int_033': 'c399f4d25f8f7ae1b0161928f44b3254e862fa0f2befe01dc0da40d2fcd4bfc2',
  'extra_int_034': 'fc502ac9caee50ef686f5848f99aab42c867605a102ed579ebf792fd3829d592',
  'extra_int_035': 'bf5a58e32ab0447e57447b27deff4867e9e89556e256d7408dc3e0e91c6e2fa2',
  'extra_bool_036': '9202464225419d1b0208dfdf83750c3a9233dc3e51499661d2cab9738bf3cc3e',
  'extra_bool_037': 'cce126ff4ecc5410603058a96235bec821888f26ac74542e39bf0550eb1e24dc',
  'extra_bool_038': 'b2775f87b3d6e09e6bdbf53cf11092d927d80f914dc4f10ca7faba5a1206511a',
  'extra_string_039': '393cc82480ab20aa3655380c08f370c4077dbdf383f964ac60479cfb3b3fc76a',
  'extra_datetime_040': 'b26176966e24957066cce481ef0a9e1d887e3ac4f810065355390c3732d5e027',
  'extra_float_041': '04cae36721170b8aa2ddc956491c1563b6cbbdca7aecfe0d7b39469b5dec4869',
  'extra_float_042': '020736a9c61f58d9cb1cc3b9c7218e59f4213cdc10c5868f316d7cb77648f7e7',
  'extra_float_043': 'e33c01db523708928a6651023771d287ee24c67266c033376031a128a7d73b70',
  'extra_float_044': '0c07c097f27a1bdf34de7b64e3a319e45c5f732a3d60bf10d8c32b0a62029906',
  'extra_float_045': '7147fd0730ebbdb63872b387f71eacc4fa12db573581b3e1e95d3422286d13fa',
  'extra_float_046': '34a4998cb832353117e90eef02ed48eb4d883389d5e7c93c5dfff154db09a382',
  'extra_float_047': 'a49cafd5cd8cf3b033afd4333d8d4188305a6fafcb885fc7f1e1dc6f57f1e7f7',
  'extra_float_048': '048791e52c2e7b4d9302bb6b34985f247d04e312ae7631e571aba9146854c3b3',
  'extra_float_049': '0f26b1d3e9d4444f8c09765d3eb0dc4a5de48b7533de2a6a56cf99260f9d6cca',
  'extra_float_050': '883c51118a2aa50ba0b4b18b729fe236e21160e16c40a2818cceae2fc70a8bbb',
  'extra_int_051': '1cab77b5c7f96aafd1d94139058dc2ece7f63e89e5cb278739500b4d64aa8926',
  'extra_int_052': 'd6b0357a9d726e62419d52e5e81d2cc6e6e5b04e0686ae5130a02bd239265a49',
  'extra_int_053': 'd07a98ae521eb2a3b0729c4c2fd8c56d97406fa4ff8ba7258c938ec3bd752624',
  'extra_int_054': '7e9975c03db243182249e84b90cb28db73d168c4c15aefd78140597f6ae92d80',
  'extra_int_055': '694c38e5d7346f684f92c38addb874b0db71b21b8ac9d763295a94c69bb2611c',
  'extra_bool_056': 'b1208bede9dd48719c4d85eb77ba2d0f04ecfc4b27b48007c68c3e49562567bd',
  'extra_bool_057': '8ef1eaaf3145286183aefdb130347a671545bb6083a2d6bd932f31defcf26f29',
  'extra_bool_058': 'fda23afc93205856b1ab271c81d9dc0f7d75890e3d97e889e9f4857fe7a2b9ef',
  'extra_string_059': '2fb18fa802a0c3ea6e118bd81d011e07a3e0651b7cf64796223077ed2d0178e7',
  'extra_datetime_060': 'e8cedb399aa855f460e73dead649e22eb7d168f8c26380805c754d4cb6848b70',
  'extra_float_061': '371def159ba3d3f58c45b0ed4a8c885d2ae4655c7426cf2501f99e615e535ef4',
  'extra_float_062': '90edcc5b11a853c12e2af2104771de9bf4898e4dfa28ba0ac9cedeae1e1e60b4',
  'extra_float_063': '0ecf156a2f1f13ad8a527849694b22de8a7293102dc46f6cb222da5a79c2cbe1',
  'extra_float_064': 'ac67177baf88b26db4adf9929df4f0780a8f8178c796f636c852510f385ff097',
  'extra_float_065': 'e317a2ab2748e13769aadabea4dc7b467fdf9b7de167f7a588e5b00a5be33177',
  'extra_float_066': '17bdb3d316483f3ca23c049b3e8b1b7f06057289eccac079dc13f26c54e20bca',
  'extra_float_067': '259240323459774bc3a64d050434368f309e43513e8e6895084adbfdeed59e99',
  'extra_float_068': '3e6609e0f936ab734a97ee40045a4fa9319ae3bb1b86ea85060ff95710bfbde6',
  'extra_float_069': '54fd3531b99adb312da5591b5395fa6c223cceaddeac9fa2d75cfd8648cbae11',
  'extra_float_070': 'f005d2363f3d2015f585c2f2f313b9d707ee5e3eb7c7d2e5e5a453f96f2cd8b0',
  'extra_int_071': '40948683a75ce3c4dab88a7f068ee100bdb26927cc79bc320378930819732ffb',
  'extra_int_072': '24a62c631bc36f71b2ac5d5dad5eace35e9fa6a8b5dbc261d638cf5c5fbc4093',
  'extra_int_073': 'e92b8a30b34375eff549634febe976f2ba6e0f1dfc08eda2b1e1173d5b5a6ce4',
  'extra_int_074': '734dc0237880ab505427229e413d275ba32924e323017c003a7fa93c3a7b19ac',
  'extra_int_075': '141f56eea19c5267746e78d804ae6b0eda9444122ba730fde3d23695587d1937',
  'extra_bool_076': 'dc45878c1dee5efc8106fab382074ee1a0011c710f339c88d6f39f2d6cad26e4',
  'extra_bool_077': '9d3724b8414fe235da1f0666c67a2dc9e946d03eb37d97c270a96246d774ef20',
  'extra_bool_078': 'ff9668fa738bd710c767b2e63484c3c3e2cad33918bfaa84f58557de77d0edb4',
  'extra_string_079': '46d72bb616a4543453d0516c4eff12e7fc64ee34423b842a83e084bdb7bf62e8',
  'extra_datetime_080': '1b0b6dac8cabd7c19261686ae8a55451582dd1ed14b28421f2f9f89a8551fbbf',
  'extra_float_081': '83e4965e02c6bffd90011729a6e6b5ea393a40f4cb7c0e932c4a47e03c46c336',
  'extra_float_082': '3397cd6137b9eb4f48817bf655978c08d0dac771aec78d6b5e054ecae55d61d9',
  'extra_float_083': 'ee0bc2868faa4eccc9548077a9b8ccaa38259cdaff2eaed5037b4090b0e2655b',
  'extra_float_084': 'fc4b28b5d3c1d0c7a04dcd1faf17f0e881ebbe650a8c2a3bda1f0165225d9498',
  'extra_float_085': '944ace0a8512cbdcad5c233e3561fdc1913c7a55f88ea4f5a342d9d9b7dcba2f',
  'extra_float_086': '8f85dc7723d4b38b3aa03584f817a05c6f58344c9dfe4a290ac296e5b4c99c24',
  'extra_float_087': '368b92bd53f4a184fb06f6785e728a8a55f68c4b57a954ea5ca0da90b97fe30a',
  'extra_float_088': 'f85df66b346102a06b45597439af72b2921ea61f8cc5bd503f576eab5346884d',
  'extra_float_089': '8ce3f3e8b27ed72a4b0cc27647a1fa131d15ffe82f4eaeb164e8f089413aa657',
  'extra_float_090': '1a20402041ce965fe5a1adc190f8212208871c87ff6723555dc3ef6267d40fea',
  'extra_int_091': '196d4d199a6157d54591cd88dd9779fa5394625de8ea92afb8f87f0d25b7e0b9',
  'extra_int_092': 'b853b53a14db321cb03f57da49e30e9df80dd8ad9f9e5baf1ca06068ba246824',
  'extra_int_093': '23ef0e772d83c3519cb1a0fac062d2030f79035fb71536dc53c7cdbff8d52880',
  'extra_int_094': 'dbfe45f90a7fc0cbf7db584067d6377a8d537e922b30956d9641810cf2542a0c',
  'extra_int_095': '7d79397286b30442603714469f3ac1dc1bde88fe3235048258a28a7b54a12091',
  'extra_bool_096': 'b6bdeb725c55b62d44e6602921142bd6c1b1c6913e3fbc5bb8883280de19f567',
  'extra_bool_097': '0ed43db072e2916c0480e3a8f729b2df4c6387ad7f529ce5ba5e382ae672909b',
  'extra_bool_098': '6eb928e7510d55c08a2f749a21ae36d0deb99dc161b4b18b0179fb80cc97d506',
  'extra_string_099': 'c2b368e04202ede3856d660ea9ff024471c695ea7f05c799cbd376ea33cab1a3',
  'extra_datetime_100': '5c040b8d76f5a08055c0005e272712d677e533ae890117af9b26f6d3efac16c7',
  'extra_float_101': '30d18abf3a12e8d91adf56742994ceab6cb6662e0cd40f29381a3f6836074acc',
  'extra_float_102': 'adb14e77be251ddfed4e16ba9e766f6d337b5c9006f378e5212056b52c32cbec',
  'extra_float_103': '18ce03ff6a440052f8ad8cafca992a5115fee9802f354283d832674133028f61',
  'extra_float_104': '254bf0cf7821dc6a3d3bcf468530aba49074fe00e65e167e3842ae7f903c4d60',
  'extra_float_105': 'e841328c5ff296caa5ec7ee7c5b1fa22133f01cfcb982bb1b8ffa6caa4e23264',
  'extra_float_106': '90c232fa612f670830d41d7403508147352f159320f104cac87b189879dc7ca5',
  'extra_float_107': '62f9c02fbe85b177d6f5a48728e6eac771e66b8b39ba2a4b47208591f1df6754',
  'extra_float_108': '82ea0d882b40ec99c9e6768ae347267603cc167db5fba33edff9a7ab6c92005f',
  'extra_float_109': '300917fa32ebd243d611de81792a3e979bfcc63911e03544d9d9f380b7747017',
  'extra_float_110': 'e4309abe5d746034373ad7f7338676da396830bf769b521ff7a47bc1dac2df64',
  'extra_int_111': 'fb6f1b9a58da27086bce1bd2f3a8373b5d13e3553a25bbb57047c41d9893d6aa',
  'extra_int_112': '3e2131fcf1e16c185d5fe56c5a54b035e719cc84cf5d6b38100fe83fdb10b357',
  'extra_int_113': 'de7dc2a16062db201724b1d654840ecca4e1c7541ac6bdcd44d6bd5519f93a11',
  'extra_int_114': '12108b544209040d9eb08903d1f553037551b96cdf5158aaf74854782dbfb025',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_136  extra_bool_137
0       m000000000  u0000000  ...           False            True
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...            True           False
3       m000000003  u0000003  ...            True            True
4       m000000004  u0000004  ...            True            True
...            ...       ...  ...             ...             ...
999995  m000999995  u0199995  ...           False            True
999996  m000999996  u0199996  ...            True           False
999997  m000999997  u0199997  ...            True           False
999998  m000999998  u0199998  ...            True           False
999999  m000999999  u0199999  ...            True           False

[1000000 rows x 156 columns]

{'config_id': 'C5',
 'seed': 20260415,
 'n_rows': 1000000,
 'n_cols': 156,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'cb3f67ad59018b5e3e4d8eedcfd4ac72a676550b8406aad93429d806c74b7920',
  'user_id': '65f89204fe232f167e13db27140e38292930107b27ddff177c3bcba8324c1fa9',
  'origin_longitude': 'ceba053d9212e5c1db80e77c89fa05a6a180e9472fe246d92468f00703bb526f',
  'origin_latitude': '995dc7efa75779356579efccd1f9a0aed9b78b3e9ce410c0447c733ff2b8cb45',
  'destination_longitude': '16dcb9e3bb41a2a0266c434f373be6c4cab5827d662ab0f3186a71d5d12fc876',
  'destination_latitude': 'e2030db41304350b4661f6130e99d973da53aec8f1714eab78dad2db12233986',
  'origin_h3_index': 'b5a8eef8f9c9292ec626457f6a971f442822a30d53d86b26f2d2707d87d3d7db',
  'destination_h3_index': 'f722e9a5cc8b58392086852c004a9bfea33bc60bd7bf20c6421a5dc82cad8786',
  'origin_time_utc': '01321ba6312a3f398fdfec99ab6c971a070fe62fbcf6c4bf8c1bd87e391ba997',
  'destination_time_utc': '13706e69ff7155260cb85b6b546356adaa5bc346d652e05b6843b577c8f794cb',
  'trip_id': '0df800f6554a384308f0134c08b5b5112df154a6701736005951783471e3f82b',
  'movement_seq': '6506614505e113daab08b3f894ca46d4d61867c7b007c413b47a669abe8aae67',
  'trip_weight': '963f8cecbac5fba8cfb088a2d743ff1769a915ae20d506123bdd266a74cbf2a0',
  'mode': '1667d7157767d2577465659f1b7ba6edf41bb10f062e350b03b083890bd252cd',
  'purpose': 'b2f736fe9d9c948ec8d7a94f42998c926899089cfcffdc33acf803367fec3be8',
  'day_type': '50ee05cc4c2ed9daf9d66c5baf0fd604e24a8f29de2324dac9e412ca2a84e912',
  'time_period': '0ba244f6bc3b226e122a70b71f700f917c555d12bd6336365621b93ddaa05f0b',
  'exp_cat_a_k': '11a90923d2670d239d6fb52cc3abb8acadf8206c44ea3fc0f70ce9eb6e17b7c7',
  'exp_cat_b_k': '8df595575a9c373475d0c0aa4ae6198d951406dfc7681242a02edb5054de9f98',
  'extra_float_001': '8742bb8e23e7c729982fa8d05651752899669ae2cbbd7f28102b8332edd2c698',
  'extra_float_002': '79570d09d10703b379e5865e8a97121bac45bf8228b2909a99805a9acd55bb60',
  'extra_float_003': 'b429e05224b3f917ba5f8f3fc6c7e172541b4cd712677c88def4ecf128e51548',
  'extra_float_004': 'f162dcdd32b179a84d74d01a023f40df6cdf65202d62d03299f536514c37967d',
  'extra_float_005': '18d0b812fd8dd5801a95e1832f453d721d35c29c83bb6ddebc52f97fe569ced8',
  'extra_float_006': 'fc42b9325ba5ffb55bf58eea24357d23774b5f76fff7e2828b12046c56e23374',
  'extra_float_007': '65125cb08f9fb11a42838485d3c22289cfa9c5e2483ddcf04e93a2ca23b17805',
  'extra_float_008': 'ef87e06374999709a0ceac2d028d3e3ad535296baeb755631dd668fca3aca3a0',
  'extra_float_009': '4db06161d9de8313dd34867af05de6b7c0fb68c07190c73a742aa62555e71d69',
  'extra_float_010': '9c38e1c1b2f7bf7cffc1e1b91cd4e1bd0c2da39fad205744be0ed92673f5d944',
  'extra_int_011': '3f0c53276c5f72d90ffc8ff8b50563725e54512d9010f04ec4ca8caab6c002e6',
  'extra_int_012': '7061924898220d620dd0ff64e7845017efc047b5e5c1afacdf11d193c037d2c9',
  'extra_int_013': '19415c3abbe5dade594f97831d286a816bcacd7daa5f9159187eb577c2bdf717',
  'extra_int_014': 'e693931e3f1a8b09b5388fd6c5975bf5321e0d26937a91f1ace2391d1e95ad25',
  'extra_int_015': '39d06dcf2593d6508c82dbb6236e3b20d2b51ebd3bbe7a284aedaead60bc61a6',
  'extra_bool_016': '54f79df2524164e2dfdd6cba8f5f30776fdacc0349459957dfc92e5b3b3fc120',
  'extra_bool_017': 'cc4a1dea789b953c097c84ce44b04f5b9489b7d18d94543dc6b2aa46f92a928a',
  'extra_bool_018': 'f030070f515956885f894abf314d7805a7a661ee22a6b3addb3d76a1f2bb34cf',
  'extra_string_019': '722186eb87aaf3c56ecb898794afa48c52ae57ab3e645b742af871d635000ef3',
  'extra_datetime_020': '0c972223f4a5a77a2f5283401db4fb23bab8403b1ea6ca644734ea33a6ad7af6',
  'extra_float_021': 'a0b47e8c223d359d41ad97daec6582d9c24836903ee965d0a8a23cd9e96221a5',
  'extra_float_022': '427f38149d34c669f73544c9f479483b67c83c84fca512f8d8b3281da04b11dd',
  'extra_float_023': 'e4acf50733b073bafece296bacc2372efd9ed1638b6dad8436a90fa1b278d71b',
  'extra_float_024': '98bb58a78690cce75c22ca01cbd528bf89f2c7eb54dfc46c2e85bad0673b8d7c',
  'extra_float_025': 'c2628adf118f7811dfd1a0ce48c87cdafc3cc20be0712c8289d5b1b8e9be28d0',
  'extra_float_026': '5441083e6c1c7841abc58c467d877e4b59387e936c0db0664614d900cff1d209',
  'extra_float_027': 'ae67fb6f61ada92e6a637f36bb633fdc6c890467abdaaa2ec4b588314f78b57b',
  'extra_float_028': '41501490497778ba90e4870b399438478f718f56ad7b585505d6330ec98c8cb9',
  'extra_float_029': 'ad38a8777d2f853678cce47e9abf48c30bc1f9b9ed0ff6d765000bfa0b9e656b',
  'extra_float_030': 'bcd6002fe0712ed1e89919442b60786b9501def85e9d2d2a69c7d1f2a6e35466',
  'extra_int_031': '1feea78dff8e12fce1bdb0d63cd3f97cbc544a684c11c6365acefac954ce4e1d',
  'extra_int_032': '9e52d6850db34b4a7db9b87c6503013606eb6e5ad36f8369567594be1f0de1f9',
  'extra_int_033': '83ba7337de983f9d41cbfcb9afa807fbf0f075a2114ba2d6c2cd50e3e01dbdb5',
  'extra_int_034': '16db288059c463a90d1107eedcef12de8a05defdf46b165dce699122a41119ef',
  'extra_int_035': '704467f0b07d9da4281d158214d8038602bdfbbe511a38193c2118b469f7b2ff',
  'extra_bool_036': '508e8bdff1f91643bd1a11172cc76cf346cebb52ca61b04f5ccea02d66e45b91',
  'extra_bool_037': '7a08bf80cb21a7ed74e3e7d7255b2296a6d0c38f7cf0dc2a2466c430328d9634',
  'extra_bool_038': '3d4cb2929c9b9a694693ae880a124999fdec788fbff625efa283259de61fb87b',
  'extra_string_039': '32a7a3e8f5ac4e83ab7a56bfb35be5bff5e1668876e65b89e7816c59b03e0993',
  'extra_datetime_040': '91bd3a5d3d3057827f056bd1907eca63f39d12c90d2ac8e6f9bc981689bcf543',
  'extra_float_041': '372d1099419602a54ef17e61288d38a94ff54f5e0aad6522870ef58ba8ff9c1f',
  'extra_float_042': '260f01c9c2c9ade617a93bfc8f153170be1d0055643a86039bd12a6ddf06ce8a',
  'extra_float_043': '4aac3f36c424f4b5f71cd0729d6e3f34b798bea965b5c5f17f531e1f54859340',
  'extra_float_044': 'c10c65b6925ca328ce460c32d7b85444d4141cfeb31fdde82219e4fd08853509',
  'extra_float_045': '6fbd2623cce75c8c6bdd02137df35595dbc7b601c19f7a9ef31d2877ced254a3',
  'extra_float_046': 'ed64f7a40fe269a612a6582b4be210ce64f5d1cbca7b0080f834bbd3fd90735a',
  'extra_float_047': '873763d5ddc42beca5132dee0ef8e58384b6c8786dcbfd17850df0b53a37488f',
  'extra_float_048': 'b3b09ebd31f13ec298f7b4b9fb1d71381fa2dcd262e2631e0937dc75e3fd1e2c',
  'extra_float_049': '7c0bc8d3c94b5222911c370d1c0ab75b39230d348a4747eba7e1b77d479f47a1',
  'extra_float_050': '24efed12c564ca5c6ddf2718e9cde8bbcad4d65a7c665a5a55a8872a60928f06',
  'extra_int_051': 'e25301ccace2aad9541f9f7835973500058085e03b417357ab41424d297f517a',
  'extra_int_052': '61f5bc011c3adff153f0c913a551798f84d31233f7cb01a96e4d25fcd2c9dccd',
  'extra_int_053': '3b64042a8685a97f28c9f0427313932c6a7bea26283d67f9669f66e45828357c',
  'extra_int_054': '78ffdcdd975ef3ad1532b1b7a70900ad3238b4f8b505ab4400917d852031efc3',
  'extra_int_055': '67fe12ce74dc9fa45dab2d135eab26a105487244ac782b2519a6b0b3713d0aa8',
  'extra_bool_056': '2e48da8e57931a797735d9313284eef0e4b0a3036c015e84597ada9d1983b6e9',
  'extra_bool_057': '3f0ec44cd95325e630c00debedf37a958ff8e832fdb92ba179aa057e2834ae65',
  'extra_bool_058': '9790991b9c299518aa188b3f25e932c8e221e0f1264790839269f4c5a2a9a62e',
  'extra_string_059': '2cb6a2911f495e4e094c7f2b819ccfbfcfbb89ff026d544f93542407e9838f14',
  'extra_datetime_060': '4caa841baac100d7452b30975ea720d1763f646602f7b3aa681f26d468912277',
  'extra_float_061': 'dd9dbc404b3f4b8430792eed1568f1eda0ed78510e302f3465686f65ed5f11b6',
  'extra_float_062': '9f1e0c4addc83cafcf2cd416090652a7d16af3e419e747e980e777435ee4a268',
  'extra_float_063': 'efd771bbe43fa4a85993b800095e2fa5d0b46d77bd95cb4165ae0db7a4b87bb4',
  'extra_float_064': '9f783f6e2e43b9f5678e3e0ed7ae2e8f5bc259a692f845daa26ca74370eb8ad1',
  'extra_float_065': '2c70d9df02821a7d2cd839c4142139a762c1c5303a811fd06caf6eab0ec7a53c',
  'extra_float_066': 'd95eddcc462fb66fe3043efad78242f20d286f252831f0f9873fc020329b1916',
  'extra_float_067': 'c341bf4dfd5b962163a70efaa4462ecd32713fa0e06f24bba3e2eecef9ec06b1',
  'extra_float_068': 'b0054783bedd4ac359637340dc534df6d2c89744cc60c9cdf3c504ab0c996fed',
  'extra_float_069': 'd05b6eba07b8c60900fa46aaabdb110b10be95ccf5fa824a056cb8fd6051c70b',
  'extra_float_070': '037a8591afd697c266ee9404fcafc948dd9f1fec1708929744da1f3ab23baaba',
  'extra_int_071': '43b23faa69adb53eb6cb764f104e04ed7b60833d7390e377ed7552f270494190',
  'extra_int_072': 'bbf11c8559f162c586d81ff98b97192038d03f4720b2c492695a10ba36620532',
  'extra_int_073': '6005b05db3f789907e419746d0a0a3e40a1c5f3cca94384d5bc9b3e1396c8fba',
  'extra_int_074': 'ce66e9155f6d0b4ce87709350af4f3ee5b49767b371ca13a952a3129ef29e24a',
  'extra_int_075': '4366f15dbc7deb9ffedc01fd53135e850e68c1044b856b1bdd71ba4bb6a1d985',
  'extra_bool_076': 'a4502743f3ad2d66290cd30c8dbe414d751644ab6d398eb55e4cf744f5999661',
  'extra_bool_077': '7a5c1678a318b7e0db4c219d6bd5331fbb68085df434ddd370378e74a0b77068',
  'extra_bool_078': 'ecb8eb8049ff96d45f539ed3b3975873f45beeba4585f238fbaf2ddf52b7bac2',
  'extra_string_079': 'f44b21dc888a27d78e7beebc60f901dc79bac04114236893a68ca7e3ee980684',
  'extra_datetime_080': '703a8c29373923ab1e7c562f9cb3fa37f9dcb5be30f6b6990812098201b171f9',
  'extra_float_081': 'a1d9217330effdb5f01c5abf323f264f185602ea34b5cb0ab1f3864e21c26d54',
  'extra_float_082': 'ff1fdbab61afde8add3e8319f2c53add66b575e1b8cf23514b708c4c0ad9cdef',
  'extra_float_083': '00a21213dd30b15bf3894f979961e4402b3fda6c61640f16cd0e9faafc32fe83',
  'extra_float_084': '0f18f0c3ea4489be44d0eab883db1689e7dd97f3df223c61b48f9e0ebef1d46a',
  'extra_float_085': 'e25d997b58d02a1d481d0ba1a15f45d02b73d472658f7208dd3e2f10c46b2f62',
  'extra_float_086': 'eba27adcb93b524fe42f2714aa8e7d4519e9363a8a27766fa2f68e197e25c7df',
  'extra_float_087': '420015bcb8fa4ef1c4f92007bd0d575ae35fae5714fcb25f44fb14e5d52f88de',
  'extra_float_088': '03f7c1315b0db1c83f5b77d13bdede3b3a4d9e35b9c7a7f5a311d1ec268dec04',
  'extra_float_089': 'e1e6b2ab2eced3ffcb65a6e1c4cc8d6d4609c1577d9ac455a93a22329cc6aeda',
  'extra_float_090': 'fb51f44e2ab77dafeb59dc0b21a05398eba8b89e446d0406b1d7a9af77f0e284',
  'extra_int_091': '2a0c8e082e30c3c57d16f9a01c5632a6431de10d73a2063d40b85393ae0e2260',
  'extra_int_092': 'd518527a7d24be7006fc3a80659e05b78cfbd3f2f3e090916b28d902dbe6a838',
  'extra_int_093': 'd8942ec8019312f365b31c772239a740514d75e1592c7acec598f6b035c97133',
  'extra_int_094': 'f7be232167472b1b8303f87e370d72700bb86df4935b31b579f4b75a3ab683b2',
  'extra_int_095': 'e74af36cef6c537fceac7a6e0e0f0fb7081de0a0d5b4e6d15e6b1ea345f2dbb1',
  'extra_bool_096': 'e7634a8ada409a39d6e5e3bd8adc675094db5e0f5a68b58e9ac61ad324ebf150',
  'extra_bool_097': 'c22b3e19ef6bf8154cb4833dd7cd4117402f301e4348b55cced00fd875e18327',
  'extra_bool_098': 'a9c11043b10e5e783cfacefa0570b3d93bc771f3fa0bd52ed1915962fe47ad97',
  'extra_string_099': '90fe511f8ab27408385b0f96acd8665539be69fc106027d049bc5ffcbd7e19ff',
  'extra_datetime_100': '25cc5103db4fc5827514271d617e2f3185b497610aaf607cc012991153d1902c',
  'extra_float_101': 'a62df82311c615ed7e73b11fcd5e94a81b08386dafce2dfde7fa16b57f6fdbef',
  'extra_float_102': 'aa028ed2239104733e996d80b962285b4172cf81e91b698bc71e15ccb79b61de',
  'extra_float_103': 'd064f7f4e2a75949186ffa0b0db914facf04353ff4bd70ad56c3906425117a23',
  'extra_float_104': '0fb508d124d320e3ca1bc681b87300c152c21884711f10b2fdfc424f240b833c',
  'extra_float_105': '65c4c9218a6a3ab1d0356daf89aaa952f42e6242179a00e68037659332c8fc02',
  'extra_float_106': '0484ee3761fb7933ecff7ee315483ef937cfb9144489d26d7403610286464d33',
  'extra_float_107': '3b64e064c8df86a9ac92413ac4598266b71b9ab92dedc24dc7a952be46b4cfdc',
  'extra_float_108': '637371693534b16d05954ba98e73db5f36edc0a2054635075f4ac75912e4d769',
  'extra_float_109': 'c10885ef12b3666499fb83e010eb19f618fadee615cedf4cc88c15ab243004ff',
  'extra_float_110': '0fb0809c20a4d40a2366a0b2feb440014b34d9273a54e25d89bd30f3c06b55be',
  'extra_int_111': '76d79f78209c5da3aaeb726a19fd8f16cd3718fecf0abec6931439590ac7de52',
  'extra_int_112': '9e200c026233be41b379b0bf1af9f634dc84fa263c2f81d88c9c6c35c8d498ad',
  'extra_int_113': 'cc5bb48c6f0ffa2b51e73f162d91499a96660ca00a83608d04542a9f93837fec',
  'extra_int_114': 'abe65161fe16f37e8303e2f6563872d81f2f5b4b32cf4f39e18aeb7c99c2204e',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_136  extra_bool_137
0       m000000000  u0000000  ...           False           False
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...           False            True
3       m000000003  u0000003  ...           False            True
4       m000000004  u0000004  ...           False           False
...            ...       ...  ...             ...             ...
199995  m000199995  u0039995  ...           False            True
199996  m000199996  u0039996  ...           False           False
199997  m000199997  u0039997  ...            True            True
199998  m000199998  u0039998  ...           False            True
199999  m000199999  u0039999  ...           False           False

[200000 rows x 156 columns]

{'config_id': 'C6',
 'seed': 20260415,
 'n_rows': 200000,
 'n_cols': 156,
 'k': 1000,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'c849c4d592b0c980c478ace6741348badcf57b22f7989ad748630d694c4f2da0',
  'user_id': 'eaeb890a4223d17c8be054d6859a701241b2051e13433adafa451cdc3e696302',
  'origin_longitude': '6410224b15e201ac842f4dca6592fc1da1dc52f4f291b38c8138974e179ca593',
  'origin_latitude': 'dd4293a55298471ecf743903c2c0534afdd456fdbb9303b7a2a19cb001c6b19d',
  'destination_longitude': 'ead1565a3117e609d20a9935b67d181235f872b5ef196c5814e2cdc831b887af',
  'destination_latitude': 'eb1d7202f964ea34b0d64fbba49c96e839cc76306c268ac40c1217bd68a1ec32',
  'origin_h3_index': '0cfd22b3e177154b186d59629e1d93a6b1f113a3f33a267c208968496ae501de',
  'destination_h3_index': '0d87fd7f869a5e38d03e721d32990ea6d3c5501935fc14f7a2f99450c02ab7b1',
  'origin_time_utc': '73b4cdf1c90dd44800773a6c11f3d1f453553333b4cf113a3b7de3231828c005',
  'destination_time_utc': '8ea92714080120fdb8ebc28d0a221d1253e13da81550061dc9b838bf74c67728',
  'trip_id': '1dafc82c67b6342629f51f6fbefc56a31d22cd78a808e5ee060492eaa42224c5',
  'movement_seq': '58e0a2f7c0e88d03332c57054d218a14ea5c2b4a408cc7a5f7780f04298ba981',
  'trip_weight': '7617eb641c10cb0168d26d3100c2f17577e68a931fba705a3daf7d0a7c7c2a09',
  'mode': '47f9de0d959ca111a9b0d414f5e82a972f53557a2c88b1dd64c4f02cb3786f5e',
  'purpose': 'c1197ec9097b9a1b764915f769a6c73222b89e1744f962ab8fffc8d5fc690722',
  'day_type': 'ba2bd9112828c4746f5edab87b01b9f7b5eb79e9fbc1a748225bb614c75f1b3b',
  'time_period': 'b5ca0460a13679fb5e0e568b74218569c1d313ed5fd97c8cb731c7c642dea477',
  'exp_cat_a_k': 'ac0b1eb8c6c39cb6cf0a7d4adece7bf50056d19263399627f602d85e2b3a1f79',
  'exp_cat_b_k': '5fa975724c4a1f45c36d3b565c65d264699d23273579c1ba7820b9f2207c74c3',
  'extra_float_001': '490613f5e5def96196598bb5d6d9585170191c047b3971b3f310f907dac355a6',
  'extra_float_002': '086fe1137a8313abd08d3ce00694ad8279d93b0c404796a9398e14b7e9e8df78',
  'extra_float_003': 'f812c4240cf0dea6d66476d754aa3ef6339295785de0d5181419899db4ef5a1d',
  'extra_float_004': '5f9f0360980d72241306edc163fa6a4429d116ac3cd1b6a5958a440c6b4d75ba',
  'extra_float_005': '87e9e006c858ea1ef80de89eb35e058d09c904435752c476ebb1dbdfefd5fe33',
  'extra_float_006': '750e92355b54c02e371f7e1b2b2df71e216b706f6b7c249ab7191f7fe405e22c',
  'extra_float_007': 'a9edf5d62e7c6447b4eead894debecaf2d77da777a5bed0e0ede2e48627b4be4',
  'extra_float_008': '149acac0a238441aabc19a923fa534e26c5760b77c94d3a181efbad654d4ba6e',
  'extra_float_009': '1f45ab72a1be5ae7c0e9667e3c3dab83dd740591b55dcc89ae9d61ae909c3220',
  'extra_float_010': '690e7353ddc260b3bcb5dc3d0b6af541c205bcf2a31268184c3d53d7747fd644',
  'extra_int_011': '915b1db6a56f4ccb00accb7db50a29e17be66aeddb3e54642a1659820fc82268',
  'extra_int_012': '7334ce1d803f356bb4d76a50cf2073191e4b661072e0773ffbbda6a2e487b691',
  'extra_int_013': '4bca3b928f258d31812f38675374309a88d026b66f4994f95c1dd3526301029a',
  'extra_int_014': 'c1c2c1f82cf4d0e11443a5d5db8d431253e60b07dd51fd6ad42d3f0e7f15122c',
  'extra_int_015': '7264debbd2528462ab33646b9a4dea45b65cd9acf242b083d7a7d682637f4991',
  'extra_bool_016': '7a2280a777894891a83b62c022b665a2c9022178b9af7dc221fb15c07b75f467',
  'extra_bool_017': 'd8a0bc303497b2363ad3cc0e39bd3c6f7b4a7d0e5c01ce29be9dfc4ffe1730f8',
  'extra_bool_018': 'c8bf5bad07aaad8c10643db06c7171398bb5952428084cd2b9d7e613f82ba6ca',
  'extra_string_019': '5866b462402b027e11c621971bd5e5abd928c9525169dfdcdb1de53fdb80639b',
  'extra_datetime_020': 'b16385727d126b2f6364e619f9d7aed5751bf526f447b505873363993f8ac636',
  'extra_float_021': '447b08ab5eb5f6ca2f2724a4c52962dfdefeffd5470918b66f2835d67d105ca6',
  'extra_float_022': '7b7b182818da3f22651bafecba3fc6ff09d40a3a30a7c6ed1da04f936b6c8f51',
  'extra_float_023': 'bf2f567bfa731320168ccfc85d0f8ab7790e121b05962ca83e11c9a9aa615600',
  'extra_float_024': 'd7d38a115c4a08fd09b0e0617ae7988812bd119f9a86e46c5676960ada0a998e',
  'extra_float_025': '78c24cd40c37f3fee0e380bd535d3b1b1ea25928b0db58c9a0b5b524281a5580',
  'extra_float_026': '83d0baf2c6e434494cd80afd635bf3fd4c0c19c375ac2e7610bc9e91e82a3497',
  'extra_float_027': '3994a19be5ca59608175c52807f7e055775f776066873ee7650fa8df26d0cbbf',
  'extra_float_028': 'bf37c2ac2a5500340de4f9dce2b131faa8752efc4cc309e149d4b5f8bed03249',
  'extra_float_029': '2200a824bede7e49401afa00235b1580f420a7053384d8e63f0a9b3cc33e4f99',
  'extra_float_030': 'a79d9d410d397ac23dfe7f29a4edd8d6e97e94864f663ea244fef308578a23af',
  'extra_int_031': '20c4368451dabd0aa5aa9954ea60aa2b998af1f11a833b33c4d97a32d26f8f0e',
  'extra_int_032': 'abe3d645b3119c75d5c61f70ee5846d91732f521e54ba1520a10bb6c267d79f3',
  'extra_int_033': '2023fb53d1060c39737b1b45906ae6de4296c4061f73e27c0d355dfe43af8984',
  'extra_int_034': 'fccf570f84da5941557b85922a7f4a8ed0b5e50498d1ef38d77afe1c9f624547',
  'extra_int_035': '18237987502b05c8a05060fc5b0212c55f3ce77cf1b89f626ef1530b6d894ac6',
  'extra_bool_036': '4a703a07afe16fda8ce2a86387b9438eeee462d87600a4d1a45df00d49c24c0f',
  'extra_bool_037': 'fe6ca639ac3e5f624014bef4ece7cdddf727c6500a0ec0e5fdc955c874173983',
  'extra_bool_038': '4977ceb5a0155695ac6b87077c8808608a0fd8edafdb1c9479d27fcb9b3440a6',
  'extra_string_039': '19f1a9b33f1d50515805c7bb44b0a5292e34daf1555c2c6a2ab821ca0ec22772',
  'extra_datetime_040': 'd86e67cecf6879c3e4188216564fd80b8ad4b077ddf2aa3545cbde94ac78a69a',
  'extra_float_041': '0361d7c40b956fabf46bbc30d8397adb646f0011ed2aef7276b6440ef62bfdd6',
  'extra_float_042': 'cc9faafa1a07875058fb6373900e6e80a300019bf1fa58ee3e5da79b2e166a2a',
  'extra_float_043': 'fba679c12bc2b405d56ef6a09fc1df5915f797cf66276b6acf2d2dbe9dae8811',
  'extra_float_044': 'b8370d5f6301cd24f25457f30f0b997743d0e26d77d396cb13752d7d2884560c',
  'extra_float_045': '0a8c3d58705dce0cbeb3d087c53930ff34b48471aadbe551f2b2d4fb88320674',
  'extra_float_046': '11ed4bbc9c8b1d6ba8cbd086bece2a1e0daf5dbcdd900e115244737bd4b1e693',
  'extra_float_047': 'e7adce33656f08fbeb5efdad373bddefeba68ad91fb6c62042b447453c7a9131',
  'extra_float_048': 'dea2d805241ac502d3257566473e4b9920d73d0e44e27c30b29e7bbcb48aebdd',
  'extra_float_049': '678e97046eba996acd4f39d59019561fc5c9deb4770579ebea6a7865f2103898',
  'extra_float_050': '5ff3aea2427341efb89182b6431b106d8489380cb309ca3eb8685b981f722b9a',
  'extra_int_051': '038a0020cdb2b281f81dcd6e74235428ef52c0e67cda16cf128c2a90d3ad6459',
  'extra_int_052': '7322d996495cdd6c9458b84034e79af3012c6cf01b990be91a4ead1fa0d25809',
  'extra_int_053': '19027b5359f06192eec80dcf01ebee6433135398dab0c2250aefbf53c36e5580',
  'extra_int_054': 'f04fdd366967310eebc4153d06ede7969eef4f3e313a25c10eca231e73d66a87',
  'extra_int_055': '05d3cf1e03b002af3c6a4490f3b096d297fb1211368f4d09af0be192a767749a',
  'extra_bool_056': '30641ac51b745cbbfa72f04ff5f5fe8ab84645ced7b3e964320b1f7d062dcbe5',
  'extra_bool_057': '0b29a842277ed1d1b84d13d46730510406fde816fe2e9f7b462be3ec2e3504dd',
  'extra_bool_058': '75fe46dc79dadcaf245945d5b5227204602e98b9b01cc7d522115a23ac1af6d3',
  'extra_string_059': '3de183912d8c111c33fc041c2c4205fb6660d448955645b726bb0a0edaab00f8',
  'extra_datetime_060': '3bf8df226fb72730397b6087a0be0bf07906959ccf8c743dc5607981db08b7c7',
  'extra_float_061': 'e1cf3adf94e6185a745c9c584ffc9a6cb31f0904dd3c481a97e87814bea20bc7',
  'extra_float_062': '64178a79a55eb29421e18ab1259756d4a5106d9868487d8ce4a61b92edd8335a',
  'extra_float_063': 'de9af0c44ec2522908d7576be762dcee4ae02d91c5b54ca00b04fdf216db6e9a',
  'extra_float_064': '319efcc3a5a3c5722f01cf28d72f2eb9a39c622e9ac6bb2ed1016fabd5616f78',
  'extra_float_065': 'e23b689b0b962227b9677527bb610f2bf9ada910b93150d8833d0ca21c82af6a',
  'extra_float_066': 'ae38f57653e89b965eb7ccf8a5f93a27399bd0d068aebabf8c17fbf9c103626d',
  'extra_float_067': '44beedf91bb78710e9a21f5c307f587fd7506d4e3bafa388ea499c92726c1581',
  'extra_float_068': 'c0889df3ecba4536ccc9f38dc266023b72bf292ed14d8cda7603d55e522675e8',
  'extra_float_069': '7e3838973aa21b801b2146fe71aaa855ecf17443a076b43e1ca3ea1ae700c144',
  'extra_float_070': 'e0c27ab608f6f6a3ae86ab9501166d9b2f76e2e8a23b2ef5282883f3017e02e3',
  'extra_int_071': '753f877bf071accd172c63248ddc1e13c5f2f664c94688ddc743ff3be98188d8',
  'extra_int_072': '6fa1e46fce8b3740d234384219253f1e6dc363e4ad343535084bb0668cca45e4',
  'extra_int_073': 'd9ccf1e8653fdc9b79accb3fdd7cf0ae8c1ea5189b2ec5c01a89980322eaf9bf',
  'extra_int_074': 'd92256606efd60adf4a1180b832c1c4958ed6c26c07622f4353ecc7ce24ee554',
  'extra_int_075': 'a770a7d51fb921375728d03f5b282f75e9bb5fdf2d0d2f368b519cfbdb3b0fe7',
  'extra_bool_076': 'c5aa5a43e66d45b7a650a6364c51a52c0835acb407428929c26ba0093907cc99',
  'extra_bool_077': '8003510534bda296373e0aabd99b0358a94a5c0d69a6438d4ae545289f852e17',
  'extra_bool_078': 'afa2e00572991f018a8b1af75f8c0fe5eb2dcf5d94f326b3891665b85e9bfc24',
  'extra_string_079': '3ebca6c9f996873681bb9491a9dd025c529a09847acd5fdfbdea3c9dc1b9da9f',
  'extra_datetime_080': '43156b6e80e8c2f8aa0b15e25bd88af811faf0fa77df1a306f233e40416d6c79',
  'extra_float_081': 'eff6f7239ec29c821c30810ff033ebf185b94c3ba0af3e59ebc9b784efbf97cc',
  'extra_float_082': '945729a24f522755c77658ca718fbbee991f05229f648dbafd608ec6495e91fb',
  'extra_float_083': '0d1e097e3805fdc8cfbaa3bbe59371de3c6040cb38356b60b2242d3fb0733939',
  'extra_float_084': 'a5d7cfe1da461b59c76db61ff3d147236e781e670935f3ba97a9707949639ba3',
  'extra_float_085': '32c39df7d46c74c9de50735241b5d78488e3302bcfed41a175745d4ecb33bdfc',
  'extra_float_086': '9ed94b4ccaa01d837c7cfb6a2f79aae7e2f476312c3f05ae10c6f35d904a5939',
  'extra_float_087': '2756227eec346f0f5435c8c6c97edf5647b48ef38babe46847d63022c591b6a3',
  'extra_float_088': '2090919261c1ed13eef95d0f14b06b25855008edc7163db3ab511620b0eb18b9',
  'extra_float_089': '942f7ce296fa8c87bfdaa82ec4699e4ad0ed4af049e6ae990449f3e9a0ea2583',
  'extra_float_090': '60176cd4ca9161576272bbc17baa1917eac2a24b2fef8d44c939546056f9f1ef',
  'extra_int_091': 'de68caa2dbf93507bae00ecd146b902df49c1d31c550d2c73625773e72152393',
  'extra_int_092': 'e9a8ed17f49b63e7bbef3c67f4f43c764ac0bb590212c37a122bd5d7f0e619b9',
  'extra_int_093': '67528ca3d8fa06014cb68f1c63f82d9ecfeee4e3b5620b6cd564c58fb3745545',
  'extra_int_094': '77b17a4fac32b25aac3a2f3d1171680340a299be504e68b30ae9da05c2e1e59e',
  'extra_int_095': 'cd4711d503d6bf4eb73bb0078bdd020776e25b8ce0d8d6aec8613198fb470b08',
  'extra_bool_096': 'bb9b17fc628ab8a90b65e5cd6827a20397f85a8e1ba3df5f593d2166ea2bd75f',
  'extra_bool_097': '78fe50fd0a4276493df50ab00ab949084444fc261e861c0ce324da8cac20f8f2',
  'extra_bool_098': '7bbfa8504669cbb6a5b3bd155e79157555b12ed1d1c3a47e227ed202e13772ee',
  'extra_string_099': '1e19e6fe60c4a28b6d83abd7a1e6ae18f218e0af0a015db934a5bf862c5fc730',
  'extra_datetime_100': '00060a1e36bddb3592ceb51c3ea6d45c01c03205b78d4e1bc2cbe1b91ba1cd6b',
  'extra_float_101': '14765350f8e0c2e34410243f12d514932802933c14107b868d87a73693d716ff',
  'extra_float_102': '5e4e191f436db12623f9c0f3dfd0b603e2335e58e13f9268e566ac055cad1f68',
  'extra_float_103': '5121fed186481a710db9bade91619de652fd9f5d9ad1435e7d88d6062ffb36c5',
  'extra_float_104': '56bf3bea2be57b91cb6ebde74c93406df00de36d960aed5cd654032c2faf9c5b',
  'extra_float_105': '1bcb3a59b9d906f274a26a8a0053013f4ec5fe58f196e00c4147a094d8476da8',
  'extra_float_106': '49f8b27817fe5d1a7a89a05683447b5c307f6c9482dee95f6d12e4cc5063e29b',
  'extra_float_107': '25eaa368c2cc9c6162ad4af456eb79849e4ffab951b4c08544806a856a99dfb7',
  'extra_float_108': 'ff7e9649c5729bf4cd7e9a73f4cb318ea9c70aba4ae9ee68e351d4a7fc712827',
  'extra_float_109': '5b0936099e67043bbb8ec363f19cf288a6c330f7cfb375e0c59de293084de010',
  'extra_float_110': '1438c596210c72bc887e5480053ba12539076131a380df41f52f6610e5a9a846',
  'extra_int_111': '676c789b110486e4b096c1f1e4a8a6329605e8710c1fec30bcbcdd788e413eab',
  'extra_int_112': 'c57e667c441ad6f5ae579d9168c8a6388b746bcb15abc38e66b7be3a7880183e',
  'extra_int_113': '78d955ec4299018b377e469f437f50745a11a2b34b1e8da55ad66048869c35b7',
  'extra_int_114': '973908c004ac6b136779f6392d97be14220c32ff0ef4fbe7f9e03a3eb105ca53',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_136  extra_bool_137
0       m000000000  u0000000  ...           False           False
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...           False            True
3       m000000003  u0000003  ...           False            True
4       m000000004  u0000004  ...           False           False
...            ...       ...  ...             ...             ...
199995  m000199995  u0039995  ...           False            True
199996  m000199996  u0039996  ...           False           False
199997  m000199997  u0039997  ...            True            True
199998  m000199998  u0039998  ...           False            True
199999  m000199999  u0039999  ...           False           False

[200000 rows x 156 columns]

{'config_id': 'C7',
 'seed': 20260415,
 'n_rows': 200000,
 'n_cols': 156,
 'k': 10000,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'c849c4d592b0c980c478ace6741348badcf57b22f7989ad748630d694c4f2da0',
  'user_id': 'eaeb890a4223d17c8be054d6859a701241b2051e13433adafa451cdc3e696302',
  'origin_longitude': '6410224b15e201ac842f4dca6592fc1da1dc52f4f291b38c8138974e179ca593',
  'origin_latitude': 'dd4293a55298471ecf743903c2c0534afdd456fdbb9303b7a2a19cb001c6b19d',
  'destination_longitude': 'ead1565a3117e609d20a9935b67d181235f872b5ef196c5814e2cdc831b887af',
  'destination_latitude': 'eb1d7202f964ea34b0d64fbba49c96e839cc76306c268ac40c1217bd68a1ec32',
  'origin_h3_index': '0cfd22b3e177154b186d59629e1d93a6b1f113a3f33a267c208968496ae501de',
  'destination_h3_index': '0d87fd7f869a5e38d03e721d32990ea6d3c5501935fc14f7a2f99450c02ab7b1',
  'origin_time_utc': '73b4cdf1c90dd44800773a6c11f3d1f453553333b4cf113a3b7de3231828c005',
  'destination_time_utc': '8ea92714080120fdb8ebc28d0a221d1253e13da81550061dc9b838bf74c67728',
  'trip_id': '1dafc82c67b6342629f51f6fbefc56a31d22cd78a808e5ee060492eaa42224c5',
  'movement_seq': '58e0a2f7c0e88d03332c57054d218a14ea5c2b4a408cc7a5f7780f04298ba981',
  'trip_weight': '7617eb641c10cb0168d26d3100c2f17577e68a931fba705a3daf7d0a7c7c2a09',
  'mode': '47f9de0d959ca111a9b0d414f5e82a972f53557a2c88b1dd64c4f02cb3786f5e',
  'purpose': 'c1197ec9097b9a1b764915f769a6c73222b89e1744f962ab8fffc8d5fc690722',
  'day_type': 'ba2bd9112828c4746f5edab87b01b9f7b5eb79e9fbc1a748225bb614c75f1b3b',
  'time_period': 'b5ca0460a13679fb5e0e568b74218569c1d313ed5fd97c8cb731c7c642dea477',
  'exp_cat_a_k': '1ff06c020354ae0017b9b4acd755bd3c999ce71f3aaaa7c199dea391936d5a9f',
  'exp_cat_b_k': 'e56e972ee099c51dd6bfbf560fa319f8ef08cac1e440f976e2f8f7162ebee020',
  'extra_float_001': '490613f5e5def96196598bb5d6d9585170191c047b3971b3f310f907dac355a6',
  'extra_float_002': '086fe1137a8313abd08d3ce00694ad8279d93b0c404796a9398e14b7e9e8df78',
  'extra_float_003': 'f812c4240cf0dea6d66476d754aa3ef6339295785de0d5181419899db4ef5a1d',
  'extra_float_004': '5f9f0360980d72241306edc163fa6a4429d116ac3cd1b6a5958a440c6b4d75ba',
  'extra_float_005': '87e9e006c858ea1ef80de89eb35e058d09c904435752c476ebb1dbdfefd5fe33',
  'extra_float_006': '750e92355b54c02e371f7e1b2b2df71e216b706f6b7c249ab7191f7fe405e22c',
  'extra_float_007': 'a9edf5d62e7c6447b4eead894debecaf2d77da777a5bed0e0ede2e48627b4be4',
  'extra_float_008': '149acac0a238441aabc19a923fa534e26c5760b77c94d3a181efbad654d4ba6e',
  'extra_float_009': '1f45ab72a1be5ae7c0e9667e3c3dab83dd740591b55dcc89ae9d61ae909c3220',
  'extra_float_010': '690e7353ddc260b3bcb5dc3d0b6af541c205bcf2a31268184c3d53d7747fd644',
  'extra_int_011': '915b1db6a56f4ccb00accb7db50a29e17be66aeddb3e54642a1659820fc82268',
  'extra_int_012': '7334ce1d803f356bb4d76a50cf2073191e4b661072e0773ffbbda6a2e487b691',
  'extra_int_013': '4bca3b928f258d31812f38675374309a88d026b66f4994f95c1dd3526301029a',
  'extra_int_014': 'c1c2c1f82cf4d0e11443a5d5db8d431253e60b07dd51fd6ad42d3f0e7f15122c',
  'extra_int_015': '7264debbd2528462ab33646b9a4dea45b65cd9acf242b083d7a7d682637f4991',
  'extra_bool_016': '7a2280a777894891a83b62c022b665a2c9022178b9af7dc221fb15c07b75f467',
  'extra_bool_017': 'd8a0bc303497b2363ad3cc0e39bd3c6f7b4a7d0e5c01ce29be9dfc4ffe1730f8',
  'extra_bool_018': 'c8bf5bad07aaad8c10643db06c7171398bb5952428084cd2b9d7e613f82ba6ca',
  'extra_string_019': '5866b462402b027e11c621971bd5e5abd928c9525169dfdcdb1de53fdb80639b',
  'extra_datetime_020': 'b16385727d126b2f6364e619f9d7aed5751bf526f447b505873363993f8ac636',
  'extra_float_021': '447b08ab5eb5f6ca2f2724a4c52962dfdefeffd5470918b66f2835d67d105ca6',
  'extra_float_022': '7b7b182818da3f22651bafecba3fc6ff09d40a3a30a7c6ed1da04f936b6c8f51',
  'extra_float_023': 'bf2f567bfa731320168ccfc85d0f8ab7790e121b05962ca83e11c9a9aa615600',
  'extra_float_024': 'd7d38a115c4a08fd09b0e0617ae7988812bd119f9a86e46c5676960ada0a998e',
  'extra_float_025': '78c24cd40c37f3fee0e380bd535d3b1b1ea25928b0db58c9a0b5b524281a5580',
  'extra_float_026': '83d0baf2c6e434494cd80afd635bf3fd4c0c19c375ac2e7610bc9e91e82a3497',
  'extra_float_027': '3994a19be5ca59608175c52807f7e055775f776066873ee7650fa8df26d0cbbf',
  'extra_float_028': 'bf37c2ac2a5500340de4f9dce2b131faa8752efc4cc309e149d4b5f8bed03249',
  'extra_float_029': '2200a824bede7e49401afa00235b1580f420a7053384d8e63f0a9b3cc33e4f99',
  'extra_float_030': 'a79d9d410d397ac23dfe7f29a4edd8d6e97e94864f663ea244fef308578a23af',
  'extra_int_031': '20c4368451dabd0aa5aa9954ea60aa2b998af1f11a833b33c4d97a32d26f8f0e',
  'extra_int_032': 'abe3d645b3119c75d5c61f70ee5846d91732f521e54ba1520a10bb6c267d79f3',
  'extra_int_033': '2023fb53d1060c39737b1b45906ae6de4296c4061f73e27c0d355dfe43af8984',
  'extra_int_034': 'fccf570f84da5941557b85922a7f4a8ed0b5e50498d1ef38d77afe1c9f624547',
  'extra_int_035': '18237987502b05c8a05060fc5b0212c55f3ce77cf1b89f626ef1530b6d894ac6',
  'extra_bool_036': '4a703a07afe16fda8ce2a86387b9438eeee462d87600a4d1a45df00d49c24c0f',
  'extra_bool_037': 'fe6ca639ac3e5f624014bef4ece7cdddf727c6500a0ec0e5fdc955c874173983',
  'extra_bool_038': '4977ceb5a0155695ac6b87077c8808608a0fd8edafdb1c9479d27fcb9b3440a6',
  'extra_string_039': '19f1a9b33f1d50515805c7bb44b0a5292e34daf1555c2c6a2ab821ca0ec22772',
  'extra_datetime_040': 'd86e67cecf6879c3e4188216564fd80b8ad4b077ddf2aa3545cbde94ac78a69a',
  'extra_float_041': '0361d7c40b956fabf46bbc30d8397adb646f0011ed2aef7276b6440ef62bfdd6',
  'extra_float_042': 'cc9faafa1a07875058fb6373900e6e80a300019bf1fa58ee3e5da79b2e166a2a',
  'extra_float_043': 'fba679c12bc2b405d56ef6a09fc1df5915f797cf66276b6acf2d2dbe9dae8811',
  'extra_float_044': 'b8370d5f6301cd24f25457f30f0b997743d0e26d77d396cb13752d7d2884560c',
  'extra_float_045': '0a8c3d58705dce0cbeb3d087c53930ff34b48471aadbe551f2b2d4fb88320674',
  'extra_float_046': '11ed4bbc9c8b1d6ba8cbd086bece2a1e0daf5dbcdd900e115244737bd4b1e693',
  'extra_float_047': 'e7adce33656f08fbeb5efdad373bddefeba68ad91fb6c62042b447453c7a9131',
  'extra_float_048': 'dea2d805241ac502d3257566473e4b9920d73d0e44e27c30b29e7bbcb48aebdd',
  'extra_float_049': '678e97046eba996acd4f39d59019561fc5c9deb4770579ebea6a7865f2103898',
  'extra_float_050': '5ff3aea2427341efb89182b6431b106d8489380cb309ca3eb8685b981f722b9a',
  'extra_int_051': '038a0020cdb2b281f81dcd6e74235428ef52c0e67cda16cf128c2a90d3ad6459',
  'extra_int_052': '7322d996495cdd6c9458b84034e79af3012c6cf01b990be91a4ead1fa0d25809',
  'extra_int_053': '19027b5359f06192eec80dcf01ebee6433135398dab0c2250aefbf53c36e5580',
  'extra_int_054': 'f04fdd366967310eebc4153d06ede7969eef4f3e313a25c10eca231e73d66a87',
  'extra_int_055': '05d3cf1e03b002af3c6a4490f3b096d297fb1211368f4d09af0be192a767749a',
  'extra_bool_056': '30641ac51b745cbbfa72f04ff5f5fe8ab84645ced7b3e964320b1f7d062dcbe5',
  'extra_bool_057': '0b29a842277ed1d1b84d13d46730510406fde816fe2e9f7b462be3ec2e3504dd',
  'extra_bool_058': '75fe46dc79dadcaf245945d5b5227204602e98b9b01cc7d522115a23ac1af6d3',
  'extra_string_059': '3de183912d8c111c33fc041c2c4205fb6660d448955645b726bb0a0edaab00f8',
  'extra_datetime_060': '3bf8df226fb72730397b6087a0be0bf07906959ccf8c743dc5607981db08b7c7',
  'extra_float_061': 'e1cf3adf94e6185a745c9c584ffc9a6cb31f0904dd3c481a97e87814bea20bc7',
  'extra_float_062': '64178a79a55eb29421e18ab1259756d4a5106d9868487d8ce4a61b92edd8335a',
  'extra_float_063': 'de9af0c44ec2522908d7576be762dcee4ae02d91c5b54ca00b04fdf216db6e9a',
  'extra_float_064': '319efcc3a5a3c5722f01cf28d72f2eb9a39c622e9ac6bb2ed1016fabd5616f78',
  'extra_float_065': 'e23b689b0b962227b9677527bb610f2bf9ada910b93150d8833d0ca21c82af6a',
  'extra_float_066': 'ae38f57653e89b965eb7ccf8a5f93a27399bd0d068aebabf8c17fbf9c103626d',
  'extra_float_067': '44beedf91bb78710e9a21f5c307f587fd7506d4e3bafa388ea499c92726c1581',
  'extra_float_068': 'c0889df3ecba4536ccc9f38dc266023b72bf292ed14d8cda7603d55e522675e8',
  'extra_float_069': '7e3838973aa21b801b2146fe71aaa855ecf17443a076b43e1ca3ea1ae700c144',
  'extra_float_070': 'e0c27ab608f6f6a3ae86ab9501166d9b2f76e2e8a23b2ef5282883f3017e02e3',
  'extra_int_071': '753f877bf071accd172c63248ddc1e13c5f2f664c94688ddc743ff3be98188d8',
  'extra_int_072': '6fa1e46fce8b3740d234384219253f1e6dc363e4ad343535084bb0668cca45e4',
  'extra_int_073': 'd9ccf1e8653fdc9b79accb3fdd7cf0ae8c1ea5189b2ec5c01a89980322eaf9bf',
  'extra_int_074': 'd92256606efd60adf4a1180b832c1c4958ed6c26c07622f4353ecc7ce24ee554',
  'extra_int_075': 'a770a7d51fb921375728d03f5b282f75e9bb5fdf2d0d2f368b519cfbdb3b0fe7',
  'extra_bool_076': 'c5aa5a43e66d45b7a650a6364c51a52c0835acb407428929c26ba0093907cc99',
  'extra_bool_077': '8003510534bda296373e0aabd99b0358a94a5c0d69a6438d4ae545289f852e17',
  'extra_bool_078': 'afa2e00572991f018a8b1af75f8c0fe5eb2dcf5d94f326b3891665b85e9bfc24',
  'extra_string_079': '3ebca6c9f996873681bb9491a9dd025c529a09847acd5fdfbdea3c9dc1b9da9f',
  'extra_datetime_080': '43156b6e80e8c2f8aa0b15e25bd88af811faf0fa77df1a306f233e40416d6c79',
  'extra_float_081': 'eff6f7239ec29c821c30810ff033ebf185b94c3ba0af3e59ebc9b784efbf97cc',
  'extra_float_082': '945729a24f522755c77658ca718fbbee991f05229f648dbafd608ec6495e91fb',
  'extra_float_083': '0d1e097e3805fdc8cfbaa3bbe59371de3c6040cb38356b60b2242d3fb0733939',
  'extra_float_084': 'a5d7cfe1da461b59c76db61ff3d147236e781e670935f3ba97a9707949639ba3',
  'extra_float_085': '32c39df7d46c74c9de50735241b5d78488e3302bcfed41a175745d4ecb33bdfc',
  'extra_float_086': '9ed94b4ccaa01d837c7cfb6a2f79aae7e2f476312c3f05ae10c6f35d904a5939',
  'extra_float_087': '2756227eec346f0f5435c8c6c97edf5647b48ef38babe46847d63022c591b6a3',
  'extra_float_088': '2090919261c1ed13eef95d0f14b06b25855008edc7163db3ab511620b0eb18b9',
  'extra_float_089': '942f7ce296fa8c87bfdaa82ec4699e4ad0ed4af049e6ae990449f3e9a0ea2583',
  'extra_float_090': '60176cd4ca9161576272bbc17baa1917eac2a24b2fef8d44c939546056f9f1ef',
  'extra_int_091': 'de68caa2dbf93507bae00ecd146b902df49c1d31c550d2c73625773e72152393',
  'extra_int_092': 'e9a8ed17f49b63e7bbef3c67f4f43c764ac0bb590212c37a122bd5d7f0e619b9',
  'extra_int_093': '67528ca3d8fa06014cb68f1c63f82d9ecfeee4e3b5620b6cd564c58fb3745545',
  'extra_int_094': '77b17a4fac32b25aac3a2f3d1171680340a299be504e68b30ae9da05c2e1e59e',
  'extra_int_095': 'cd4711d503d6bf4eb73bb0078bdd020776e25b8ce0d8d6aec8613198fb470b08',
  'extra_bool_096': 'bb9b17fc628ab8a90b65e5cd6827a20397f85a8e1ba3df5f593d2166ea2bd75f',
  'extra_bool_097': '78fe50fd0a4276493df50ab00ab949084444fc261e861c0ce324da8cac20f8f2',
  'extra_bool_098': '7bbfa8504669cbb6a5b3bd155e79157555b12ed1d1c3a47e227ed202e13772ee',
  'extra_string_099': '1e19e6fe60c4a28b6d83abd7a1e6ae18f218e0af0a015db934a5bf862c5fc730',
  'extra_datetime_100': '00060a1e36bddb3592ceb51c3ea6d45c01c03205b78d4e1bc2cbe1b91ba1cd6b',
  'extra_float_101': '14765350f8e0c2e34410243f12d514932802933c14107b868d87a73693d716ff',
  'extra_float_102': '5e4e191f436db12623f9c0f3dfd0b603e2335e58e13f9268e566ac055cad1f68',
  'extra_float_103': '5121fed186481a710db9bade91619de652fd9f5d9ad1435e7d88d6062ffb36c5',
  'extra_float_104': '56bf3bea2be57b91cb6ebde74c93406df00de36d960aed5cd654032c2faf9c5b',
  'extra_float_105': '1bcb3a59b9d906f274a26a8a0053013f4ec5fe58f196e00c4147a094d8476da8',
  'extra_float_106': '49f8b27817fe5d1a7a89a05683447b5c307f6c9482dee95f6d12e4cc5063e29b',
  'extra_float_107': '25eaa368c2cc9c6162ad4af456eb79849e4ffab951b4c08544806a856a99dfb7',
  'extra_float_108': 'ff7e9649c5729bf4cd7e9a73f4cb318ea9c70aba4ae9ee68e351d4a7fc712827',
  'extra_float_109': '5b0936099e67043bbb8ec363f19cf288a6c330f7cfb375e0c59de293084de010',
  'extra_float_110': '1438c596210c72bc887e5480053ba12539076131a380df41f52f6610e5a9a846',
  'extra_int_111': '676c789b110486e4b096c1f1e4a8a6329605e8710c1fec30bcbcdd788e413eab',
  'extra_int_112': 'c57e667c441ad6f5ae579d9168c8a6388b746bcb15abc38e66b7be3a7880183e',
  'extra_int_113': '78d955ec4299018b377e469f437f50745a11a2b34b1e8da55ad66048869c35b7',
  'extra_int_114': '973908c004ac6b136779f6392d97be14220c32ff0ef4fbe7f9e03a3eb105ca53',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_236  extra_bool_237
0       m000000000  u0000000  ...           False            True
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...           False           False
3       m000000003  u0000003  ...            True            True
4       m000000004  u0000004  ...            True            True
...            ...       ...  ...             ...             ...
999995  m000999995  u0199995  ...            True            True
999996  m000999996  u0199996  ...            True           False
999997  m000999997  u0199997  ...           False            True
999998  m000999998  u0199998  ...            True           False
999999  m000999999  u0199999  ...           False           False

[1000000 rows x 256 columns]

{'config_id': 'C8',
 'seed': 20260415,
 'n_rows': 1000000,
 'n_cols': 256,
 'k': 10,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137',
  'extra_bool_138',
  'extra_string_139',
  'extra_datetime_140',
  'extra_float_141',
  'extra_float_142',
  'extra_float_143',
  'extra_float_144',
  'extra_float_145',
  'extra_float_146',
  'extra_float_147',
  'extra_float_148',
  'extra_float_149',
  'extra_float_150',
  'extra_int_151',
  'extra_int_152',
  'extra_int_153',
  'extra_int_154',
  'extra_int_155',
  'extra_bool_156',
  'extra_bool_157',
  'extra_bool_158',
  'extra_string_159',
  'extra_datetime_160',
  'extra_float_161',
  'extra_float_162',
  'extra_float_163',
  'extra_float_164',
  'extra_float_165',
  'extra_float_166',
  'extra_float_167',
  'extra_float_168',
  'extra_float_169',
  'extra_float_170',
  'extra_int_171',
  'extra_int_172',
  'extra_int_173',
  'extra_int_174',
  'extra_int_175',
  'extra_bool_176',
  'extra_bool_177',
  'extra_bool_178',
  'extra_string_179',
  'extra_datetime_180',
  'extra_float_181',
  'extra_float_182',
  'extra_float_183',
  'extra_float_184',
  'extra_float_185',
  'extra_float_186',
  'extra_float_187',
  'extra_float_188',
  'extra_float_189',
  'extra_float_190',
  'extra_int_191',
  'extra_int_192',
  'extra_int_193',
  'extra_int_194',
  'extra_int_195',
  'extra_bool_196',
  'extra_bool_197',
  'extra_bool_198',
  'extra_string_199',
  'extra_datetime_200',
  'extra_float_201',
  'extra_float_202',
  'extra_float_203',
  'extra_float_204',
  'extra_float_205',
  'extra_float_206',
  'extra_float_207',
  'extra_float_208',
  'extra_float_209',
  'extra_float_210',
  'extra_int_211',
  'extra_int_212',
  'extra_int_213',
  'extra_int_214',
  'extra_int_215',
  'extra_bool_216',
  'extra_bool_217',
  'extra_bool_218',
  'extra_string_219',
  'extra_datetime_220',
  'extra_float_221',
  'extra_float_222',
  'extra_float_223',
  'extra_float_224',
  'extra_float_225',
  'extra_float_226',
  'extra_float_227',
  'extra_float_228',
  'extra_float_229',
  'extra_float_230',
  'extra_int_231',
  'extra_int_232',
  'extra_int_233',
  'extra_int_234',
  'extra_int_235',
  'extra_bool_236',
  'extra_bool_237'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean',
  'extra_bool_138': 'boolean',
  'extra_string_139': 'string',
  'extra_datetime_140': 'datetime64[ns]',
  'extra_float_141': 'float32',
  'extra_float_142': 'float32',
  'extra_float_143': 'float32',
  'extra_float_144': 'float32',
  'extra_float_145': 'float32',
  'extra_float_146': 'float32',
  'extra_float_147': 'float32',
  'extra_float_148': 'float32',
  'extra_float_149': 'float32',
  'extra_float_150': 'float32',
  'extra_int_151': 'int32',
  'extra_int_152': 'int32',
  'extra_int_153': 'int32',
  'extra_int_154': 'int32',
  'extra_int_155': 'int32',
  'extra_bool_156': 'boolean',
  'extra_bool_157': 'boolean',
  'extra_bool_158': 'boolean',
  'extra_string_159': 'string',
  'extra_datetime_160': 'datetime64[ns]',
  'extra_float_161': 'float32',
  'extra_float_162': 'float32',
  'extra_float_163': 'float32',
  'extra_float_164': 'float32',
  'extra_float_165': 'float32',
  'extra_float_166': 'float32',
  'extra_float_167': 'float32',
  'extra_float_168': 'float32',
  'extra_float_169': 'float32',
  'extra_float_170': 'float32',
  'extra_int_171': 'int32',
  'extra_int_172': 'int32',
  'extra_int_173': 'int32',
  'extra_int_174': 'int32',
  'extra_int_175': 'int32',
  'extra_bool_176': 'boolean',
  'extra_bool_177': 'boolean',
  'extra_bool_178': 'boolean',
  'extra_string_179': 'string',
  'extra_datetime_180': 'datetime64[ns]',
  'extra_float_181': 'float32',
  'extra_float_182': 'float32',
  'extra_float_183': 'float32',
  'extra_float_184': 'float32',
  'extra_float_185': 'float32',
  'extra_float_186': 'float32',
  'extra_float_187': 'float32',
  'extra_float_188': 'float32',
  'extra_float_189': 'float32',
  'extra_float_190': 'float32',
  'extra_int_191': 'int32',
  'extra_int_192': 'int32',
  'extra_int_193': 'int32',
  'extra_int_194': 'int32',
  'extra_int_195': 'int32',
  'extra_bool_196': 'boolean',
  'extra_bool_197': 'boolean',
  'extra_bool_198': 'boolean',
  'extra_string_199': 'string',
  'extra_datetime_200': 'datetime64[ns]',
  'extra_float_201': 'float32',
  'extra_float_202': 'float32',
  'extra_float_203': 'float32',
  'extra_float_204': 'float32',
  'extra_float_205': 'float32',
  'extra_float_206': 'float32',
  'extra_float_207': 'float32',
  'extra_float_208': 'float32',
  'extra_float_209': 'float32',
  'extra_float_210': 'float32',
  'extra_int_211': 'int32',
  'extra_int_212': 'int32',
  'extra_int_213': 'int32',
  'extra_int_214': 'int32',
  'extra_int_215': 'int32',
  'extra_bool_216': 'boolean',
  'extra_bool_217': 'boolean',
  'extra_bool_218': 'boolean',
  'extra_string_219': 'string',
  'extra_datetime_220': 'datetime64[ns]',
  'extra_float_221': 'float32',
  'extra_float_222': 'float32',
  'extra_float_223': 'float32',
  'extra_float_224': 'float32',
  'extra_float_225': 'float32',
  'extra_float_226': 'float32',
  'extra_float_227': 'float32',
  'extra_float_228': 'float32',
  'extra_float_229': 'float32',
  'extra_float_230': 'float32',
  'extra_int_231': 'int32',
  'extra_int_232': 'int32',
  'extra_int_233': 'int32',
  'extra_int_234': 'int32',
  'extra_int_235': 'int32',
  'extra_bool_236': 'boolean',
  'extra_bool_237': 'boolean'},
 'column_fingerprints': {'movement_id': 'cb3f67ad59018b5e3e4d8eedcfd4ac72a676550b8406aad93429d806c74b7920',
  'user_id': '65f89204fe232f167e13db27140e38292930107b27ddff177c3bcba8324c1fa9',
  'origin_longitude': 'ceba053d9212e5c1db80e77c89fa05a6a180e9472fe246d92468f00703bb526f',
  'origin_latitude': '995dc7efa75779356579efccd1f9a0aed9b78b3e9ce410c0447c733ff2b8cb45',
  'destination_longitude': '16dcb9e3bb41a2a0266c434f373be6c4cab5827d662ab0f3186a71d5d12fc876',
  'destination_latitude': 'e2030db41304350b4661f6130e99d973da53aec8f1714eab78dad2db12233986',
  'origin_h3_index': 'b5a8eef8f9c9292ec626457f6a971f442822a30d53d86b26f2d2707d87d3d7db',
  'destination_h3_index': 'f722e9a5cc8b58392086852c004a9bfea33bc60bd7bf20c6421a5dc82cad8786',
  'origin_time_utc': '01321ba6312a3f398fdfec99ab6c971a070fe62fbcf6c4bf8c1bd87e391ba997',
  'destination_time_utc': '13706e69ff7155260cb85b6b546356adaa5bc346d652e05b6843b577c8f794cb',
  'trip_id': '0df800f6554a384308f0134c08b5b5112df154a6701736005951783471e3f82b',
  'movement_seq': '6506614505e113daab08b3f894ca46d4d61867c7b007c413b47a669abe8aae67',
  'trip_weight': '963f8cecbac5fba8cfb088a2d743ff1769a915ae20d506123bdd266a74cbf2a0',
  'mode': '1667d7157767d2577465659f1b7ba6edf41bb10f062e350b03b083890bd252cd',
  'purpose': 'b2f736fe9d9c948ec8d7a94f42998c926899089cfcffdc33acf803367fec3be8',
  'day_type': '50ee05cc4c2ed9daf9d66c5baf0fd604e24a8f29de2324dac9e412ca2a84e912',
  'time_period': '0ba244f6bc3b226e122a70b71f700f917c555d12bd6336365621b93ddaa05f0b',
  'exp_cat_a_k': '11a90923d2670d239d6fb52cc3abb8acadf8206c44ea3fc0f70ce9eb6e17b7c7',
  'exp_cat_b_k': '8df595575a9c373475d0c0aa4ae6198d951406dfc7681242a02edb5054de9f98',
  'extra_float_001': '8742bb8e23e7c729982fa8d05651752899669ae2cbbd7f28102b8332edd2c698',
  'extra_float_002': '79570d09d10703b379e5865e8a97121bac45bf8228b2909a99805a9acd55bb60',
  'extra_float_003': 'b429e05224b3f917ba5f8f3fc6c7e172541b4cd712677c88def4ecf128e51548',
  'extra_float_004': 'f162dcdd32b179a84d74d01a023f40df6cdf65202d62d03299f536514c37967d',
  'extra_float_005': '18d0b812fd8dd5801a95e1832f453d721d35c29c83bb6ddebc52f97fe569ced8',
  'extra_float_006': 'fc42b9325ba5ffb55bf58eea24357d23774b5f76fff7e2828b12046c56e23374',
  'extra_float_007': '65125cb08f9fb11a42838485d3c22289cfa9c5e2483ddcf04e93a2ca23b17805',
  'extra_float_008': 'ef87e06374999709a0ceac2d028d3e3ad535296baeb755631dd668fca3aca3a0',
  'extra_float_009': '4db06161d9de8313dd34867af05de6b7c0fb68c07190c73a742aa62555e71d69',
  'extra_float_010': '9c38e1c1b2f7bf7cffc1e1b91cd4e1bd0c2da39fad205744be0ed92673f5d944',
  'extra_int_011': '3f0c53276c5f72d90ffc8ff8b50563725e54512d9010f04ec4ca8caab6c002e6',
  'extra_int_012': '7061924898220d620dd0ff64e7845017efc047b5e5c1afacdf11d193c037d2c9',
  'extra_int_013': '19415c3abbe5dade594f97831d286a816bcacd7daa5f9159187eb577c2bdf717',
  'extra_int_014': 'e693931e3f1a8b09b5388fd6c5975bf5321e0d26937a91f1ace2391d1e95ad25',
  'extra_int_015': '39d06dcf2593d6508c82dbb6236e3b20d2b51ebd3bbe7a284aedaead60bc61a6',
  'extra_bool_016': '54f79df2524164e2dfdd6cba8f5f30776fdacc0349459957dfc92e5b3b3fc120',
  'extra_bool_017': 'cc4a1dea789b953c097c84ce44b04f5b9489b7d18d94543dc6b2aa46f92a928a',
  'extra_bool_018': 'f030070f515956885f894abf314d7805a7a661ee22a6b3addb3d76a1f2bb34cf',
  'extra_string_019': '722186eb87aaf3c56ecb898794afa48c52ae57ab3e645b742af871d635000ef3',
  'extra_datetime_020': '0c972223f4a5a77a2f5283401db4fb23bab8403b1ea6ca644734ea33a6ad7af6',
  'extra_float_021': 'a0b47e8c223d359d41ad97daec6582d9c24836903ee965d0a8a23cd9e96221a5',
  'extra_float_022': '427f38149d34c669f73544c9f479483b67c83c84fca512f8d8b3281da04b11dd',
  'extra_float_023': 'e4acf50733b073bafece296bacc2372efd9ed1638b6dad8436a90fa1b278d71b',
  'extra_float_024': '98bb58a78690cce75c22ca01cbd528bf89f2c7eb54dfc46c2e85bad0673b8d7c',
  'extra_float_025': 'c2628adf118f7811dfd1a0ce48c87cdafc3cc20be0712c8289d5b1b8e9be28d0',
  'extra_float_026': '5441083e6c1c7841abc58c467d877e4b59387e936c0db0664614d900cff1d209',
  'extra_float_027': 'ae67fb6f61ada92e6a637f36bb633fdc6c890467abdaaa2ec4b588314f78b57b',
  'extra_float_028': '41501490497778ba90e4870b399438478f718f56ad7b585505d6330ec98c8cb9',
  'extra_float_029': 'ad38a8777d2f853678cce47e9abf48c30bc1f9b9ed0ff6d765000bfa0b9e656b',
  'extra_float_030': 'bcd6002fe0712ed1e89919442b60786b9501def85e9d2d2a69c7d1f2a6e35466',
  'extra_int_031': '1feea78dff8e12fce1bdb0d63cd3f97cbc544a684c11c6365acefac954ce4e1d',
  'extra_int_032': '9e52d6850db34b4a7db9b87c6503013606eb6e5ad36f8369567594be1f0de1f9',
  'extra_int_033': '83ba7337de983f9d41cbfcb9afa807fbf0f075a2114ba2d6c2cd50e3e01dbdb5',
  'extra_int_034': '16db288059c463a90d1107eedcef12de8a05defdf46b165dce699122a41119ef',
  'extra_int_035': '704467f0b07d9da4281d158214d8038602bdfbbe511a38193c2118b469f7b2ff',
  'extra_bool_036': '508e8bdff1f91643bd1a11172cc76cf346cebb52ca61b04f5ccea02d66e45b91',
  'extra_bool_037': '7a08bf80cb21a7ed74e3e7d7255b2296a6d0c38f7cf0dc2a2466c430328d9634',
  'extra_bool_038': '3d4cb2929c9b9a694693ae880a124999fdec788fbff625efa283259de61fb87b',
  'extra_string_039': '32a7a3e8f5ac4e83ab7a56bfb35be5bff5e1668876e65b89e7816c59b03e0993',
  'extra_datetime_040': '91bd3a5d3d3057827f056bd1907eca63f39d12c90d2ac8e6f9bc981689bcf543',
  'extra_float_041': '372d1099419602a54ef17e61288d38a94ff54f5e0aad6522870ef58ba8ff9c1f',
  'extra_float_042': '260f01c9c2c9ade617a93bfc8f153170be1d0055643a86039bd12a6ddf06ce8a',
  'extra_float_043': '4aac3f36c424f4b5f71cd0729d6e3f34b798bea965b5c5f17f531e1f54859340',
  'extra_float_044': 'c10c65b6925ca328ce460c32d7b85444d4141cfeb31fdde82219e4fd08853509',
  'extra_float_045': '6fbd2623cce75c8c6bdd02137df35595dbc7b601c19f7a9ef31d2877ced254a3',
  'extra_float_046': 'ed64f7a40fe269a612a6582b4be210ce64f5d1cbca7b0080f834bbd3fd90735a',
  'extra_float_047': '873763d5ddc42beca5132dee0ef8e58384b6c8786dcbfd17850df0b53a37488f',
  'extra_float_048': 'b3b09ebd31f13ec298f7b4b9fb1d71381fa2dcd262e2631e0937dc75e3fd1e2c',
  'extra_float_049': '7c0bc8d3c94b5222911c370d1c0ab75b39230d348a4747eba7e1b77d479f47a1',
  'extra_float_050': '24efed12c564ca5c6ddf2718e9cde8bbcad4d65a7c665a5a55a8872a60928f06',
  'extra_int_051': 'e25301ccace2aad9541f9f7835973500058085e03b417357ab41424d297f517a',
  'extra_int_052': '61f5bc011c3adff153f0c913a551798f84d31233f7cb01a96e4d25fcd2c9dccd',
  'extra_int_053': '3b64042a8685a97f28c9f0427313932c6a7bea26283d67f9669f66e45828357c',
  'extra_int_054': '78ffdcdd975ef3ad1532b1b7a70900ad3238b4f8b505ab4400917d852031efc3',
  'extra_int_055': '67fe12ce74dc9fa45dab2d135eab26a105487244ac782b2519a6b0b3713d0aa8',
  'extra_bool_056': '2e48da8e57931a797735d9313284eef0e4b0a3036c015e84597ada9d1983b6e9',

Dataframe generado y fingerprint generado

       movement_id   user_id  ...  extra_bool_136  extra_bool_137
0       m000000000  u0000000  ...           False            True
1       m000000001  u0000001  ...            True            True
2       m000000002  u0000002  ...            True           False
3       m000000003  u0000003  ...            True            True
4       m000000004  u0000004  ...            True            True
...            ...       ...  ...             ...             ...
999995  m000999995  u0199995  ...           False            True
999996  m000999996  u0199996  ...            True           False
999997  m000999997  u0199997  ...            True           False
999998  m000999998  u0199998  ...            True           False
999999  m000999999  u0199999  ...            True           False

[1000000 rows x 156 columns]

{'config_id': 'C9',
 'seed': 20260415,
 'n_rows': 1000000,
 'n_cols': 156,
 'k': 10000,
 'columns_order': ['movement_id',
  'user_id',
  'origin_longitude',
  'origin_latitude',
  'destination_longitude',
  'destination_latitude',
  'origin_h3_index',
  'destination_h3_index',
  'origin_time_utc',
  'destination_time_utc',
  'trip_id',
  'movement_seq',
  'trip_weight',
  'mode',
  'purpose',
  'day_type',
  'time_period',
  'exp_cat_a_k',
  'exp_cat_b_k',
  'extra_float_001',
  'extra_float_002',
  'extra_float_003',
  'extra_float_004',
  'extra_float_005',
  'extra_float_006',
  'extra_float_007',
  'extra_float_008',
  'extra_float_009',
  'extra_float_010',
  'extra_int_011',
  'extra_int_012',
  'extra_int_013',
  'extra_int_014',
  'extra_int_015',
  'extra_bool_016',
  'extra_bool_017',
  'extra_bool_018',
  'extra_string_019',
  'extra_datetime_020',
  'extra_float_021',
  'extra_float_022',
  'extra_float_023',
  'extra_float_024',
  'extra_float_025',
  'extra_float_026',
  'extra_float_027',
  'extra_float_028',
  'extra_float_029',
  'extra_float_030',
  'extra_int_031',
  'extra_int_032',
  'extra_int_033',
  'extra_int_034',
  'extra_int_035',
  'extra_bool_036',
  'extra_bool_037',
  'extra_bool_038',
  'extra_string_039',
  'extra_datetime_040',
  'extra_float_041',
  'extra_float_042',
  'extra_float_043',
  'extra_float_044',
  'extra_float_045',
  'extra_float_046',
  'extra_float_047',
  'extra_float_048',
  'extra_float_049',
  'extra_float_050',
  'extra_int_051',
  'extra_int_052',
  'extra_int_053',
  'extra_int_054',
  'extra_int_055',
  'extra_bool_056',
  'extra_bool_057',
  'extra_bool_058',
  'extra_string_059',
  'extra_datetime_060',
  'extra_float_061',
  'extra_float_062',
  'extra_float_063',
  'extra_float_064',
  'extra_float_065',
  'extra_float_066',
  'extra_float_067',
  'extra_float_068',
  'extra_float_069',
  'extra_float_070',
  'extra_int_071',
  'extra_int_072',
  'extra_int_073',
  'extra_int_074',
  'extra_int_075',
  'extra_bool_076',
  'extra_bool_077',
  'extra_bool_078',
  'extra_string_079',
  'extra_datetime_080',
  'extra_float_081',
  'extra_float_082',
  'extra_float_083',
  'extra_float_084',
  'extra_float_085',
  'extra_float_086',
  'extra_float_087',
  'extra_float_088',
  'extra_float_089',
  'extra_float_090',
  'extra_int_091',
  'extra_int_092',
  'extra_int_093',
  'extra_int_094',
  'extra_int_095',
  'extra_bool_096',
  'extra_bool_097',
  'extra_bool_098',
  'extra_string_099',
  'extra_datetime_100',
  'extra_float_101',
  'extra_float_102',
  'extra_float_103',
  'extra_float_104',
  'extra_float_105',
  'extra_float_106',
  'extra_float_107',
  'extra_float_108',
  'extra_float_109',
  'extra_float_110',
  'extra_int_111',
  'extra_int_112',
  'extra_int_113',
  'extra_int_114',
  'extra_int_115',
  'extra_bool_116',
  'extra_bool_117',
  'extra_bool_118',
  'extra_string_119',
  'extra_datetime_120',
  'extra_float_121',
  'extra_float_122',
  'extra_float_123',
  'extra_float_124',
  'extra_float_125',
  'extra_float_126',
  'extra_float_127',
  'extra_float_128',
  'extra_float_129',
  'extra_float_130',
  'extra_int_131',
  'extra_int_132',
  'extra_int_133',
  'extra_int_134',
  'extra_int_135',
  'extra_bool_136',
  'extra_bool_137'],
 'dtypes_expected': {'movement_id': 'string',
  'user_id': 'string',
  'origin_longitude': 'float64',
  'origin_latitude': 'float64',
  'destination_longitude': 'float64',
  'destination_latitude': 'float64',
  'origin_h3_index': 'string',
  'destination_h3_index': 'string',
  'origin_time_utc': 'datetime64[ns]',
  'destination_time_utc': 'datetime64[ns]',
  'trip_id': 'string',
  'movement_seq': 'int16',
  'trip_weight': 'float32',
  'mode': 'category',
  'purpose': 'category',
  'day_type': 'category',
  'time_period': 'category',
  'exp_cat_a_k': 'category',
  'exp_cat_b_k': 'category',
  'extra_float_001': 'float32',
  'extra_float_002': 'float32',
  'extra_float_003': 'float32',
  'extra_float_004': 'float32',
  'extra_float_005': 'float32',
  'extra_float_006': 'float32',
  'extra_float_007': 'float32',
  'extra_float_008': 'float32',
  'extra_float_009': 'float32',
  'extra_float_010': 'float32',
  'extra_int_011': 'int32',
  'extra_int_012': 'int32',
  'extra_int_013': 'int32',
  'extra_int_014': 'int32',
  'extra_int_015': 'int32',
  'extra_bool_016': 'boolean',
  'extra_bool_017': 'boolean',
  'extra_bool_018': 'boolean',
  'extra_string_019': 'string',
  'extra_datetime_020': 'datetime64[ns]',
  'extra_float_021': 'float32',
  'extra_float_022': 'float32',
  'extra_float_023': 'float32',
  'extra_float_024': 'float32',
  'extra_float_025': 'float32',
  'extra_float_026': 'float32',
  'extra_float_027': 'float32',
  'extra_float_028': 'float32',
  'extra_float_029': 'float32',
  'extra_float_030': 'float32',
  'extra_int_031': 'int32',
  'extra_int_032': 'int32',
  'extra_int_033': 'int32',
  'extra_int_034': 'int32',
  'extra_int_035': 'int32',
  'extra_bool_036': 'boolean',
  'extra_bool_037': 'boolean',
  'extra_bool_038': 'boolean',
  'extra_string_039': 'string',
  'extra_datetime_040': 'datetime64[ns]',
  'extra_float_041': 'float32',
  'extra_float_042': 'float32',
  'extra_float_043': 'float32',
  'extra_float_044': 'float32',
  'extra_float_045': 'float32',
  'extra_float_046': 'float32',
  'extra_float_047': 'float32',
  'extra_float_048': 'float32',
  'extra_float_049': 'float32',
  'extra_float_050': 'float32',
  'extra_int_051': 'int32',
  'extra_int_052': 'int32',
  'extra_int_053': 'int32',
  'extra_int_054': 'int32',
  'extra_int_055': 'int32',
  'extra_bool_056': 'boolean',
  'extra_bool_057': 'boolean',
  'extra_bool_058': 'boolean',
  'extra_string_059': 'string',
  'extra_datetime_060': 'datetime64[ns]',
  'extra_float_061': 'float32',
  'extra_float_062': 'float32',
  'extra_float_063': 'float32',
  'extra_float_064': 'float32',
  'extra_float_065': 'float32',
  'extra_float_066': 'float32',
  'extra_float_067': 'float32',
  'extra_float_068': 'float32',
  'extra_float_069': 'float32',
  'extra_float_070': 'float32',
  'extra_int_071': 'int32',
  'extra_int_072': 'int32',
  'extra_int_073': 'int32',
  'extra_int_074': 'int32',
  'extra_int_075': 'int32',
  'extra_bool_076': 'boolean',
  'extra_bool_077': 'boolean',
  'extra_bool_078': 'boolean',
  'extra_string_079': 'string',
  'extra_datetime_080': 'datetime64[ns]',
  'extra_float_081': 'float32',
  'extra_float_082': 'float32',
  'extra_float_083': 'float32',
  'extra_float_084': 'float32',
  'extra_float_085': 'float32',
  'extra_float_086': 'float32',
  'extra_float_087': 'float32',
  'extra_float_088': 'float32',
  'extra_float_089': 'float32',
  'extra_float_090': 'float32',
  'extra_int_091': 'int32',
  'extra_int_092': 'int32',
  'extra_int_093': 'int32',
  'extra_int_094': 'int32',
  'extra_int_095': 'int32',
  'extra_bool_096': 'boolean',
  'extra_bool_097': 'boolean',
  'extra_bool_098': 'boolean',
  'extra_string_099': 'string',
  'extra_datetime_100': 'datetime64[ns]',
  'extra_float_101': 'float32',
  'extra_float_102': 'float32',
  'extra_float_103': 'float32',
  'extra_float_104': 'float32',
  'extra_float_105': 'float32',
  'extra_float_106': 'float32',
  'extra_float_107': 'float32',
  'extra_float_108': 'float32',
  'extra_float_109': 'float32',
  'extra_float_110': 'float32',
  'extra_int_111': 'int32',
  'extra_int_112': 'int32',
  'extra_int_113': 'int32',
  'extra_int_114': 'int32',
  'extra_int_115': 'int32',
  'extra_bool_116': 'boolean',
  'extra_bool_117': 'boolean',
  'extra_bool_118': 'boolean',
  'extra_string_119': 'string',
  'extra_datetime_120': 'datetime64[ns]',
  'extra_float_121': 'float32',
  'extra_float_122': 'float32',
  'extra_float_123': 'float32',
  'extra_float_124': 'float32',
  'extra_float_125': 'float32',
  'extra_float_126': 'float32',
  'extra_float_127': 'float32',
  'extra_float_128': 'float32',
  'extra_float_129': 'float32',
  'extra_float_130': 'float32',
  'extra_int_131': 'int32',
  'extra_int_132': 'int32',
  'extra_int_133': 'int32',
  'extra_int_134': 'int32',
  'extra_int_135': 'int32',
  'extra_bool_136': 'boolean',
  'extra_bool_137': 'boolean'},
 'column_fingerprints': {'movement_id': 'cb3f67ad59018b5e3e4d8eedcfd4ac72a676550b8406aad93429d806c74b7920',
  'user_id': '65f89204fe232f167e13db27140e38292930107b27ddff177c3bcba8324c1fa9',
  'origin_longitude': 'ceba053d9212e5c1db80e77c89fa05a6a180e9472fe246d92468f00703bb526f',
  'origin_latitude': '995dc7efa75779356579efccd1f9a0aed9b78b3e9ce410c0447c733ff2b8cb45',
  'destination_longitude': '16dcb9e3bb41a2a0266c434f373be6c4cab5827d662ab0f3186a71d5d12fc876',
  'destination_latitude': 'e2030db41304350b4661f6130e99d973da53aec8f1714eab78dad2db12233986',
  'origin_h3_index': 'b5a8eef8f9c9292ec626457f6a971f442822a30d53d86b26f2d2707d87d3d7db',
  'destination_h3_index': 'f722e9a5cc8b58392086852c004a9bfea33bc60bd7bf20c6421a5dc82cad8786',
  'origin_time_utc': '01321ba6312a3f398fdfec99ab6c971a070fe62fbcf6c4bf8c1bd87e391ba997',
  'destination_time_utc': '13706e69ff7155260cb85b6b546356adaa5bc346d652e05b6843b577c8f794cb',
  'trip_id': '0df800f6554a384308f0134c08b5b5112df154a6701736005951783471e3f82b',
  'movement_seq': '6506614505e113daab08b3f894ca46d4d61867c7b007c413b47a669abe8aae67',
  'trip_weight': '963f8cecbac5fba8cfb088a2d743ff1769a915ae20d506123bdd266a74cbf2a0',
  'mode': '1667d7157767d2577465659f1b7ba6edf41bb10f062e350b03b083890bd252cd',
  'purpose': 'b2f736fe9d9c948ec8d7a94f42998c926899089cfcffdc33acf803367fec3be8',
  'day_type': '50ee05cc4c2ed9daf9d66c5baf0fd604e24a8f29de2324dac9e412ca2a84e912',
  'time_period': '0ba244f6bc3b226e122a70b71f700f917c555d12bd6336365621b93ddaa05f0b',
  'exp_cat_a_k': 'f362c33760df2f1caa55079e7083036eb5fdb89af68ca2d81a517e9155c3b099',
  'exp_cat_b_k': 'fe05dceb3292b56ed749540514f3606c74285dded028db97073973f364759c1d',
  'extra_float_001': '8742bb8e23e7c729982fa8d05651752899669ae2cbbd7f28102b8332edd2c698',
  'extra_float_002': '79570d09d10703b379e5865e8a97121bac45bf8228b2909a99805a9acd55bb60',
  'extra_float_003': 'b429e05224b3f917ba5f8f3fc6c7e172541b4cd712677c88def4ecf128e51548',
  'extra_float_004': 'f162dcdd32b179a84d74d01a023f40df6cdf65202d62d03299f536514c37967d',
  'extra_float_005': '18d0b812fd8dd5801a95e1832f453d721d35c29c83bb6ddebc52f97fe569ced8',
  'extra_float_006': 'fc42b9325ba5ffb55bf58eea24357d23774b5f76fff7e2828b12046c56e23374',
  'extra_float_007': '65125cb08f9fb11a42838485d3c22289cfa9c5e2483ddcf04e93a2ca23b17805',
  'extra_float_008': 'ef87e06374999709a0ceac2d028d3e3ad535296baeb755631dd668fca3aca3a0',
  'extra_float_009': '4db06161d9de8313dd34867af05de6b7c0fb68c07190c73a742aa62555e71d69',
  'extra_float_010': '9c38e1c1b2f7bf7cffc1e1b91cd4e1bd0c2da39fad205744be0ed92673f5d944',
  'extra_int_011': '3f0c53276c5f72d90ffc8ff8b50563725e54512d9010f04ec4ca8caab6c002e6',
  'extra_int_012': '7061924898220d620dd0ff64e7845017efc047b5e5c1afacdf11d193c037d2c9',
  'extra_int_013': '19415c3abbe5dade594f97831d286a816bcacd7daa5f9159187eb577c2bdf717',
  'extra_int_014': 'e693931e3f1a8b09b5388fd6c5975bf5321e0d26937a91f1ace2391d1e95ad25',
  'extra_int_015': '39d06dcf2593d6508c82dbb6236e3b20d2b51ebd3bbe7a284aedaead60bc61a6',
  'extra_bool_016': '54f79df2524164e2dfdd6cba8f5f30776fdacc0349459957dfc92e5b3b3fc120',
  'extra_bool_017': 'cc4a1dea789b953c097c84ce44b04f5b9489b7d18d94543dc6b2aa46f92a928a',
  'extra_bool_018': 'f030070f515956885f894abf314d7805a7a661ee22a6b3addb3d76a1f2bb34cf',
  'extra_string_019': '722186eb87aaf3c56ecb898794afa48c52ae57ab3e645b742af871d635000ef3',
  'extra_datetime_020': '0c972223f4a5a77a2f5283401db4fb23bab8403b1ea6ca644734ea33a6ad7af6',
  'extra_float_021': 'a0b47e8c223d359d41ad97daec6582d9c24836903ee965d0a8a23cd9e96221a5',
  'extra_float_022': '427f38149d34c669f73544c9f479483b67c83c84fca512f8d8b3281da04b11dd',
  'extra_float_023': 'e4acf50733b073bafece296bacc2372efd9ed1638b6dad8436a90fa1b278d71b',
  'extra_float_024': '98bb58a78690cce75c22ca01cbd528bf89f2c7eb54dfc46c2e85bad0673b8d7c',
  'extra_float_025': 'c2628adf118f7811dfd1a0ce48c87cdafc3cc20be0712c8289d5b1b8e9be28d0',
  'extra_float_026': '5441083e6c1c7841abc58c467d877e4b59387e936c0db0664614d900cff1d209',
  'extra_float_027': 'ae67fb6f61ada92e6a637f36bb633fdc6c890467abdaaa2ec4b588314f78b57b',
  'extra_float_028': '41501490497778ba90e4870b399438478f718f56ad7b585505d6330ec98c8cb9',
  'extra_float_029': 'ad38a8777d2f853678cce47e9abf48c30bc1f9b9ed0ff6d765000bfa0b9e656b',
  'extra_float_030': 'bcd6002fe0712ed1e89919442b60786b9501def85e9d2d2a69c7d1f2a6e35466',
  'extra_int_031': '1feea78dff8e12fce1bdb0d63cd3f97cbc544a684c11c6365acefac954ce4e1d',
  'extra_int_032': '9e52d6850db34b4a7db9b87c6503013606eb6e5ad36f8369567594be1f0de1f9',
  'extra_int_033': '83ba7337de983f9d41cbfcb9afa807fbf0f075a2114ba2d6c2cd50e3e01dbdb5',
  'extra_int_034': '16db288059c463a90d1107eedcef12de8a05defdf46b165dce699122a41119ef',
  'extra_int_035': '704467f0b07d9da4281d158214d8038602bdfbbe511a38193c2118b469f7b2ff',
  'extra_bool_036': '508e8bdff1f91643bd1a11172cc76cf346cebb52ca61b04f5ccea02d66e45b91',
  'extra_bool_037': '7a08bf80cb21a7ed74e3e7d7255b2296a6d0c38f7cf0dc2a2466c430328d9634',
  'extra_bool_038': '3d4cb2929c9b9a694693ae880a124999fdec788fbff625efa283259de61fb87b',
  'extra_string_039': '32a7a3e8f5ac4e83ab7a56bfb35be5bff5e1668876e65b89e7816c59b03e0993',
  'extra_datetime_040': '91bd3a5d3d3057827f056bd1907eca63f39d12c90d2ac8e6f9bc981689bcf543',
  'extra_float_041': '372d1099419602a54ef17e61288d38a94ff54f5e0aad6522870ef58ba8ff9c1f',
  'extra_float_042': '260f01c9c2c9ade617a93bfc8f153170be1d0055643a86039bd12a6ddf06ce8a',
  'extra_float_043': '4aac3f36c424f4b5f71cd0729d6e3f34b798bea965b5c5f17f531e1f54859340',
  'extra_float_044': 'c10c65b6925ca328ce460c32d7b85444d4141cfeb31fdde82219e4fd08853509',
  'extra_float_045': '6fbd2623cce75c8c6bdd02137df35595dbc7b601c19f7a9ef31d2877ced254a3',
  'extra_float_046': 'ed64f7a40fe269a612a6582b4be210ce64f5d1cbca7b0080f834bbd3fd90735a',
  'extra_float_047': '873763d5ddc42beca5132dee0ef8e58384b6c8786dcbfd17850df0b53a37488f',
  'extra_float_048': 'b3b09ebd31f13ec298f7b4b9fb1d71381fa2dcd262e2631e0937dc75e3fd1e2c',
  'extra_float_049': '7c0bc8d3c94b5222911c370d1c0ab75b39230d348a4747eba7e1b77d479f47a1',
  'extra_float_050': '24efed12c564ca5c6ddf2718e9cde8bbcad4d65a7c665a5a55a8872a60928f06',
  'extra_int_051': 'e25301ccace2aad9541f9f7835973500058085e03b417357ab41424d297f517a',
  'extra_int_052': '61f5bc011c3adff153f0c913a551798f84d31233f7cb01a96e4d25fcd2c9dccd',
  'extra_int_053': '3b64042a8685a97f28c9f0427313932c6a7bea26283d67f9669f66e45828357c',
  'extra_int_054': '78ffdcdd975ef3ad1532b1b7a70900ad3238b4f8b505ab4400917d852031efc3',
  'extra_int_055': '67fe12ce74dc9fa45dab2d135eab26a105487244ac782b2519a6b0b3713d0aa8',
  'extra_bool_056': '2e48da8e57931a797735d9313284eef0e4b0a3036c015e84597ada9d1983b6e9',
  'extra_bool_057': '3f0ec44cd95325e630c00debedf37a958ff8e832fdb92ba179aa057e2834ae65',
  'extra_bool_058': '9790991b9c299518aa188b3f25e932c8e221e0f1264790839269f4c5a2a9a62e',
  'extra_string_059': '2cb6a2911f495e4e094c7f2b819ccfbfcfbb89ff026d544f93542407e9838f14',
  'extra_datetime_060': '4caa841baac100d7452b30975ea720d1763f646602f7b3aa681f26d468912277',
  'extra_float_061': 'dd9dbc404b3f4b8430792eed1568f1eda0ed78510e302f3465686f65ed5f11b6',
  'extra_float_062': '9f1e0c4addc83cafcf2cd416090652a7d16af3e419e747e980e777435ee4a268',
  'extra_float_063': 'efd771bbe43fa4a85993b800095e2fa5d0b46d77bd95cb4165ae0db7a4b87bb4',
  'extra_float_064': '9f783f6e2e43b9f5678e3e0ed7ae2e8f5bc259a692f845daa26ca74370eb8ad1',
  'extra_float_065': '2c70d9df02821a7d2cd839c4142139a762c1c5303a811fd06caf6eab0ec7a53c',
  'extra_float_066': 'd95eddcc462fb66fe3043efad78242f20d286f252831f0f9873fc020329b1916',
  'extra_float_067': 'c341bf4dfd5b962163a70efaa4462ecd32713fa0e06f24bba3e2eecef9ec06b1',
  'extra_float_068': 'b0054783bedd4ac359637340dc534df6d2c89744cc60c9cdf3c504ab0c996fed',
  'extra_float_069': 'd05b6eba07b8c60900fa46aaabdb110b10be95ccf5fa824a056cb8fd6051c70b',
  'extra_float_070': '037a8591afd697c266ee9404fcafc948dd9f1fec1708929744da1f3ab23baaba',
  'extra_int_071': '43b23faa69adb53eb6cb764f104e04ed7b60833d7390e377ed7552f270494190',
  'extra_int_072': 'bbf11c8559f162c586d81ff98b97192038d03f4720b2c492695a10ba36620532',
  'extra_int_073': '6005b05db3f789907e419746d0a0a3e40a1c5f3cca94384d5bc9b3e1396c8fba',
  'extra_int_074': 'ce66e9155f6d0b4ce87709350af4f3ee5b49767b371ca13a952a3129ef29e24a',
  'extra_int_075': '4366f15dbc7deb9ffedc01fd53135e850e68c1044b856b1bdd71ba4bb6a1d985',
  'extra_bool_076': 'a4502743f3ad2d66290cd30c8dbe414d751644ab6d398eb55e4cf744f5999661',
  'extra_bool_077': '7a5c1678a318b7e0db4c219d6bd5331fbb68085df434ddd370378e74a0b77068',
  'extra_bool_078': 'ecb8eb8049ff96d45f539ed3b3975873f45beeba4585f238fbaf2ddf52b7bac2',
  'extra_string_079': 'f44b21dc888a27d78e7beebc60f901dc79bac04114236893a68ca7e3ee980684',
  'extra_datetime_080': '703a8c29373923ab1e7c562f9cb3fa37f9dcb5be30f6b6990812098201b171f9',
  'extra_float_081': 'a1d9217330effdb5f01c5abf323f264f185602ea34b5cb0ab1f3864e21c26d54',
  'extra_float_082': 'ff1fdbab61afde8add3e8319f2c53add66b575e1b8cf23514b708c4c0ad9cdef',
  'extra_float_083': '00a21213dd30b15bf3894f979961e4402b3fda6c61640f16cd0e9faafc32fe83',
  'extra_float_084': '0f18f0c3ea4489be44d0eab883db1689e7dd97f3df223c61b48f9e0ebef1d46a',
  'extra_float_085': 'e25d997b58d02a1d481d0ba1a15f45d02b73d472658f7208dd3e2f10c46b2f62',
  'extra_float_086': 'eba27adcb93b524fe42f2714aa8e7d4519e9363a8a27766fa2f68e197e25c7df',
  'extra_float_087': '420015bcb8fa4ef1c4f92007bd0d575ae35fae5714fcb25f44fb14e5d52f88de',
  'extra_float_088': '03f7c1315b0db1c83f5b77d13bdede3b3a4d9e35b9c7a7f5a311d1ec268dec04',
  'extra_float_089': 'e1e6b2ab2eced3ffcb65a6e1c4cc8d6d4609c1577d9ac455a93a22329cc6aeda',
  'extra_float_090': 'fb51f44e2ab77dafeb59dc0b21a05398eba8b89e446d0406b1d7a9af77f0e284',
  'extra_int_091': '2a0c8e082e30c3c57d16f9a01c5632a6431de10d73a2063d40b85393ae0e2260',
  'extra_int_092': 'd518527a7d24be7006fc3a80659e05b78cfbd3f2f3e090916b28d902dbe6a838',
  'extra_int_093': 'd8942ec8019312f365b31c772239a740514d75e1592c7acec598f6b035c97133',
  'extra_int_094': 'f7be232167472b1b8303f87e370d72700bb86df4935b31b579f4b75a3ab683b2',
  'extra_int_095': 'e74af36cef6c537fceac7a6e0e0f0fb7081de0a0d5b4e6d15e6b1ea345f2dbb1',
  'extra_bool_096': 'e7634a8ada409a39d6e5e3bd8adc675094db5e0f5a68b58e9ac61ad324ebf150',
  'extra_bool_097': 'c22b3e19ef6bf8154cb4833dd7cd4117402f301e4348b55cced00fd875e18327',
  'extra_bool_098': 'a9c11043b10e5e783cfacefa0570b3d93bc771f3fa0bd52ed1915962fe47ad97',
  'extra_string_099': '90fe511f8ab27408385b0f96acd8665539be69fc106027d049bc5ffcbd7e19ff',
  'extra_datetime_100': '25cc5103db4fc5827514271d617e2f3185b497610aaf607cc012991153d1902c',
  'extra_float_101': 'a62df82311c615ed7e73b11fcd5e94a81b08386dafce2dfde7fa16b57f6fdbef',
  'extra_float_102': 'aa028ed2239104733e996d80b962285b4172cf81e91b698bc71e15ccb79b61de',
  'extra_float_103': 'd064f7f4e2a75949186ffa0b0db914facf04353ff4bd70ad56c3906425117a23',
  'extra_float_104': '0fb508d124d320e3ca1bc681b87300c152c21884711f10b2fdfc424f240b833c',
  'extra_float_105': '65c4c9218a6a3ab1d0356daf89aaa952f42e6242179a00e68037659332c8fc02',
  'extra_float_106': '0484ee3761fb7933ecff7ee315483ef937cfb9144489d26d7403610286464d33',
  'extra_float_107': '3b64e064c8df86a9ac92413ac4598266b71b9ab92dedc24dc7a952be46b4cfdc',
  'extra_float_108': '637371693534b16d05954ba98e73db5f36edc0a2054635075f4ac75912e4d769',
  'extra_float_109': 'c10885ef12b3666499fb83e010eb19f618fadee615cedf4cc88c15ab243004ff',
  'extra_float_110': '0fb0809c20a4d40a2366a0b2feb440014b34d9273a54e25d89bd30f3c06b55be',
  'extra_int_111': '76d79f78209c5da3aaeb726a19fd8f16cd3718fecf0abec6931439590ac7de52',
  'extra_int_112': '9e200c026233be41b379b0bf1af9f634dc84fa263c2f81d88c9c6c35c8d498ad',
  'extra_int_113': 'cc5bb48c6f0ffa2b51e73f162d91499a96660ca00a83608d04542a9f93837fec',
  'extra_int_114': 'abe65161fe16f37e8303e2f6563872d81f2f5b4b32cf4f39e18aeb7c99c2204e',

  config_id  ... dataset_fingerprint_prefix
0        C1  ...               3f9af838fb90
1        C2  ...               62c82cac6a35
2        C3  ...               238689ae5886
3        C4  ...               178d9db5a094
4        C5  ...               fb3689520649
5        C6  ...               2f733085a0fe
6        C7  ...               16caee5ebfb3
7        C8  ...               ec28f3789f43
8        C9  ...               803537920bb2

[9 rows x 3 columns]

Ok: Test 3 superado: fingerprint construido, recomputable y persistible.

## Test 4 - Determinismo exacto sobre una configuración representativa

Objetivo:
- comprobar que, con la misma seed y la misma configuración,
  el generador produce exactamente el mismo DataFrame,
  el mismo `TripSchema`,
  el mismo `schema_effective`,
  el mismo `manifest`,
  y el mismo `expected_fingerprint`.

Nota:
- este test usa `C2` por ser suficientemente representativa sin ser tan pesada como `C8` o `C9`.
- si quieres, luego puedes repetir el mismo patrón con otra configuración.

In [6]:
config = get_predefined_config("C2")

case_a = generate_experiment_case(config, seed=DEFAULT_SEED)
case_b = generate_experiment_case(config, seed=DEFAULT_SEED)

# 1) DataFrame exactamente igual
assert_frame_equal(
    case_a.trips.data,
    case_b.trips.data,
    check_dtype=True,
    check_exact=True,
    check_categorical=True,
)

# 2) TripSchema exactamente igual vía snapshot serializable
assert case_a.schema.to_dict() == case_b.schema.to_dict(), "TripSchema distinto entre llamadas repetidas"

# 3) schema_effective exactamente igual
assert case_a.trips.schema_effective.to_dict() == case_b.trips.schema_effective.to_dict(), (
    "TripSchemaEffective distinto entre llamadas repetidas"
)

# 4) manifest exactamente igual
assert case_a.manifest == case_b.manifest, "Manifest distinto entre llamadas repetidas"

# 5) fingerprint exactamente igual
assert case_a.expected_fingerprint == case_b.expected_fingerprint, (
    "Fingerprint esperado distinto entre llamadas repetidas"
)

_cleanup_case(case_a)
_cleanup_case(case_b)

_print_ok("Test 4 superado: determinismo exacto confirmado en C2.")

Ok: Test 4 superado: determinismo exacto confirmado en C2.

## Test 5 - Determinismo mínimo sobre las 9 configuraciones

Objetivo:
- comprobar en las 9 configuraciones que, con la misma seed, al menos se conservan:
  - `manifest`,
  - `TripSchema`,
  - `dataset_fingerprint`.

Este test es más liviano que comparar DataFrames completos por pares en `C8` y `C9`.

In [7]:
rows = []

for config_id in CONFIG_IDS:
    config = get_predefined_config(config_id)

    case_a = generate_experiment_case(config, seed=DEFAULT_SEED)
    case_b = generate_experiment_case(config, seed=DEFAULT_SEED)

    assert case_a.manifest == case_b.manifest, f"{config_id}: manifest no determinista"
    assert case_a.schema.to_dict() == case_b.schema.to_dict(), f"{config_id}: schema no determinista"
    assert (
        case_a.expected_fingerprint["dataset_fingerprint"]
        == case_b.expected_fingerprint["dataset_fingerprint"]
    ), f"{config_id}: dataset_fingerprint no determinista"

    rows.append(
        {
            "config_id": config_id,
            "dataset_fingerprint_prefix": case_a.expected_fingerprint["dataset_fingerprint"][:12],
        }
    )

    _cleanup_case(case_a)
    _cleanup_case(case_b)

det_df = pd.DataFrame(rows)
display(det_df)
_print_ok("Test 5 superado: determinismo mínimo confirmado en las 9 configuraciones.")

  config_id dataset_fingerprint_prefix
0        C1               3f9af838fb90
1        C2               62c82cac6a35
2        C3               238689ae5886
3        C4               178d9db5a094
4        C5               fb3689520649
5        C6               2f733085a0fe
6        C7               16caee5ebfb3
7        C8               ec28f3789f43
8        C9               803537920bb2

Ok: Test 5 superado: determinismo mínimo confirmado en las 9 configuraciones.

## Test 6 - Validación explícita de que `get_predefined_config()` refleja exactamente las 9 configuraciones cerradas

Objetivo:
- comprobar que las 9 configuraciones del generador coinciden con las tuplas acordadas.

In [8]:
expected = {
    "C1": (36, 200_000, 10),
    "C2": (156, 200_000, 10),
    "C3": (256, 200_000, 10),
    "C4": (156, 20_000, 10),
    "C5": (156, 1_000_000, 10),
    "C6": (156, 200_000, 1_000),
    "C7": (156, 200_000, 10_000),
    "C8": (256, 1_000_000, 10),
    "C9": (156, 1_000_000, 10_000),
}

rows = []

for config_id, (exp_cols, exp_rows, exp_k) in expected.items():
    cfg = get_predefined_config(config_id)

    assert cfg.n_cols == exp_cols, f"{config_id}: n_cols incorrecto"
    assert cfg.n_rows == exp_rows, f"{config_id}: n_rows incorrecto"
    assert cfg.k == exp_k, f"{config_id}: k incorrecto"

    rows.append(
        {
            "config_id": config_id,
            "n_cols": cfg.n_cols,
            "n_rows": cfg.n_rows,
            "k": cfg.k,
        }
    )

expected_df = pd.DataFrame(rows)
display(expected_df)
_print_ok("Test 6 superado: las 9 configuraciones predefinidas coinciden con lo acordado.")

  config_id  n_cols   n_rows      k
0        C1      36   200000     10
1        C2     156   200000     10
2        C3     256   200000     10
3        C4     156    20000     10
4        C5     156  1000000     10
5        C6     156   200000   1000
6        C7     156   200000  10000
7        C8     256  1000000     10
8        C9     156  1000000  10000

Ok: Test 6 superado: las 9 configuraciones predefinidas coinciden con lo acordado.