# Ejemplos de uso de la funcion para generar datasets sinteticos

In [1]:
from pathlib import Path
import sys

REPO_ROOT = Path("../..").resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DATA_PATH = REPO_ROOT / "data" / "synthetic"

In [2]:
from scripts.synthetic_data.base_generator import generate_synthetic_trip_dataframe

### 1) Happy path mínimo canónico

Este es el caso más simple: dataset válido, Tier 1, coordenadas numéricas, H3 ya informado, sin campos base ni extras.

In [3]:
df = generate_synthetic_trip_dataframe(
    filas=5,
    seed=42,
)
print(df.head())
print(df.columns.tolist())
print(df.shape)

  movement_id user_id trip_id  movement_seq  origin_longitude  \
0      m00000   u0000  t00000             0        -70.661680
1      m00001   u0002  t00001             0        -70.745304
2      m00002   u0001  t00002             0        -70.572060
3      m00003   u0001  t00003             0        -70.582221
4      m00004   u0001  t00004             0        -70.653397

   origin_latitude  destination_longitude  destination_latitude  \
0       -33.374755             -70.626542            -33.340938
1       -33.606083             -70.747301            -33.592058
2       -33.554174             -70.579455            -33.579953
3       -33.439773             -70.609458            -33.428710
4       -33.475299             -70.604495            -33.504066

        origin_time_utc  destination_time_utc  origin_h3_index  \
0  2026-03-07T06:14:00Z  2026-03-07T07:46:00Z  88b2c55663fffff
1  2026-03-04T08:52:00Z  2026-03-04T09:19:00Z  88b2c545edfffff
2  2026-03-07T12:02:00Z  2026-03-07T12:48:00Z  88b2c509abfffff
3  2026-03-05T23:53:00Z  2026-03-06T00:51:00Z  88b2c50b45fffff
4  2026-03-06T16:46:00Z  2026-03-06T17:48:00Z  88b2c554abfffff

  destination_h3_index
0      88b2c5ccbdfffff
1      88b2c54515fffff
2      88b2c57343fffff
3      88b2c556b9fffff
4      88b2c5090dfffff
['movement_id', 'user_id', 'trip_id', 'movement_seq', 'origin_longitude', 'origin_latitude', 'destination_longitude', 'destination_latitude', 'origin_time_utc', 'destination_time_utc', 'origin_h3_index', 'destination_h3_index']
(5, 12)

In [4]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,u0000,t00000,0,-70.661680,-33.374755,-70.626542,-33.340938,2026-03-07T06:14:00Z,2026-03-07T07:46:00Z,88b2c55663fffff,88b2c5ccbdfffff
1,m00001,u0002,t00001,0,-70.745304,-33.606083,-70.747301,-33.592058,2026-03-04T08:52:00Z,2026-03-04T09:19:00Z,88b2c545edfffff,88b2c54515fffff
2,m00002,u0001,t00002,0,-70.572060,-33.554174,-70.579455,-33.579953,2026-03-07T12:02:00Z,2026-03-07T12:48:00Z,88b2c509abfffff,88b2c57343fffff
3,m00003,u0001,t00003,0,-70.582221,-33.439773,-70.609458,-33.428710,2026-03-05T23:53:00Z,2026-03-06T00:51:00Z,88b2c50b45fffff,88b2c556b9fffff
4,m00004,u0001,t00004,0,-70.653397,-33.475299,-70.604495,-33.504066,2026-03-06T16:46:00Z,2026-03-06T17:48:00Z,88b2c554abfffff,88b2c5090dfffff

### 2) Happy path con algunos campos base canónicos

Ahora agregamos un poco de semántica útil, pero todavía sin rarezas.

In [5]:
df = generate_synthetic_trip_dataframe(
    filas=8,
    seed=7,
    base_fields=["mode", "purpose", "trip_weight"],
)

print(df[["movement_id", "mode", "purpose", "trip_weight"]].head())

  movement_id          mode   purpose  trip_weight
0      m00000  ride_hailing  shopping        3.371
1      m00001         train  shopping        3.544
2      m00002           bus    health        1.179
3      m00003    motorcycle     other        2.481
4      m00004           bus  shopping        1.578

In [6]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight
0,m00000,u0003,t00000,0,-70.649459,-33.486374,-70.651399,-33.541626,2026-03-04T16:09:00Z,2026-03-04T18:04:00Z,88b2c554b5fffff,88b2c546edfffff,ride_hailing,shopping,3.371
1,m00001,u0002,t00001,0,-70.753047,-33.529332,-70.748514,-33.536384,2026-03-01T06:37:00Z,2026-03-01T08:23:00Z,88b2c54767fffff,88b2c54729fffff,train,shopping,3.544
2,m00002,u0002,t00002,0,-70.662925,-33.445189,-70.724131,-33.483212,2026-03-05T13:44:00Z,2026-03-05T14:10:00Z,88b2c55417fffff,88b2c555a9fffff,bus,health,1.179
3,m00003,u0003,t00003,0,-70.590470,-33.342783,-70.609580,-33.334645,2026-03-07T01:26:00Z,2026-03-07T02:29:00Z,88b2c5194dfffff,88b2c5cc9dfffff,motorcycle,other,2.481
4,m00004,u0002,t00004,0,-70.794421,-33.489377,-70.833562,-33.484674,2026-03-05T21:29:00Z,2026-03-05T23:22:00Z,88b2c542e7fffff,88b2c54041fffff,bus,shopping,1.578
5,m00005,u0003,t00005,0,-70.705762,-33.499638,-70.738115,-33.505246,2026-03-02T07:56:00Z,2026-03-02T09:38:00Z,88b2c555b1fffff,88b2c54293fffff,ride_hailing,health,2.311
6,m00006,u0003,t00006,0,-70.850122,-33.410813,-70.807686,-33.486315,2026-03-04T23:40:00Z,2026-03-05T01:06:00Z,88b2c55181fffff,88b2c54059fffff,bicycle,shopping,0.935
7,m00007,u0000,t00007,0,-70.788954,-33.421449,-70.821255,-33.437610,2026-03-03T02:57:00Z,2026-03-03T04:15:00Z,88b2c550b1fffff,88b2c5426bfffff,walk,health,4.855

### 3) Happy path con correspondencia de nombres

Este caso sirve para probar datasets fuente con nombres no canónicos, pero todavía válidos para import usando field_correspondence.

In [7]:
df = generate_synthetic_trip_dataframe(
    filas=6,
    seed=1,
    field_correspondence={
        "user_id": "viajero_id",
        "origin_latitude": "o_lat",
        "origin_longitude": "o_lon",
    },
)

print(df.head())
print(df.columns.tolist())

  movement_id viajero_id trip_id  movement_seq      o_lon      o_lat  \
0      m00000      u0001  t00000             0 -70.630587 -33.554253
1      m00001      u0001  t00001             0 -70.657158 -33.377572
2      m00002      u0002  t00002             0 -70.605329 -33.414290
3      m00003      u0002  t00003             0 -70.733645 -33.492956
4      m00004      u0000  t00004             0 -70.676291 -33.403511

   destination_longitude  destination_latitude       origin_time_utc  \
0             -70.641611            -33.536287  2026-03-07T17:23:00Z
1             -70.605395            -33.376380  2026-03-03T04:31:00Z
2             -70.565060            -33.423064  2026-03-06T07:56:00Z
3             -70.842092            -33.516414  2026-03-02T08:59:00Z
4             -70.751852            -33.411226  2026-03-03T12:11:00Z

   destination_time_utc  origin_h3_index destination_h3_index
0  2026-03-07T18:16:00Z  88b2c5468dfffff      88b2c54617fffff
1  2026-03-03T05:35:00Z  88b2c55605fffff      88b2c51921fffff
2  2026-03-06T08:34:00Z  88b2c55689fffff      88b2c519a3fffff
3  2026-03-02T09:17:00Z  88b2c555a5fffff      88b2c5403dfffff
4  2026-03-03T13:04:00Z  88b2c5544dfffff      88b2c5509bfffff
['movement_id', 'viajero_id', 'trip_id', 'movement_seq', 'o_lon', 'o_lat', 'destination_longitude', 'destination_latitude', 'origin_time_utc', 'destination_time_utc', 'origin_h3_index', 'destination_h3_index']

In [8]:
display(df)

,movement_id,viajero_id,trip_id,movement_seq,o_lon,o_lat,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,u0001,t00000,0,-70.630587,-33.554253,-70.641611,-33.536287,2026-03-07T17:23:00Z,2026-03-07T18:16:00Z,88b2c5468dfffff,88b2c54617fffff
1,m00001,u0001,t00001,0,-70.657158,-33.377572,-70.605395,-33.376380,2026-03-03T04:31:00Z,2026-03-03T05:35:00Z,88b2c55605fffff,88b2c51921fffff
2,m00002,u0002,t00002,0,-70.605329,-33.414290,-70.565060,-33.423064,2026-03-06T07:56:00Z,2026-03-06T08:34:00Z,88b2c55689fffff,88b2c519a3fffff
3,m00003,u0002,t00003,0,-70.733645,-33.492956,-70.842092,-33.516414,2026-03-02T08:59:00Z,2026-03-02T09:17:00Z,88b2c555a5fffff,88b2c5403dfffff
4,m00004,u0000,t00004,0,-70.676291,-33.403511,-70.751852,-33.411226,2026-03-03T12:11:00Z,2026-03-03T13:04:00Z,88b2c5544dfffff,88b2c5509bfffff
5,m00005,u0000,t00005,0,-70.708212,-33.420834,-70.715203,-33.420590,2026-03-08T00:56:00Z,2026-03-08T02:12:00Z,88b2c55465fffff,88b2c55559fffff

### 4) Happy path Tier 2 con HH:MM válidos

Aquí hacemos un caso limpio, pero usando temporalidad Tier 2.

In [9]:
df = generate_synthetic_trip_dataframe(
    filas=8,
    seed=3,
    tier_temporal="tier_2",
    tier2_hhmm_format="valid_hhmm",
    base_fields=[
        "origin_time_local_hhmm",
        "destination_time_local_hhmm",
        "mode",
    ],
)

print(df[
    [
        "movement_id",
        "origin_time_local_hhmm",
        "destination_time_local_hhmm",
        "mode",
    ]
].head())

  movement_id origin_time_local_hhmm destination_time_local_hhmm   mode
0      m00000                  15:52                       17:33    bus
1      m00001                  10:36                       11:56    car
2      m00002                  07:08                       07:13  train
3      m00003                  07:19                       08:42   taxi
4      m00004                  19:50                       20:20    car

In [10]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode
0,m00000,u0003,t00000,0,-70.688129,-33.486212,-70.697871,-33.485484,15:52,17:33,88b2c5559dfffff,88b2c55583fffff,bus
1,m00001,u0000,t00001,0,-70.726805,-33.467248,-70.686712,-33.420873,10:36,11:56,88b2c555edfffff,88b2c5546bfffff,car
2,m00002,u0000,t00002,0,-70.765515,-33.611599,-70.800973,-33.595246,07:08,07:13,88b2c54eddfffff,88b2c54e19fffff,train
3,m00003,u0000,t00003,0,-70.699080,-33.468555,-70.710749,-33.483711,07:19,08:42,88b2c55589fffff,88b2c55585fffff,taxi
4,m00004,u0000,t00004,0,-70.611805,-33.519217,-70.576504,-33.524702,19:50,20:20,88b2c5092bfffff,88b2c50917fffff,car
5,m00005,u0003,t00005,0,-70.683855,-33.184160,-70.660641,-33.167944,18:44,20:23,88b2c5c1c5fffff,88b2c5c035fffff,bicycle
6,m00006,u0003,t00006,0,-70.564224,-33.431937,-70.560563,-33.373884,23:09,00:59,88b2c50b49fffff,88b2c51919fffff,scooter
7,m00007,u0002,t00007,0,-70.679980,-33.478210,-70.653176,-33.486299,01:25,02:19,88b2c555d7fffff,88b2c554a3fffff,bus

### 5) Happy path con H3 derivable

Este es importante porque se parece mucho a un caso de integración real: el dataset no trae H3, pero sí trae coordenadas válidas y el import podría derivarlos.

Para este caso hay que combinar correctamente los argumentos. No basta con poner h3_mode="omitted_derivable": además hay que omitir explícitamente las columnas H3.

In [11]:
df = generate_synthetic_trip_dataframe(
    filas=10,
    seed=4,
    omit_required_fields=["origin_h3_index", "destination_h3_index"],
    h3_mode="omitted_derivable",
)

print(df.head())
print(df.columns.tolist())

  movement_id user_id trip_id  movement_seq  origin_longitude  \
0      m00000   u0003  t00000             0        -70.434727
1      m00001   u0004  t00001             0        -70.851565
2      m00002   u0004  t00002             0        -70.549820
3      m00003   u0002  t00003             0        -70.692990
4      m00004   u0004  t00004             0        -70.748065

   origin_latitude  destination_longitude  destination_latitude  \
0       -33.450416             -70.394453            -33.505304
1       -33.499877             -70.813197            -33.499970
2       -33.438109             -70.589014            -33.464871
3       -33.578655             -70.724902            -33.555379
4       -33.430658             -70.756198            -33.494200

        origin_time_utc  destination_time_utc
0  2026-03-06T21:08:00Z  2026-03-06T21:47:00Z
1  2026-03-07T23:42:00Z  2026-03-08T01:32:00Z
2  2026-03-02T03:28:00Z  2026-03-02T04:10:00Z
3  2026-03-07T10:32:00Z  2026-03-07T11:38:00Z
4  2026-03-01T11:49:00Z  2026-03-01T12:02:00Z
['movement_id', 'user_id', 'trip_id', 'movement_seq', 'origin_longitude', 'origin_latitude', 'destination_longitude', 'destination_latitude', 'origin_time_utc', 'destination_time_utc']

In [12]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc
0,m00000,u0003,t00000,0,-70.434727,-33.450416,-70.394453,-33.505304,2026-03-06T21:08:00Z,2026-03-06T21:47:00Z
1,m00001,u0004,t00001,0,-70.851565,-33.499877,-70.813197,-33.499970,2026-03-07T23:42:00Z,2026-03-08T01:32:00Z
2,m00002,u0004,t00002,0,-70.549820,-33.438109,-70.589014,-33.464871,2026-03-02T03:28:00Z,2026-03-02T04:10:00Z
3,m00003,u0002,t00003,0,-70.692990,-33.578655,-70.724902,-33.555379,2026-03-07T10:32:00Z,2026-03-07T11:38:00Z
4,m00004,u0004,t00004,0,-70.748065,-33.430658,-70.756198,-33.494200,2026-03-01T11:49:00Z,2026-03-01T12:02:00Z
5,m00005,u0004,t00005,0,-70.725629,-33.431170,-70.695710,-33.441480,2026-03-03T22:13:00Z,2026-03-03T23:52:00Z
6,m00006,u0004,t00006,0,-70.727201,-33.323950,-70.693163,-33.317645,2026-03-04T23:23:00Z,2026-03-05T01:18:00Z
7,m00007,u0000,t00007,0,-70.621981,-33.424668,-70.650368,-33.469196,2026-03-06T10:13:00Z,2026-03-06T10:49:00Z
8,m00008,u0002,t00008,0,-70.671006,-33.409156,-70.695294,-33.379600,2026-03-02T10:42:00Z,2026-03-02T12:24:00Z
9,m00009,u0003,t00009,0,-70.511743,-33.569449,-70.543656,-33.564088,2026-03-01T13:03:00Z,2026-03-01T13:51:00Z

### 6) Happy path multistage

Ahora subimos complejidad estructural: varios movements pueden compartir trip_id.

In [13]:
df = generate_synthetic_trip_dataframe(
    filas=12,
    seed=11,
    trip_structure="multistage",
    max_movements_per_trip=3,
    base_fields=["mode", "purpose", "trip_weight"],
)

print(df[["trip_id", "movement_seq", "movement_id", "mode", "purpose"]].head(12))
print(df["trip_id"].value_counts().head())

     trip_id  movement_seq movement_id        mode    purpose
0   tm_00000             0      m00000         bus    leisure
1   tm_00001             0      m00001        walk  education
2   tm_00002             0      m00002  motorcycle      other
3   tm_00002             1      m00003  motorcycle    leisure
4   tm_00002             2      m00004       other   transfer
5   tm_00003             0      m00005         bus       home
6   tm_00003             1      m00006         bus       home
7   tm_00004             0      m00007        taxi       home
8   tm_00004             1      m00008  motorcycle     errand
9   tm_00005             0      m00009       train   shopping
10  tm_00005             1      m00010       other      other
11  tm_00006             0      m00011     scooter  education
trip_id
tm_00002    3
tm_00003    2
tm_00004    2
tm_00005    2
tm_00000    1
Name: count, dtype: Int64

In [14]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight
0,m00000,u0000,tm_00000,0,-70.591430,-33.454485,-70.642813,-33.461479,2026-03-01T18:17:00Z,2026-03-01T18:24:00Z,88b2c50b67fffff,88b2c5548dfffff,bus,leisure,4.304
1,m00001,u0001,tm_00001,0,-70.747034,-33.390249,-70.773499,-33.412557,2026-03-05T08:45:00Z,2026-03-05T10:26:00Z,88b2c550dbfffff,88b2c55095fffff,walk,education,3.838
2,m00002,u0000,tm_00002,0,-70.811438,-33.597786,-70.844965,-33.586236,2026-03-01T09:23:00Z,2026-03-01T09:28:00Z,88b2c54e15fffff,88b2c54e67fffff,motorcycle,other,2.956
3,m00003,u0000,tm_00002,1,-70.620502,-33.324676,-70.689862,-33.303159,2026-03-03T09:51:00Z,2026-03-03T10:49:00Z,88b2c5cc89fffff,88b2c5cc27fffff,motorcycle,leisure,3.477
4,m00004,u0000,tm_00002,2,-70.727057,-33.457715,-70.721999,-33.466715,2026-03-07T18:42:00Z,2026-03-07T19:36:00Z,88b2c55517fffff,88b2c555e1fffff,other,transfer,3.615
5,m00005,u0001,tm_00003,0,-70.852034,-33.395570,-70.830922,-33.379230,2026-03-03T11:19:00Z,2026-03-03T11:38:00Z,88b2c551c5fffff,88b2c5503dfffff,bus,home,4.015
6,m00006,u0001,tm_00003,1,-70.741405,-33.460925,-70.770957,-33.429639,2026-03-03T09:55:00Z,2026-03-03T11:14:00Z,88b2c55531fffff,88b2c55565fffff,bus,home,4.674
7,m00007,u0003,tm_00004,0,-70.706760,-33.480328,-70.651334,-33.486537,2026-03-01T20:59:00Z,2026-03-01T22:29:00Z,88b2c55581fffff,88b2c554a3fffff,taxi,home,1.174
8,m00008,u0003,tm_00004,1,-70.779320,-33.412951,-70.746443,-33.437357,2026-03-06T16:08:00Z,2026-03-06T18:06:00Z,88b2c550b9fffff,88b2c5550dfffff,motorcycle,errand,3.318
9,m00009,u0002,tm_00005,0,-70.809246,-33.384039,-70.784151,-33.373609,2026-03-02T11:00:00Z,2026-03-02T11:27:00Z,88b2c550edfffff,88b2c550cdfffff,train,shopping,1.146
10,m00010,u0002,tm_00005,1,-70.656336,-33.466202,-70.640268,-33.458776,2026-03-04T17:49:00Z,2026-03-04T19:40:00Z,88b2c554e7fffff,88b2c554c7fffff,other,other,2.494
11,m00011,u0000,tm_00006,0,-70.570275,-33.462223,-70.532048,-33.429259,2026-03-01T10:07:00Z,2026-03-01T10:19:00Z,88b2c50b07fffff,88b2c50a6dfffff,scooter,education,4.038

### 7) Dominios extendidos controlados

Aquí probamos un dataset aún válido, pero ya más interesante: usamos un campo categórico con mezcla de valores canónicos y extendidos.

In [15]:
df = generate_synthetic_trip_dataframe(
    filas=10,
    seed=5,
    base_fields=["purpose", "user_gender", "day_type"],
    extra_value_domains={
        "purpose": ["canon", "finos"]
    },
    categorical_sampling_policy={
        "purpose": {"extended_ratio": 0.4}
    },
)

print(df[["purpose", "user_gender", "day_type"]].head(10))
print(df["purpose"].value_counts())

               purpose user_gender day_type
0               errand      female  weekday
1           Recreación       other  holiday
2               health     unknown  holiday
3          Por estudio       other  holiday
4    Visitar a alguien     unknown  weekend
5               health        male  holiday
6              leisure        male  weekend
7  Buscar o dejar algo     unknown  holiday
8               errand      female  weekday
9    Visitar a alguien      female  weekday
purpose
errand                 2
health                 2
Visitar a alguien      2
Recreación             1
Por estudio            1
leisure                1
Buscar o dejar algo    1
Name: count, dtype: Int64

In [16]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,purpose,user_gender,day_type
0,m00000,u0003,t00000,0,-70.833213,-33.441223,-70.849061,-33.416328,2026-03-04T21:17:00Z,2026-03-04T23:02:00Z,88b2c54261fffff,88b2c55187fffff,errand,female,weekday
1,m00001,u0004,t00001,0,-70.668370,-33.494212,-70.712023,-33.543502,2026-03-04T19:11:00Z,2026-03-04T19:25:00Z,88b2c5464dfffff,88b2c54717fffff,Recreación,other,holiday
2,m00002,u0000,t00002,0,-70.776323,-33.512782,-70.830531,-33.520484,2026-03-03T06:48:00Z,2026-03-03T08:29:00Z,88b2c542b5fffff,88b2c5403bfffff,health,unknown,holiday
3,m00003,u0004,t00003,0,-70.722929,-33.390100,-70.713937,-33.419523,2026-03-04T19:04:00Z,2026-03-04T20:46:00Z,88b2c55705fffff,88b2c55559fffff,Por estudio,other,holiday
4,m00004,u0002,t00004,0,-70.708801,-33.319217,-70.753175,-33.324412,2026-03-08T00:31:00Z,2026-03-08T01:28:00Z,88b2c5cd17fffff,88b2c552c9fffff,Visitar a alguien,unknown,weekend
5,m00005,u0002,t00005,0,-70.731331,-33.428178,-70.684519,-33.466861,2026-03-02T21:40:00Z,2026-03-02T22:27:00Z,88b2c55543fffff,88b2c555ddfffff,health,male,holiday
6,m00006,u0003,t00006,0,-70.604662,-33.548666,-70.575999,-33.548046,2026-03-06T15:02:00Z,2026-03-06T16:59:00Z,88b2c546d1fffff,88b2c509a9fffff,leisure,male,weekend
7,m00007,u0001,t00007,0,-70.666309,-33.526661,-70.746221,-33.527798,2026-03-01T08:26:00Z,2026-03-01T10:20:00Z,88b2c54607fffff,88b2c54763fffff,Buscar o dejar algo,unknown,holiday
8,m00008,u0004,t00008,0,-70.718943,-33.321998,-70.708058,-33.331129,2026-03-03T10:43:00Z,2026-03-03T12:05:00Z,88b2c5cd3bfffff,88b2c5cde1fffff,errand,female,weekday
9,m00009,u0000,t00009,0,-70.619036,-33.433769,-70.663105,-33.465207,2026-03-07T18:46:00Z,2026-03-07T19:36:00Z,88b2c556bdfffff,88b2c554e7fffff,Visitar a alguien,female,weekday

### 8) Dataset mas "rico": base + extras + nulos controlados

Este ya se parece mas a un caso de integración natural

In [17]:
df = generate_synthetic_trip_dataframe(
    filas=15,
    seed=9,
    base_fields=["mode", "purpose", "trip_weight", "user_gender"],
    extra_columns=["household_id", "activity_destination", "travel_time_min"],
    null_ratio={
        "trip_weight": 0.2,
        "activity_destination": 0.3,
    },
)

print(df.head())
print(df.isna().mean().sort_values(ascending=False).head(10))

  movement_id user_id trip_id  movement_seq  origin_longitude  \
0      m00000   u0003  t00000             0        -70.425677
1      m00001   u0006  t00001             0        -70.669403
2      m00002   u0007  t00002             0        -70.698511
3      m00003   u0002  t00003             0        -70.578915
4      m00004   u0000  t00004             0        -70.749137

   origin_latitude  destination_longitude  destination_latitude  \
0       -33.481548             -70.463993            -33.478809
1       -33.518992             -70.701679            -33.529608
2       -33.612604             -70.712543            -33.611760
3       -33.337166             -70.539981            -33.305591
4       -33.453811             -70.788256            -33.459305

        origin_time_utc  destination_time_utc  origin_h3_index  \
0  2026-03-07T16:15:00Z  2026-03-07T18:09:00Z  88b2c501adfffff
1  2026-03-01T21:50:00Z  2026-03-01T23:00:00Z  88b2c54605fffff
2  2026-03-03T21:22:00Z  2026-03-03T21:35:00Z  88b2c545d7fffff
3  2026-03-07T11:55:00Z  2026-03-07T13:31:00Z  88b2c51949fffff
4  2026-03-01T15:11:00Z  2026-03-01T16:19:00Z  88b2c5553dfffff

  destination_h3_index        mode   purpose  trip_weight user_gender  \
0      88b2c50a89fffff       metro   leisure        3.720       other
1      88b2c54719fffff       train    health        4.974      female
2      88b2c54589fffff  motorcycle    errand        3.870     unknown
3      88b2c51b5dfffff  motorcycle    health        2.707      female
4      88b2c54211fffff       other  transfer        4.897       other

  household_id activity_destination  travel_time_min
0       H00001                salud            114.0
1       H00006                 <NA>             70.0
2       H00002                 <NA>             13.0
3       H00002              trabajo             96.0
4       H00003                salud             68.0
activity_destination    0.266667
trip_weight             0.200000
movement_id             0.000000
origin_h3_index         0.000000
household_id            0.000000
user_gender             0.000000
purpose                 0.000000
mode                    0.000000
destination_h3_index    0.000000
destination_time_utc    0.000000
dtype: float64

In [18]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight,user_gender,household_id,activity_destination,travel_time_min
0,m00000,u0003,t00000,0,-70.425677,-33.481548,-70.463993,-33.478809,2026-03-07T16:15:00Z,2026-03-07T18:09:00Z,88b2c501adfffff,88b2c50a89fffff,metro,leisure,3.720,other,H00001,salud,114.0
1,m00001,u0006,t00001,0,-70.669403,-33.518992,-70.701679,-33.529608,2026-03-01T21:50:00Z,2026-03-01T23:00:00Z,88b2c54605fffff,88b2c54719fffff,train,health,4.974,female,H00006,<NA>,70.0
2,m00002,u0007,t00002,0,-70.698511,-33.612604,-70.712543,-33.611760,2026-03-03T21:22:00Z,2026-03-03T21:35:00Z,88b2c545d7fffff,88b2c54589fffff,motorcycle,errand,3.870,unknown,H00002,<NA>,13.0
3,m00003,u0002,t00003,0,-70.578915,-33.337166,-70.539981,-33.305591,2026-03-07T11:55:00Z,2026-03-07T13:31:00Z,88b2c51949fffff,88b2c51b5dfffff,motorcycle,health,2.707,female,H00002,trabajo,96.0
4,m00004,u0000,t00004,0,-70.749137,-33.453811,-70.788256,-33.459305,2026-03-01T15:11:00Z,2026-03-01T16:19:00Z,88b2c5553dfffff,88b2c54211fffff,other,transfer,4.897,other,H00003,salud,68.0
5,m00005,u0004,t00005,0,-70.583239,-33.248214,-70.586892,-33.271075,2026-03-02T01:06:00Z,2026-03-02T02:22:00Z,88b2c5c535fffff,88b2c5ced5fffff,metro,errand,NaN,other,H00002,compra,76.0
6,m00006,u0005,t00006,0,-70.777124,-33.383903,-70.801646,-33.413000,2026-03-02T03:08:00Z,2026-03-02T03:18:00Z,88b2c550c3fffff,88b2c550a1fffff,walk,home,4.787,other,H00007,estudio,10.0
7,m00007,u0006,t00007,0,-70.605476,-33.427778,-70.592491,-33.434429,2026-03-03T01:59:00Z,2026-03-03T03:02:00Z,88b2c556b9fffff,88b2c55697fffff,train,shopping,2.754,female,H00003,salud,63.0
8,m00008,u0005,t00008,0,-70.764413,-33.502594,-70.748527,-33.525087,2026-03-07T13:58:00Z,2026-03-07T15:45:00Z,88b2c542b9fffff,88b2c54763fffff,motorcycle,health,2.675,unknown,H00003,<NA>,107.0
9,m00009,u0005,t00009,0,-70.843707,-33.338602,-70.902317,-33.282183,2026-03-03T11:03:00Z,2026-03-03T12:12:00Z,88b2c55317fffff,88b2c42681fffff,taxi,shopping,4.321,male,H00002,<NA>,69.0
10,m00010,u0007,t00010,0,-70.719377,-33.490503,-70.623902,-33.525860,2026-03-05T11:13:00Z,2026-03-05T12:05:00Z,88b2c555abfffff,88b2c50927fffff,metro,home,3.240,other,H00001,estudio,52.0
11,m00011,u0007,t00011,0,-70.806391,-33.324404,-70.798807,-33.356852,2026-03-01T08:09:00Z,2026-03-01T09:19:00Z,88b2c5523dfffff,88b2c55057fffff,bicycle,errand,NaN,female,H00007,recreación,70.0
12,m00012,u0007,t00012,0,-70.604672,-33.481869,-70.625045,-33.491046,2026-03-06T18:52:00Z,2026-03-06T19:01:00Z,88b2c5094dfffff,88b2c5096dfffff,bus,home,2.160,unknown,H00003,salud,9.0
13,m00013,u0006,t00013,0,-70.657833,-33.435124,-70.693593,-33.415623,2026-03-05T03:48:00Z,2026-03-05T04:32:00Z,88b2c5541dfffff,88b2c55469fffff,metro,health,2.991,other,H00005,estudio,44.0
14,m00014,u0005,t00014,0,-70.609055,-33.571814,-70.619436,-33.579857,2026-03-05T11:45:00Z,2026-03-05T13:28:00Z,88b2c54697fffff,88b2c546b3fffff,bus,health,NaN,female,H00002,compra,103.0

### 9) Primer caso “problemático”: Tier 2 con HH:MM mixtos

Este ya no es un happy path puro, pero sí es muy útil para revisión de integridad del generador y luego para tests de import no fatal.

In [19]:
df = generate_synthetic_trip_dataframe(
    filas=12,
    seed=13,
    tier_temporal="tier_2",
    tier2_hhmm_format="mixed_hhmm",
    base_fields=[
        "origin_time_local_hhmm",
        "destination_time_local_hhmm",
        "mode",
    ],
)

print(df[["origin_time_local_hhmm", "destination_time_local_hhmm"]].head(12))

   origin_time_local_hhmm destination_time_local_hhmm
0                     3:5                        7:63
1                   15:09                       15:32
2                   09:40                       11:19
3                   17:59                       18:40
4                   03:49                       04:30
5                   14:35                       15:56
6                   17:49                        7:63
7                   10:45                       99:99
8                   ab:cd                       01:34
9                   13:27                       14:25
10                  09:30                       10:35
11                    3:5                       19:35

In [20]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode
0,m00000,u0005,t00000,0,-70.492079,-33.303819,-70.521472,-33.271873,3:5,7:63,88b2c51a01fffff,88b2c5c583fffff,train
1,m00001,u0005,t00001,0,-70.682429,-33.447460,-70.652698,-33.440752,15:09,15:32,88b2c55431fffff,88b2c55411fffff,metro
2,m00002,u0004,t00002,0,-70.526272,-33.491298,-70.516834,-33.502312,09:40,11:19,88b2c50809fffff,88b2c5081dfffff,other
3,m00003,u0005,t00003,0,-70.618253,-33.403561,-70.599779,-33.427728,17:59,18:40,88b2c556c5fffff,88b2c55695fffff,metro
4,m00004,u0000,t00004,0,-70.465604,-33.415431,-70.454707,-33.425715,03:49,04:30,88b2c518bbfffff,88b2c50161fffff,other
5,m00005,u0004,t00005,0,-70.506289,-33.478547,-70.533406,-33.447013,14:35,15:56,88b2c50859fffff,88b2c50a2dfffff,metro
6,m00006,u0005,t00006,0,-70.628170,-33.469784,-70.606751,-33.443059,17:49,7:63,88b2c5548bfffff,88b2c556b3fffff,bicycle
7,m00007,u0001,t00007,0,-70.511924,-33.392445,-70.455425,-33.400309,10:45,99:99,88b2c519dbfffff,88b2c51899fffff,taxi
8,m00008,u0001,t00008,0,-70.755012,-33.393655,-70.756483,-33.431035,ab:cd,01:34,88b2c550d3fffff,88b2c5556bfffff,car
9,m00009,u0000,t00009,0,-70.534138,-33.489515,-70.508794,-33.469295,13:27,14:25,88b2c5080dfffff,88b2c50a31fffff,bus
10,m00010,u0004,t00010,0,-70.808042,-33.479417,-70.813078,-33.522913,09:30,10:35,88b2c54233fffff,88b2c540e9fffff,taxi
11,m00011,u0005,t00011,0,-70.625676,-33.594543,-70.584534,-33.610469,3:5,19:35,88b2c544d1fffff,88b2c57339fffff,train

### 10) Caso inválido: movement_id duplicado

Este ya entra en el terreno de abortos estructurales esperables para import.

In [21]:
df = generate_synthetic_trip_dataframe(
    filas=10,
    seed=21,
    duplicate_mode="movement_id_only",
)

print(df[["movement_id", "trip_id", "movement_seq"]].head(10))
print("movement_id únicos:", df["movement_id"].nunique())
print("filas totales:", len(df))

  movement_id trip_id  movement_seq
0      m00000  t00000             0
1      m00001  t00001             0
2      m00002  t00002             0
3      m00009  t00003             0
4      m00004  t00004             0
5      m00005  t00005             0
6      m00002  t00006             0
7      m00007  t00007             0
8      m00008  t00008             0
9      m00009  t00009             0
movement_id únicos: 8
filas totales: 10

In [22]:
display(df)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,u0001,t00000,0,-70.563111,-33.513998,-70.569612,-33.487222,2026-03-07T23:39:00Z,2026-03-07T23:46:00Z,88b2c5091bfffff,88b2c50959fffff
1,m00001,u0003,t00001,0,-70.441679,-33.514237,-70.425904,-33.510502,2026-03-04T01:28:00Z,2026-03-04T02:47:00Z,88b2c50f61fffff,88b2c50f47fffff
2,m00002,u0001,t00002,0,-70.539018,-33.536625,-70.566032,-33.489083,2026-03-02T01:53:00Z,2026-03-02T03:09:00Z,88b2c509d1fffff,88b2c50959fffff
3,m00009,u0003,t00003,0,-70.762439,-33.467892,-70.752905,-33.491126,2026-03-06T23:24:00Z,2026-03-07T01:20:00Z,88b2c542cbfffff,88b2c5429dfffff
4,m00004,u0002,t00004,0,-70.531473,-33.383289,-70.555678,-33.369156,2026-03-07T11:30:00Z,2026-03-07T12:43:00Z,88b2c519cbfffff,88b2c51919fffff
5,m00005,u0003,t00005,0,-70.597161,-33.403275,-70.589609,-33.388310,2026-03-03T02:12:00Z,2026-03-03T03:38:00Z,88b2c556ddfffff,88b2c51931fffff
6,m00002,u0001,t00006,0,-70.638518,-33.398937,-70.599074,-33.424867,2026-03-05T07:55:00Z,2026-03-05T08:53:00Z,88b2c5563bfffff,88b2c5569dfffff
7,m00007,u0000,t00007,0,-70.741987,-33.585585,-70.755573,-33.621023,2026-03-05T16:21:00Z,2026-03-05T16:34:00Z,88b2c5451dfffff,88b2c54ed1fffff
8,m00008,u0001,t00008,0,-70.659722,-33.575677,-70.625731,-33.545270,2026-03-02T03:42:00Z,2026-03-02T04:25:00Z,88b2c5441bfffff,88b2c546c7fffff
9,m00009,u0003,t00009,0,-70.674700,-33.325696,-70.716068,-33.310173,2026-03-01T08:01:00Z,2026-03-01T09:14:00Z,88b2c5cdddfffff,88b2c5cd15fffff

### 11) Ejemplo de choque de configuración útil de conocer

Este ejemplo debería fallar, y eso está bien, porque detecta una configuración contradictoria:

In [23]:
try:
    df = generate_synthetic_trip_dataframe(
        filas=8,
        seed=6,
        omit_required_fields=["origin_h3_index", "destination_h3_index"],
        h3_mode="provided_valid",
    )
except ValueError as e:
    print(e)

h3_mode='provided_valid' requiere mantener columnas H3; no es compatible con omitirlas.

In [24]:
df = generate_synthetic_trip_dataframe(
    filas=8,
    seed=6,
    omit_required_fields=["origin_h3_index", "destination_h3_index"],
    h3_mode="omitted_derivable",
)

### 12) Ejemplo más complejo para parecerse más a una fuente real

Hacemos una configuración compleja pero todavía plausible/natural, pensada para parecerse más a una fuente real “rica”, no completamente limpia, pero tampoco destruida.

In [25]:

df = generate_synthetic_trip_dataframe(
    filas=120,
    seed=20260322,

    # Estructura general
    duplicate_mode="none",
    trip_structure="multistage",
    max_movements_per_trip=3,

    # Temporalidad y espacialidad
    tier_temporal="tier_1",
    tier1_datetime_format="offset_string",
    coord_format="dms",
    h3_mode="provided_valid",

    # Campos base/opcionales Golondrina
    base_fields=[
        "mode",
        "purpose",
        "day_type",
        "time_period",
        "user_gender",
        "user_age_group",
        "income_quintile",
        "trip_weight",
        "origin_municipality",
        "destination_municipality",
    ],

    # Dominios extendidos
    extra_value_domains={
        "mode": ["canon", "submodes"],
        "purpose": ["canon", "finos"],
        "time_period": ["canon", "eod_finos"],
        "user_gender": ["canon", "es"],
        "income_quintile": ["canon", "tramos"],
    },

    # Cómo se muestrean esos dominios
    categorical_sampling_policy={
        "mode": {"canonical_ratio": 0.75, "ensure_presence": True},
        "purpose": {"canonical_ratio": 0.70, "ensure_presence": True},
        "time_period": {"canonical_ratio": 0.80},
        "user_gender": {"canonical_ratio": 0.90},
        "income_quintile": {"canonical_ratio": 0.85},
    },

    # Extras
    extra_columns=[
        "household_id",
        "source_person_id",
        "stage_count",
        "activity_destination",
        "travel_time_min",
        "fare_amount",
        "public_transport_route_code",
        "origin_venue_category",
        "destination_venue_category",
        "household_income_clp",
        "education_level",
        "activity_status",
        "driver_license_class",
    ],

    # Nulos realistas en algunas columnas
    null_ratio={
        "trip_weight": 0.08,
        "activity_destination": 0.12,
        "fare_amount": 0.10,
        "destination_venue_category": 0.18,
        "household_income_clp": 0.15,
        "education_level": 0.06,
    },

    # Patrones acoplados de incompletitud
    paired_missingness={
        "destination_incomplete": 0.05,
    },

    # Algo de contaminación categórica
    noise_ratio={
        "purpose": 0.04,
        "mode": 0.03,
        "user_gender": 0.02,
    },

    # Algunas columnas con tipo semánticamente "malo"
    type_corruption={
        "trip_weight": {"mode": "numeric_as_string", "ratio": 0.08},
        "household_income_clp": {"mode": "numeric_as_string", "ratio": 0.12},
        "fare_amount": {"mode": "stringified", "ratio": 0.10},
    },
)

Guardamos el dataset para una mejor inspeccion

In [26]:
df.to_csv(DATA_PATH / "test_dataset.csv", sep=",", index=False)

Visualizacion de la tabla transpuesta para verla mejor

In [27]:
display(df.head(10).T)

,0,1,2,3,4,5,6,7,8,9
movement_id,m00000,m00001,m00002,m00003,m00004,m00005,m00006,m00007,m00008,m00009
user_id,u0016,u0016,u0029,u0029,u0007,u0007,u0026,u0026,u0026,u0012
trip_id,tm_00000,tm_00000,tm_00001,tm_00001,tm_00002,tm_00002,tm_00003,tm_00003,tm_00003,tm_00004
movement_seq,0,1,0,1,0,1,0,1,2,0
origin_longitude,70° 15 20.84 W,70° 28 28.98 W,70° 55 0.00 W,70° 28 0.54 W,70° 29 11.31 W,70° 43 45.57 W,70° 32 1.41 W,70° 35 13.82 W,70° 31 34.44 W,70° 40 34.52 W
origin_latitude,33° 35 56.37 S,33° 26 48.29 S,33° 19 46.57 S,33° 13 54.83 S,33° 32 28.13 S,33° 27 0.37 S,33° 33 5.98 S,33° 25 18.61 S,33° 21 14.40 S,33° 32 4.73 S
destination_longitude,70° 15 42.25 W,70° 28 12.65 W,70° 55 53.91 W,70° 29 45.40 W,70° 30 47.07 W,70° 45 6.78 W,70° 32 34.78 W,70° 29 52.37 W,70° 31 58.48 W,70° 41 46.06 W
destination_latitude,33° 35 27.13 S,33° 28 0.78 S,33° 19 15.14 S,33° 9 41.55 S,33° 30 37.90 S,33° 26 5.05 S,33° 35 14.47 S,33° 24 6.59 S,33° 21 17.10 S,33° 31 3.83 S
origin_time_utc,2026-03-05T16:57:00-03:00,2026-03-06T18:51:00-03:00,2026-03-03T19:00:00-03:00,2026-03-04T20:36:00-03:00,2026-03-07T06:22:00-03:00,2026-03-06T20:31:00-03:00,2026-03-03T12:53:00-03:00,2026-03-03T08:43:00-03:00,2026-03-05T11:59:00-03:00,2026-03-05T21:23:00-03:00
destination_time_utc,2026-03-05T18:51:00-03:00,2026-03-06T20:01:00-03:00,2026-03-03T20:49:00-03:00,2026-03-04T21:53:00-03:00,2026-03-07T06:55:00-03:00,2026-03-06T22:03:00-03:00,2026-03-03T13:01:00-03:00,2026-03-03T10:01:00-03:00,2026-03-05T13:48:00-03:00,2026-03-05T22:56:00-03:00
origin_h3_index,88b2c53b11fffff,88b2c50125fffff,88b2c4248bfffff,88b2c5c4cdfffff,88b2c50883fffff,88b2c55515fffff,88b2c50999fffff,88b2c55699fffff,88b2c5180dfffff,88b2c54623fffff
destination_h3_index,88b2c53b57fffff,88b2c50ac5fffff,88b2c424c7fffff,88b2c5c663fffff,88b2c50817fffff,88b2c5550dfffff,88b2c5722dfffff,88b2c518a9fffff,88b2c51863fffff,88b2c5475bfffff
mode,Bus troncal,Auto Chofer,Furgón escolar chofer,taxi,ride_hailing,ZP,Furgón escolar pasajero,motorcycle,Bus alimentador,Bus interurbano o rural
purpose,shopping,work,education,De compras,home,Visitar a alguien,Buscar o dejar algo,Comer o Tomar algo,Por estudio,Buscar o Dejar a alguien
day_type,holiday,holiday,holiday,weekday,weekend,weekday,holiday,weekday,weekday,weekend
time_period,evening,midday,Punta Tarde,morning,midday,Punta Mañana 1,Punta Mañana 1,Punta Tarde,Punta Mañana 1,Punta Mañana 2
user_gender,other,Hombre,other,female,female,male,female,other,other,other
user_age_group,65-plus,55-64,65-plus,45-54,25-34,35-44,55-64,15-24,0-14,45-54
income_quintile,Entre 800.001 y 1.600.000 pesos,Menos de 200.000 pesos,Menos de 200.000 pesos,5,Menos de 200.000 pesos,3,Entre 1.600.001 y 2.400.000 pesos,5,5,3
trip_weight,4.742,0.906,NaN,0.649,1.315,4.781,0.883,0.873,3.993,3.146
origin_municipality,Recoleta,Vitacura,Maipú,Recoleta,Santiago,Vitacura,Santiago,Maipú,La Florida,Providencia
destination_municipality,Recoleta,San Miguel,Quilicura,Santiago,Quilicura,Maipú,Maipú,Las Condes,Quilicura,La Florida
household_id,H00045,H00015,H00044,H00046,H00046,H00031,H00055,H00020,H00029,H00039
source_person_id,P00045,P00009,P00008,P00044,P00059,P00058,P00039,P00018,P00004,P00027
stage_count,1,1,1,3,3,1,1,1,3,4
activity_destination,trabajo,compra,recreación,salud,estudio,salud,recreación,compra,compra,recreación
travel_time_min,114.0,70.0,109.0,77.0,33.0,92.0,8.0,78.0,109.0,93.0
fare_amount,900.0,900.0,900.0,800.0,1520.0,1520.0,0.0,800.0,nan,900.0
public_transport_route_code,401,401,210,B07,401,I09c,401,B07,L1,210
origin_venue_category,Coffee Shop,Mall,University,Bank,Coffee Shop,Gym,Coffee Shop,Home,Bank,Gym
destination_venue_category,<NA>,University,Gym,Hospital,Mall,Bank,Hospital,Hospital,Gym,Coffee Shop
household_income_clp,2478173.0,266454.0,1427137.0,972580.0,1372176.0,2211447.0,2338665.0,754091.0,NaN,1576149.0
education_level,secondary,postgraduate,postgraduate,none,primary,postgraduate,university,primary,primary,primary
activity_status,retired,studying,working,unemployed,retired,unemployed,homemaker,unemployed,working,homemaker
driver_license_class,A3,none,B,A2,none,B,none,A3,professional_other,A2

Visualizacion por bloques de tabla wide

In [28]:
n_cols_por_bloque = 10

for i in range(0, df.shape[1], n_cols_por_bloque):
    bloque = df.iloc[:10, i:i + n_cols_por_bloque]
    print(f"\nBloque {i // n_cols_por_bloque + 1}")
    display(bloque)

Bloque 1

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc
0,m00000,u0016,tm_00000,0,70° 15 20.84 W,33° 35 56.37 S,70° 15 42.25 W,33° 35 27.13 S,2026-03-05T16:57:00-03:00,2026-03-05T18:51:00-03:00
1,m00001,u0016,tm_00000,1,70° 28 28.98 W,33° 26 48.29 S,70° 28 12.65 W,33° 28 0.78 S,2026-03-06T18:51:00-03:00,2026-03-06T20:01:00-03:00
2,m00002,u0029,tm_00001,0,70° 55 0.00 W,33° 19 46.57 S,70° 55 53.91 W,33° 19 15.14 S,2026-03-03T19:00:00-03:00,2026-03-03T20:49:00-03:00
3,m00003,u0029,tm_00001,1,70° 28 0.54 W,33° 13 54.83 S,70° 29 45.40 W,33° 9 41.55 S,2026-03-04T20:36:00-03:00,2026-03-04T21:53:00-03:00
4,m00004,u0007,tm_00002,0,70° 29 11.31 W,33° 32 28.13 S,70° 30 47.07 W,33° 30 37.90 S,2026-03-07T06:22:00-03:00,2026-03-07T06:55:00-03:00
5,m00005,u0007,tm_00002,1,70° 43 45.57 W,33° 27 0.37 S,70° 45 6.78 W,33° 26 5.05 S,2026-03-06T20:31:00-03:00,2026-03-06T22:03:00-03:00
6,m00006,u0026,tm_00003,0,70° 32 1.41 W,33° 33 5.98 S,70° 32 34.78 W,33° 35 14.47 S,2026-03-03T12:53:00-03:00,2026-03-03T13:01:00-03:00
7,m00007,u0026,tm_00003,1,70° 35 13.82 W,33° 25 18.61 S,70° 29 52.37 W,33° 24 6.59 S,2026-03-03T08:43:00-03:00,2026-03-03T10:01:00-03:00
8,m00008,u0026,tm_00003,2,70° 31 34.44 W,33° 21 14.40 S,70° 31 58.48 W,33° 21 17.10 S,2026-03-05T11:59:00-03:00,2026-03-05T13:48:00-03:00
9,m00009,u0012,tm_00004,0,70° 40 34.52 W,33° 32 4.73 S,70° 41 46.06 W,33° 31 3.83 S,2026-03-05T21:23:00-03:00,2026-03-05T22:56:00-03:00

Bloque 2

,origin_h3_index,destination_h3_index,mode,purpose,day_type,time_period,user_gender,user_age_group,income_quintile,trip_weight
0,88b2c53b11fffff,88b2c53b57fffff,Bus troncal,shopping,holiday,evening,other,65-plus,Entre 800.001 y 1.600.000 pesos,4.742
1,88b2c50125fffff,88b2c50ac5fffff,Auto Chofer,work,holiday,midday,Hombre,55-64,Menos de 200.000 pesos,0.906
2,88b2c4248bfffff,88b2c424c7fffff,Furgón escolar chofer,education,holiday,Punta Tarde,other,65-plus,Menos de 200.000 pesos,NaN
3,88b2c5c4cdfffff,88b2c5c663fffff,taxi,De compras,weekday,morning,female,45-54,5,0.649
4,88b2c50883fffff,88b2c50817fffff,ride_hailing,home,weekend,midday,female,25-34,Menos de 200.000 pesos,1.315
5,88b2c55515fffff,88b2c5550dfffff,ZP,Visitar a alguien,weekday,Punta Mañana 1,male,35-44,3,4.781
6,88b2c50999fffff,88b2c5722dfffff,Furgón escolar pasajero,Buscar o dejar algo,holiday,Punta Mañana 1,female,55-64,Entre 1.600.001 y 2.400.000 pesos,0.883
7,88b2c55699fffff,88b2c518a9fffff,motorcycle,Comer o Tomar algo,weekday,Punta Tarde,other,15-24,5,0.873
8,88b2c5180dfffff,88b2c51863fffff,Bus alimentador,Por estudio,weekday,Punta Mañana 1,other,0-14,5,3.993
9,88b2c54623fffff,88b2c5475bfffff,Bus interurbano o rural,Buscar o Dejar a alguien,weekend,Punta Mañana 2,other,45-54,3,3.146

Bloque 3

,origin_municipality,destination_municipality,household_id,source_person_id,stage_count,activity_destination,travel_time_min,fare_amount,public_transport_route_code,origin_venue_category
0,Recoleta,Recoleta,H00045,P00045,1,trabajo,114.0,900.0,401,Coffee Shop
1,Vitacura,San Miguel,H00015,P00009,1,compra,70.0,900.0,401,Mall
2,Maipú,Quilicura,H00044,P00008,1,recreación,109.0,900.0,210,University
3,Recoleta,Santiago,H00046,P00044,3,salud,77.0,800.0,B07,Bank
4,Santiago,Quilicura,H00046,P00059,3,estudio,33.0,1520.0,401,Coffee Shop
5,Vitacura,Maipú,H00031,P00058,1,salud,92.0,1520.0,I09c,Gym
6,Santiago,Maipú,H00055,P00039,1,recreación,8.0,0.0,401,Coffee Shop
7,Maipú,Las Condes,H00020,P00018,1,compra,78.0,800.0,B07,Home
8,La Florida,Quilicura,H00029,P00004,3,compra,109.0,nan,L1,Bank
9,Providencia,La Florida,H00039,P00027,4,recreación,93.0,900.0,210,Gym

Bloque 4

,destination_venue_category,household_income_clp,education_level,activity_status,driver_license_class
0,<NA>,2478173.0,secondary,retired,A3
1,University,266454.0,postgraduate,studying,none
2,Gym,1427137.0,postgraduate,working,B
3,Hospital,972580.0,none,unemployed,A2
4,Mall,1372176.0,primary,retired,none
5,Bank,2211447.0,postgraduate,unemployed,B
6,Hospital,2338665.0,university,homemaker,none
7,Hospital,754091.0,primary,unemployed,A3
8,Gym,NaN,primary,working,professional_other
9,Coffee Shop,1576149.0,primary,homemaker,A2