# Ejemplos de uso de los wrappers para generar datasets sinteticos

In [1]:
from pathlib import Path
import sys

REPO_ROOT = Path("../..").resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DATA_PATH = REPO_ROOT / "data" / "synthetic"

In [2]:
from scripts.synthetic_data.gen_wrappers import (
    make_happy_path_minimal,
    make_happy_path_rich,
    make_h3_derivable,
    make_tier2_valid,
    make_tier2_mixed_invalid,
    make_multistage_valid,
    make_extended_domains,
    make_missing_required,
    make_duplicate_movement_id,
)

### 1) Happy path mínimo

In [3]:
df = make_happy_path_minimal(filas=6, seed=42)
df.head()

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,u0000,t00000,0,-70.745304,-33.374755,-70.772542,-33.400534,2026-03-04T17:37:00Z,2026-03-04T19:28:00Z,88b2c5576dfffff,88b2c5508bfffff
1,m00001,u0002,t00001,0,-70.572060,-33.606083,-70.523159,-33.595020,2026-03-01T13:21:00Z,2026-03-01T14:51:00Z,88b2c57315fffff,88b2c57207fffff
2,m00002,u0001,t00002,0,-70.582221,-33.554174,-70.588402,-33.582941,2026-03-05T01:49:00Z,2026-03-05T02:36:00Z,88b2c509a1fffff,88b2c57347fffff
3,m00003,u0001,t00003,0,-70.653397,-33.439773,-70.670530,-33.413419,2026-03-02T07:55:00Z,2026-03-02T09:51:00Z,88b2c55411fffff,88b2c55443fffff
4,m00004,u0001,t00004,0,-70.547276,-33.475299,-70.561361,-33.476797,2026-03-06T10:53:00Z,2026-03-06T11:45:00Z,88b2c50b13fffff,88b2c50b3bfffff

Con override: agregamos dos campos base para que no sea tan “vacío”

In [23]:
df = make_happy_path_minimal(
    filas=8,
    seed=42,
    base_fields=["mode", "purpose"],
)

display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose
0,m00000,u0000,t00000,0,-70.653397,-33.606083,-70.636888,-33.611629,2026-03-04T11:46:00Z,2026-03-04T13:39:00Z,88b2c54481fffff,88b2c5449dfffff,scooter,health
1,m00001,u0003,t00001,0,-70.547276,-33.554174,-70.530043,-33.574602,2026-03-02T03:49:00Z,2026-03-02T04:44:00Z,88b2c50995fffff,88b2c5726bfffff,bus,errand
2,m00002,u0002,t00002,0,-70.613249,-33.439773,-70.527583,-33.403097,2026-03-06T01:19:00Z,2026-03-06T01:42:00Z,88b2c556b1fffff,88b2c519d7fffff,bus,errand
3,m00003,u0001,t00003,0,-70.745929,-33.475299,-70.762186,-33.479935,2026-03-04T13:55:00Z,2026-03-04T15:35:00Z,88b2c542d9fffff,88b2c542c3fffff,bicycle,health
4,m00004,u0001,t00004,0,-70.623125,-33.451344,-70.643615,-33.464194,2026-03-03T13:28:00Z,2026-03-03T14:45:00Z,88b2c554ddfffff,88b2c5548dfffff,train,home

### 2) Happy path rico

In [4]:
df = make_happy_path_rich(filas=12, seed=42)
df.head()

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,...,user_gender,trip_weight,origin_municipality,destination_municipality,household_id,source_person_id,stage_count,activity_destination,travel_time_min,fare_amount
0,m00000,u0000,t00000,0,-70.572155,-33.439773,-70.598775,-33.375523,2026-03-05T03:20:00-03:00,2026-03-05T05:03:00-03:00,...,other,0.965,Ñuñoa,Estación Central,H00003,P00004,1,salud,103.0,1200.0
1,m00001,u0004,t00001,0,-70.664993,-33.475299,-70.655706,-33.487492,2026-03-04T11:05:00-03:00,2026-03-04T12:15:00-03:00,...,female,3.144,La Florida,Maipú,H00000,P00004,3,estudio,70.0,1200.0
2,m00002,u0003,t00002,0,-70.678486,-33.451344,-70.673819,-33.466711,2026-03-04T18:56:00-03:00,2026-03-04T19:10:00-03:00,...,unknown,1.268,Independencia,San Miguel,H00001,P00005,3,salud,14.0,800.0
3,m00003,u0002,t00003,0,-70.728093,-33.518244,-70.719345,-33.542657,2026-03-05T05:32:00-03:00,2026-03-05T07:04:00-03:00,...,male,4.663,La Florida,San Miguel,H00003,P00004,2,compra,92.0,760.0
4,m00004,u0002,t00004,0,-70.537746,-33.379648,-70.502889,-33.361169,2026-03-01T12:15:00-03:00,2026-03-01T13:26:00-03:00,...,unknown,3.115,La Florida,Quilicura,H00001,P00001,2,recreación,71.0,0.0

Con un pequeño override:

In [5]:
df = make_happy_path_rich(
    filas=12,
    seed=42,
    extra_columns=["household_id", "travel_time_min", "fare_amount"],
)
display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,...,purpose,day_type,time_period,user_gender,trip_weight,origin_municipality,destination_municipality,household_id,travel_time_min,fare_amount
0,m00000,u0000,t00000,0,-70.572155,-33.439773,-70.598775,-33.375523,2026-03-05T03:20:00-03:00,2026-03-05T05:03:00-03:00,...,leisure,weekend,night,other,0.965,Ñuñoa,Estación Central,H00003,103.0,900.0
1,m00001,u0004,t00001,0,-70.664993,-33.475299,-70.655706,-33.487492,2026-03-04T11:05:00-03:00,2026-03-04T12:15:00-03:00,...,leisure,weekday,midday,female,3.144,La Florida,Maipú,H00000,70.0,760.0
2,m00002,u0003,t00002,0,-70.678486,-33.451344,-70.673819,-33.466711,2026-03-04T18:56:00-03:00,2026-03-04T19:10:00-03:00,...,leisure,weekend,afternoon,unknown,1.268,Independencia,San Miguel,H00001,14.0,900.0
3,m00003,u0002,t00003,0,-70.728093,-33.518244,-70.719345,-33.542657,2026-03-05T05:32:00-03:00,2026-03-05T07:04:00-03:00,...,errand,holiday,morning,male,4.663,La Florida,San Miguel,H00003,92.0,900.0
4,m00004,u0002,t00004,0,-70.537746,-33.379648,-70.502889,-33.361169,2026-03-01T12:15:00-03:00,2026-03-01T13:26:00-03:00,...,leisure,weekend,afternoon,unknown,3.115,La Florida,Quilicura,H00001,71.0,1520.0

Con override: Elegimos extras concretos. Sirviendo para un un caso feliz con foco en salida observable / trazabilidad "rica"

In [24]:
df = make_happy_path_rich(
    filas=12,
    seed=42,
    extra_columns=[
        "household_id",
        "source_person_id",
        "activity_destination",
        "travel_time_min",
        "fare_amount",
    ],
    base_fields=[
        "mode",
        "purpose",
        "trip_weight",
        "user_gender",
        "origin_municipality",
        "destination_municipality",
    ],
)

display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,...,purpose,trip_weight,user_gender,origin_municipality,destination_municipality,household_id,source_person_id,activity_destination,travel_time_min,fare_amount
0,m00000,u0000,t00000,0,-70.572155,-33.439773,-70.598775,-33.375523,2026-03-05T03:20:00-03:00,2026-03-05T05:03:00-03:00,...,leisure,2.508,female,Santiago,Recoleta,H00004,P00003,estudio,103.0,1200.0
1,m00001,u0004,t00001,0,-70.664993,-33.475299,-70.655706,-33.487492,2026-03-04T11:05:00-03:00,2026-03-04T12:15:00-03:00,...,leisure,2.215,male,Pudahuel,Providencia,H00000,P00003,compra,70.0,1200.0
2,m00002,u0003,t00002,0,-70.678486,-33.451344,-70.673819,-33.466711,2026-03-04T18:56:00-03:00,2026-03-04T19:10:00-03:00,...,leisure,1.857,other,La Florida,Pudahuel,H00001,P00001,salud,14.0,1520.0
3,m00003,u0002,t00003,0,-70.728093,-33.518244,-70.719345,-33.542657,2026-03-05T05:32:00-03:00,2026-03-05T07:04:00-03:00,...,errand,3.336,female,Pudahuel,Puente Alto,H00003,P00000,compra,92.0,1200.0
4,m00004,u0002,t00004,0,-70.537746,-33.379648,-70.502889,-33.361169,2026-03-01T12:15:00-03:00,2026-03-01T13:26:00-03:00,...,leisure,2.128,other,Independencia,Quilicura,H00004,P00000,compra,71.0,760.0

### 3) H3 derivable

In [8]:
df = make_h3_derivable(filas=8, seed=42)

assert "origin_h3_index" not in df.columns
assert "destination_h3_index" not in df.columns

print(df.columns.tolist())
display(df.head())

['movement_id', 'user_id', 'trip_id', 'movement_seq', 'origin_longitude', 'origin_latitude', 'destination_longitude', 'destination_latitude', 'origin_time_utc', 'destination_time_utc', 'mode', 'purpose']

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,mode,purpose
0,m00000,u0000,t00000,0,-70.653397,-33.606083,-70.636888,-33.611629,2026-03-04T11:46:00Z,2026-03-04T13:39:00Z,scooter,health
1,m00001,u0003,t00001,0,-70.547276,-33.554174,-70.530043,-33.574602,2026-03-02T03:49:00Z,2026-03-02T04:44:00Z,bus,errand
2,m00002,u0002,t00002,0,-70.613249,-33.439773,-70.527583,-33.403097,2026-03-06T01:19:00Z,2026-03-06T01:42:00Z,bus,errand
3,m00003,u0001,t00003,0,-70.745929,-33.475299,-70.762186,-33.479935,2026-03-04T13:55:00Z,2026-03-04T15:35:00Z,bicycle,health
4,m00004,u0001,t00004,0,-70.623125,-33.451344,-70.643615,-33.464194,2026-03-03T13:28:00Z,2026-03-03T14:45:00Z,train,home

Con override util: Cambiar el formato espacial, para no depender solo del default.

In [25]:
df = make_h3_derivable(
    filas=10,
    seed=42,
    coord_format="dd_string",
    base_fields=["mode", "purpose"],
)

display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,mode,purpose
0,m00000,u0000,t00000,0,-70.745929,-33.554174,-70.700770,-33.564738,2026-03-07T12:52:00Z,2026-03-07T14:28:00Z,train,other
1,m00001,u0003,t00001,0,-70.623125,-33.439773,-70.627683,-33.423803,2026-03-03T06:26:00Z,2026-03-03T08:01:00Z,ride_hailing,transfer
2,m00002,u0003,t00002,0,-70.755888,-33.475299,-70.789495,-33.464336,2026-03-02T22:14:00Z,2026-03-02T23:48:00Z,walk,home
3,m00003,u0002,t00003,0,-70.572155,-33.451344,-70.605134,-33.438962,2026-03-06T00:39:00Z,2026-03-06T02:00:00Z,metro,education
4,m00004,u0002,t00004,0,-70.664993,-33.518244,-70.638969,-33.505319,2026-03-05T16:58:00Z,2026-03-05T17:57:00Z,ride_hailing,transfer

### 4) Tier 2 válido

In [10]:
df = make_tier2_valid(filas=8, seed=42)

display(df.head())
df[["origin_time_local_hhmm", "destination_time_local_hhmm"]].head()

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode,purpose
0,m00000,u0000,t00000,0,-70.653397,-33.606083,-70.636888,-33.611629,11:46,13:39,88b2c54481fffff,88b2c5449dfffff,scooter,health
1,m00001,u0003,t00001,0,-70.547276,-33.554174,-70.530043,-33.574602,03:49,04:44,88b2c50995fffff,88b2c5726bfffff,bus,errand
2,m00002,u0002,t00002,0,-70.613249,-33.439773,-70.527583,-33.403097,01:19,01:42,88b2c556b1fffff,88b2c519d7fffff,bus,errand
3,m00003,u0001,t00003,0,-70.745929,-33.475299,-70.762186,-33.479935,13:55,15:35,88b2c542d9fffff,88b2c542c3fffff,bicycle,health
4,m00004,u0001,t00004,0,-70.623125,-33.451344,-70.643615,-33.464194,13:28,14:45,88b2c554ddfffff,88b2c5548dfffff,train,home

  origin_time_local_hhmm destination_time_local_hhmm
0                  11:46                       13:39
1                  03:49                       04:44
2                  01:19                       01:42
3                  13:55                       15:35
4                  13:28                       14:45

Con override util: añadir segmentación temporal/categórica adicional.

In [26]:
df = make_tier2_valid(
    filas=10,
    seed=42,
    base_fields=[
        "origin_time_local_hhmm",
        "destination_time_local_hhmm",
        "mode",
        "day_type",
        "time_period",
    ],
)

display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode,day_type,time_period
0,m00000,u0000,t00000,0,-70.745929,-33.554174,-70.700770,-33.564738,12:52,14:28,88b2c54549fffff,88b2c54463fffff,train,holiday,midday
1,m00001,u0003,t00001,0,-70.623125,-33.439773,-70.627683,-33.423803,06:26,08:01,88b2c556b5fffff,88b2c556a9fffff,ride_hailing,holiday,evening
2,m00002,u0003,t00002,0,-70.755888,-33.475299,-70.789495,-33.464336,22:14,23:48,88b2c542ddfffff,88b2c54211fffff,walk,weekday,morning
3,m00003,u0002,t00003,0,-70.572155,-33.451344,-70.605134,-33.438962,00:39,02:00,88b2c50b0dfffff,88b2c556bbfffff,metro,weekday,night
4,m00004,u0002,t00004,0,-70.664993,-33.518244,-70.638969,-33.505319,16:58,17:57,88b2c54601fffff,88b2c54651fffff,ride_hailing,holiday,morning

### 5) Tier 2 mixto con inválidos

In [11]:
df = make_tier2_mixed_invalid(filas=10, seed=42)

display(df.head())
df[["origin_time_local_hhmm", "destination_time_local_hhmm"]].head(10)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode,purpose
0,m00000,u0000,t00000,0,-70.745929,-33.554174,-70.700770,-33.564738,12:52,14:28,88b2c54549fffff,88b2c54463fffff,metro,shopping
1,m00001,u0003,t00001,0,-70.623125,-33.439773,-70.627683,-33.423803,06:26,-1:10,88b2c556b5fffff,88b2c556a9fffff,motorcycle,health
2,m00002,u0003,t00002,0,-70.755888,-33.475299,-70.789495,-33.464336,22:14,23:48,88b2c542ddfffff,88b2c54211fffff,ride_hailing,work
3,m00003,u0002,t00003,0,-70.572155,-33.451344,-70.605134,-33.438962,00:39,02:00,88b2c50b0dfffff,88b2c556bbfffff,walk,health
4,m00004,u0002,t00004,0,-70.664993,-33.518244,-70.638969,-33.505319,24:03,99:99,88b2c54601fffff,88b2c54651fffff,motorcycle,errand

  origin_time_local_hhmm destination_time_local_hhmm
0                  12:52                       14:28
1                  06:26                       -1:10
2                  22:14                       23:48
3                  00:39                       02:00
4                  24:03                       99:99
5                  24:03                       06:54
6                  01:53                       02:29
7                  15:35                       17:09
8                  21:13                       22:21
9                  07:14                       08:11

Versión más agresiva:

In [12]:
df = make_tier2_mixed_invalid(
    filas=10,
    seed=42,
    mostly_invalid=True,
)
df[["origin_time_local_hhmm", "destination_time_local_hhmm"]].head(10)

  origin_time_local_hhmm destination_time_local_hhmm
0                    3:5                       24:03
1                  ab:cd                         3:5
2                  -1:10                       24:00
3                  00:39                         3:5
4                  ab:cd                       17:57
5                  05:28                        7:63
6                  ab:cd                       02:29
7                  15:35                       17:09
8                  24:00                       25:61
9                  ab:cd                        7:63

Con override: Util para meter un poco de nulidad y tener HH:MM validos e invalidos

In [28]:
df = make_tier2_mixed_invalid(
    filas=14,
    seed=42,
    null_ratio={
        "origin_time_local_hhmm": 0.20,
        "destination_time_local_hhmm": 0.30,
    },
    base_fields=["mode", "purpose"],
)

display(df.head(14))

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_local_hhmm,destination_time_local_hhmm,origin_h3_index,destination_h3_index,mode,purpose
0,m00000,u0000,t00000,0,-70.728093,-33.475299,-70.725390,-33.441430,04:58,-1:10,88b2c555e7fffff,88b2c5551dfffff,other,leisure
1,m00001,u0005,t00001,0,-70.537746,-33.451344,-70.526181,-33.454763,03:00,,88b2c50b53fffff,88b2c50a21fffff,walk,work
2,m00002,u0004,t00002,0,-70.675453,-33.518244,-70.650201,-33.543448,21:12,21:20,88b2c54605fffff,88b2c546edfffff,motorcycle,leisure
3,m00003,u0003,t00003,0,-70.702833,-33.379648,-70.761119,-33.404383,03:56,04:27,88b2c55755fffff,88b2c55099fffff,bicycle,education
4,m00004,u0003,t00004,0,-70.695213,-33.387777,-70.708000,-33.368259,<NA>,21:11,88b2c55757fffff,88b2c5574bfffff,motorcycle,transfer
5,m00005,u0006,t00005,0,-70.606769,-33.444718,-70.625584,-33.422420,<NA>,09:14,88b2c556b3fffff,88b2c556a9fffff,other,health
6,m00006,u0000,t00006,0,-70.623456,-33.359821,-70.649011,-33.343526,11:16,,88b2c55659fffff,88b2c5cca7fffff,car,errand
7,m00007,u0004,t00007,0,-70.618727,-33.412599,-70.629732,-33.432565,<NA>,,88b2c5568dfffff,88b2c556a3fffff,train,work
8,m00008,u0001,t00008,0,-70.616918,-33.518743,-70.557120,-33.511779,16:22,18:12,88b2c50921fffff,88b2c50827fffff,taxi,errand
9,m00009,u0000,t00009,0,-70.445835,-33.420500,-70.480468,-33.416999,7:63,08:00,88b2c50145fffff,88b2c518b1fffff,bus,transfer
10,m00010,u0003,t00010,0,-70.700642,-33.526711,-70.661910,-33.520150,03:06,,88b2c54753fffff,88b2c54601fffff,taxi,home
11,m00011,u0006,t00011,0,-70.711224,-33.379724,-70.778539,-33.353581,18:03,19:24,88b2c55709fffff,88b2c552a9fffff,scooter,leisure
12,m00012,u0005,t00012,0,-70.741377,-33.453994,-70.754773,-33.447286,24:03,ab:cd,88b2c55539fffff,88b2c5552bfffff,metro,errand
13,m00013,u0005,t00013,0,-70.598402,-33.464789,-70.591892,-33.444422,7:63,03:46,88b2c50b2dfffff,88b2c50b61fffff,other,leisure

### 6) Multistage válido

In [13]:
df = make_multistage_valid(
    filas=15,
    seed=42,
    max_movements_per_trip=3,
)

display(df.head())
df[["trip_id", "movement_seq", "movement_id"]].head(15)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight,mode_sequence,stage_count,travel_time_min
0,m00000,u0000,tm_00000,0,-70.675453,-33.451344,-70.688240,-33.476079,2026-03-08T03:06:00-03:00,2026-03-08T04:27:00-03:00,88b2c55431fffff,88b2c555d7fffff,car,education,4.355,bus+bus+train,3,81.0
1,m00001,u0000,tm_00001,0,-70.702833,-33.518244,-70.721648,-33.498726,2026-03-02T18:03:00-03:00,2026-03-02T18:22:00-03:00,88b2c54751fffff,88b2c555a3fffff,bicycle,home,3.913,car+metro+metro,3,19.0
2,m00002,u0000,tm_00001,1,-70.695213,-33.379648,-70.720768,-33.357351,2026-03-03T04:27:00-03:00,2026-03-03T05:36:00-03:00,88b2c55751fffff,88b2c5cda7fffff,car,home,3.738,car+bus,1,69.0
3,m00003,u0000,tm_00001,2,-70.606769,-33.387777,-70.617775,-33.371482,2026-03-04T02:37:00-03:00,2026-03-04T03:40:00-03:00,88b2c51927fffff,88b2c55653fffff,scooter,errand,2.444,walk,2,63.0
4,m00004,u0002,tm_00002,0,-70.623456,-33.444718,-70.563658,-33.464683,2026-03-08T04:46:00-03:00,2026-03-08T06:21:00-03:00,88b2c554cbfffff,88b2c50b03fffff,motorcycle,other,3.323,metro+metro+metro,1,95.0

     trip_id  movement_seq movement_id
0   tm_00000             0      m00000
1   tm_00001             0      m00001
2   tm_00001             1      m00002
3   tm_00001             2      m00003
4   tm_00002             0      m00004
5   tm_00002             1      m00005
6   tm_00003             0      m00006
7   tm_00003             1      m00007
8   tm_00004             0      m00008
9   tm_00004             1      m00009
10  tm_00005             0      m00010
11  tm_00005             1      m00011
12  tm_00005             2      m00012
13  tm_00006             0      m00013
14  tm_00007             0      m00014

Con override: útil para representar viajes con varias filas por trip_id, y dialoga bien con la idea de movement vs trip del formato. Tambien es util para enriquecerlo con extras por etapa/viaje.

In [29]:
df = make_multistage_valid(
    filas=18,
    seed=42,
    max_movements_per_trip=4,
    extra_columns=["stage_count", "travel_time_min", "public_transport_route_code"],
    base_fields=["mode", "purpose", "trip_weight"],
)

df.head(18)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight,stage_count,travel_time_min,public_transport_route_code
0,m00000,u0000,tm_00000,0,-70.606769,-33.451344,-70.600259,-33.447844,2026-03-04T04:13:00-03:00,2026-03-04T05:15:00-03:00,88b2c554d9fffff,88b2c50b65fffff,car,health,4.814,2,62.0,L4
1,m00001,u0000,tm_00001,0,-70.623456,-33.518244,-70.600007,-33.511683,2026-03-06T22:45:00-03:00,2026-03-07T00:10:00-03:00,88b2c50921fffff,88b2c50907fffff,train,work,2.670,1,85.0,L1
2,m00002,u0000,tm_00001,1,-70.618727,-33.379648,-70.590278,-33.353505,2026-03-03T11:57:00-03:00,2026-03-03T12:58:00-03:00,88b2c51925fffff,88b2c51945fffff,bicycle,leisure,4.022,3,61.0,210
3,m00003,u0000,tm_00001,2,-70.616918,-33.387777,-70.585184,-33.381069,2026-03-02T10:03:00-03:00,2026-03-02T10:59:00-03:00,88b2c5561bfffff,88b2c51939fffff,taxi,home,0.872,3,56.0,I09c
4,m00004,u0000,tm_00001,3,-70.445835,-33.444718,-70.459784,-33.424350,2026-03-03T14:09:00-03:00,2026-03-03T14:33:00-03:00,88b2c50107fffff,88b2c50161fffff,bus,work,2.690,1,24.0,B07
5,m00005,u0002,tm_00002,0,-70.700642,-33.359821,-70.719136,-33.357793,2026-03-01T09:48:00-03:00,2026-03-01T10:36:00-03:00,88b2c5cdb5fffff,88b2c5cda7fffff,scooter,health,2.708,2,48.0,L4
6,m00006,u0002,tm_00002,1,-70.711224,-33.412599,-70.676905,-33.403926,2026-03-01T23:49:00-03:00,2026-03-02T00:21:00-03:00,88b2c55733fffff,88b2c5544dfffff,bus,transfer,4.720,1,32.0,210
7,m00007,u0002,tm_00002,2,-70.741377,-33.518743,-70.749029,-33.499805,2026-03-01T21:07:00-03:00,2026-03-01T21:46:00-03:00,88b2c5476bfffff,88b2c54291fffff,motorcycle,work,3.073,3,39.0,401
8,m00008,u0003,tm_00003,0,-70.598402,-33.420500,-70.649430,-33.464215,2026-03-06T15:37:00-03:00,2026-03-06T17:00:00-03:00,88b2c5569dfffff,88b2c554e3fffff,metro,education,2.631,3,83.0,B07
9,m00009,u0003,tm_00003,1,-70.547103,-33.526711,-70.592434,-33.536301,2026-03-06T07:21:00-03:00,2026-03-06T08:38:00-03:00,88b2c509cbfffff,88b2c50933fffff,ride_hailing,other,1.701,3,77.0,I09c
10,m00010,u0002,tm_00004,0,-70.671395,-33.379724,-70.708173,-33.393835,2026-03-06T03:03:00-03:00,2026-03-06T04:17:00-03:00,88b2c55629fffff,88b2c55703fffff,ride_hailing,other,1.992,4,74.0,B07
11,m00011,u0002,tm_00004,1,-70.744016,-33.453994,-70.724129,-33.473160,2026-03-04T11:35:00-03:00,2026-03-04T12:21:00-03:00,88b2c55539fffff,88b2c555e1fffff,bicycle,health,2.843,4,46.0,B07
12,m00012,u0003,tm_00005,0,-70.742448,-33.464789,-70.736751,-33.473043,2026-03-06T06:27:00-03:00,2026-03-06T08:22:00-03:00,88b2c55533fffff,88b2c555e5fffff,taxi,errand,2.475,2,115.0,L1
13,m00013,u0003,tm_00005,1,-70.594941,-33.504474,-70.567321,-33.459626,2026-03-02T09:05:00-03:00,2026-03-02T09:20:00-03:00,88b2c50901fffff,88b2c50b01fffff,train,shopping,0.597,1,15.0,210
14,m00014,u0003,tm_00005,2,-70.585675,-33.352197,-70.602765,-33.378172,2026-03-07T13:18:00-03:00,2026-03-07T14:02:00-03:00,88b2c51947fffff,88b2c51921fffff,walk,health,4.218,3,44.0,401
15,m00015,u0003,tm_00005,3,-70.605685,-33.462362,-70.599343,-33.433314,2026-03-04T18:10:00-03:00,2026-03-04T18:28:00-03:00,88b2c554d3fffff,88b2c55695fffff,metro,health,4.533,4,18.0,401
16,m00016,u0002,tm_00006,0,-70.726551,-33.484266,-70.701527,-33.534752,2026-03-07T19:35:00-03:00,2026-03-07T20:18:00-03:00,88b2c555adfffff,88b2c5471bfffff,taxi,education,1.131,4,43.0,B07
17,m00017,u0003,tm_00007,0,-70.636784,-33.478171,-70.649158,-33.488217,2026-03-02T07:35:00-03:00,2026-03-02T09:30:00-03:00,88b2c554b9fffff,88b2c554b5fffff,bus,home,2.993,1,115.0,L4

### 7) Dominios extendidos

In [14]:
df = make_extended_domains(
    filas=12,
    seed=42,
    include_noise=True,
)

display(df.head())

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,time_period,user_gender,trip_weight
0,m00000,u0000,t00000,0,-70.572155,-33.439773,-70.598775,-33.375523,2026-03-05T03:20:00-03:00,2026-03-05T05:03:00-03:00,88b2c50b41fffff,88b2c5192bfffff,Bus institucional,De compras,Noche,Hombre,2.508
1,m00001,u0004,t00001,0,-70.664993,-33.475299,-70.655706,-33.487492,2026-03-04T11:05:00-03:00,2026-03-04T12:15:00-03:00,88b2c554adfffff,88b2c554a3fffff,walk,work,Fuera de Punta 1,Hombre,2.215
2,m00002,u0003,t00002,0,-70.678486,-33.451344,-70.673819,-33.466711,2026-03-04T18:56:00-03:00,2026-03-04T19:10:00-03:00,88b2c55431fffff,88b2c555dbfffff,metro,De compras,evening,Hombre,1.857
3,m00003,u0002,t00003,0,-70.728093,-33.518244,-70.719345,-33.542657,2026-03-05T05:32:00-03:00,2026-03-05T07:04:00-03:00,88b2c54747fffff,88b2c54715fffff,other,leisure,evening,other,3.336
4,m00004,u0002,t00004,0,-70.537746,-33.379648,-70.502889,-33.361169,2026-03-01T12:15:00-03:00,2026-03-01T13:26:00-03:00,88b2c519c9fffff,88b2c5181dfffff,ZP,Recreación,evening,Hombre,2.128

Con override: util para agregar algo de ruido y más de un campo extendido.

In [34]:
df = make_extended_domains(
    filas=15,
    seed=42,
    extra_value_domains={
        "purpose": ["canon", "finos"],
        "mode": ["canon", "submodes"],
        "time_period": ["canon", "eod_finos"],
    },
    noise_ratio={
        "purpose": 0.3,
        "mode": 0.2,
    },
)

df.head(15)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,time_period,user_gender,trip_weight
0,m00000,u0000,t00000,0,-70.675453,-33.451344,-70.688240,-33.476079,2026-03-06T18:03:00-03:00,2026-03-06T18:57:00-03:00,88b2c55431fffff,88b2c555d7fffff,walk,Por trabajo,Noche,female,0.880
1,m00001,u0006,t00001,0,-70.702833,-33.518244,-70.721648,-33.498726,2026-03-08T03:06:00-03:00,2026-03-08T04:27:00-03:00,88b2c54751fffff,88b2c555a3fffff,scooter,Al trabajo,evening,male,2.371
2,m00002,u0005,t00002,0,-70.695213,-33.379648,-70.720768,-33.357351,2026-03-02T18:03:00-03:00,2026-03-02T18:22:00-03:00,88b2c55751fffff,88b2c5cda7fffff,NO_MATCH,shopping,Fuera de Punta 2,unknown,0.687
3,m00003,u0003,t00003,0,-70.606769,-33.387777,-70.617775,-33.371482,2026-03-03T04:27:00-03:00,2026-03-03T05:36:00-03:00,88b2c51927fffff,88b2c55653fffff,Taxi o radiotaxi,other,Punta Mañana 1,female,2.723
4,m00004,u0003,t00004,0,-70.623456,-33.444718,-70.563658,-33.464683,2026-03-04T02:37:00-03:00,2026-03-04T03:40:00-03:00,88b2c554cbfffff,88b2c50b03fffff,Taxi colectivo,health,Fuera de Punta 1,unknown,1.984
5,m00005,u0006,t00005,0,-70.618727,-33.359821,-70.653360,-33.352856,2026-03-08T04:46:00-03:00,2026-03-08T06:21:00-03:00,88b2c51965fffff,88b2c5564dfffff,Bus urbano pago conductor,???,Punta Mañana 1,male,1.150
6,m00006,u0000,t00006,0,-70.616918,-33.412599,-70.578187,-33.409099,2026-03-07T05:22:00-03:00,2026-03-07T07:21:00-03:00,88b2c5568dfffff,88b2c556dbfffff,Auto Chofer,999999,midday,other,0.965
7,m00007,u0005,t00007,0,-70.445835,-33.518743,-70.513150,-33.512183,2026-03-01T11:49:00-03:00,2026-03-01T13:10:00-03:00,88b2c50f67fffff,88b2c50817fffff,Bus urbano pago conductor,volver a casa,Punta Tarde,other,3.144
8,m00008,u0001,t00008,0,-70.700642,-33.420500,-70.714037,-33.394357,2026-03-02T21:18:00-03:00,2026-03-02T22:10:00-03:00,88b2c55461fffff,88b2c55703fffff,BAD_MODE,volver a casa,Noche,male,1.268
9,m00009,u0000,t00009,0,-70.711224,-33.526711,-70.704714,-33.520003,2026-03-07T00:02:00-03:00,2026-03-07T00:53:00-03:00,88b2c54757fffff,88b2c54751fffff,Servicio informal,transfer,midday,male,4.663
10,m00010,u0004,t00010,0,-70.741377,-33.379724,-70.717928,-33.359357,2026-03-01T15:47:00-03:00,2026-03-01T16:40:00-03:00,88b2c55761fffff,88b2c5cda7fffff,Auto Acompañante,Otra actividad,Punta Tarde,other,3.115
11,m00011,u0007,t00011,0,-70.598402,-33.453994,-70.569953,-33.451967,2026-03-07T05:45:00-03:00,2026-03-07T07:23:00-03:00,88b2c50b67fffff,88b2c50b09fffff,METROTREN,???,midday,female,2.061
12,m00012,u0005,t00012,0,-70.547103,-33.464789,-70.515369,-33.456115,2026-03-03T05:16:00-03:00,2026-03-03T05:57:00-03:00,88b2c50b11fffff,88b2c50a2bfffff,NO_MATCH,transfer,Fuera de Punta 1,other,3.159
13,m00013,u0006,t00013,0,-70.671395,-33.504474,-70.685344,-33.485536,2026-03-07T16:09:00-03:00,2026-03-07T16:33:00-03:00,88b2c5466bfffff,88b2c5559dfffff,Auto Acompañante,???,Punta Tarde,female,0.603
14,m00014,u0005,t00014,0,-70.744016,-33.352197,-70.762510,-33.395911,2026-03-03T07:19:00-03:00,2026-03-03T08:02:00-03:00,88b2c5528bfffff,88b2c550d7fffff,Bus urbano pago conductor,transfer,evening,other,4.814

### 8) Missing required

In [15]:
df = make_missing_required(filas=6, seed=42)

display(df.head())
df.columns.tolist()

,movement_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,t00000,0,-70.745304,-33.374755,-70.772542,-33.400534,2026-03-04T17:37:00Z,2026-03-04T19:28:00Z,88b2c5576dfffff,88b2c5508bfffff
1,m00001,t00001,0,-70.572060,-33.606083,-70.523159,-33.595020,2026-03-01T13:21:00Z,2026-03-01T14:51:00Z,88b2c57315fffff,88b2c57207fffff
2,m00002,t00002,0,-70.582221,-33.554174,-70.588402,-33.582941,2026-03-05T01:49:00Z,2026-03-05T02:36:00Z,88b2c509a1fffff,88b2c57347fffff
3,m00003,t00003,0,-70.653397,-33.439773,-70.670530,-33.413419,2026-03-02T07:55:00Z,2026-03-02T09:51:00Z,88b2c55411fffff,88b2c55443fffff
4,m00004,t00004,0,-70.547276,-33.475299,-70.561361,-33.476797,2026-03-06T10:53:00Z,2026-03-06T11:45:00Z,88b2c50b13fffff,88b2c50b3bfffff

['movement_id',
 'trip_id',
 'movement_seq',
 'origin_longitude',
 'origin_latitude',
 'destination_longitude',
 'destination_latitude',
 'origin_time_utc',
 'destination_time_utc',
 'origin_h3_index',
 'destination_h3_index']

Indicando explícitamente qué required faltan:

In [16]:
df = make_missing_required(
    filas=6,
    seed=42,
    missing_fields=["user_id", "origin_latitude"],
)
display(df.head())

,movement_id,trip_id,movement_seq,origin_longitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index
0,m00000,t00000,0,-70.745304,-70.772542,-33.400534,2026-03-04T17:37:00Z,2026-03-04T19:28:00Z,88b2c5576dfffff,88b2c5508bfffff
1,m00001,t00001,0,-70.572060,-70.523159,-33.595020,2026-03-01T13:21:00Z,2026-03-01T14:51:00Z,88b2c57315fffff,88b2c57207fffff
2,m00002,t00002,0,-70.582221,-70.588402,-33.582941,2026-03-05T01:49:00Z,2026-03-05T02:36:00Z,88b2c509a1fffff,88b2c57347fffff
3,m00003,t00003,0,-70.653397,-70.670530,-33.413419,2026-03-02T07:55:00Z,2026-03-02T09:51:00Z,88b2c55411fffff,88b2c55443fffff
4,m00004,t00004,0,-70.547276,-70.561361,-33.476797,2026-03-06T10:53:00Z,2026-03-06T11:45:00Z,88b2c50b13fffff,88b2c50b3bfffff

Con override: util para quitar requeridos de manera aleatoria

In [35]:
df = make_missing_required(
    filas=8,
    seed=42,
    n_random_missing_required=2,
)
display(df.head())

,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,origin_h3_index,destination_h3_index
0,t00000,0,-70.613249,-33.439773,-70.527583,-33.403097,2026-03-08T01:54:00Z,88b2c556b1fffff,88b2c519d7fffff
1,t00001,0,-70.745929,-33.475299,-70.762186,-33.479935,2026-03-03T13:28:00Z,88b2c542d9fffff,88b2c542c3fffff
2,t00002,0,-70.623125,-33.451344,-70.643615,-33.464194,2026-03-02T20:07:00Z,88b2c554ddfffff,88b2c5548dfffff
3,t00003,0,-70.755888,-33.518244,-70.788439,-33.528808,2026-03-05T04:50:00Z,88b2c5476dfffff,88b2c540c3fffff
4,t00004,0,-70.572155,-33.379648,-70.547516,-33.363679,2026-03-05T22:31:00Z,88b2c51915fffff,88b2c5182dfffff

### 9) Duplicate movement_id

In [17]:
df = make_duplicate_movement_id(filas=8, seed=42)

display(df.head())
df["movement_id"].value_counts().head()

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose
0,m00000,u0000,t00000,0,-70.653397,-33.606083,-70.636888,-33.611629,2026-03-04T11:46:00Z,2026-03-04T13:39:00Z,88b2c54481fffff,88b2c5449dfffff,scooter,health
1,m00001,u0003,t00001,0,-70.547276,-33.554174,-70.530043,-33.574602,2026-03-02T03:49:00Z,2026-03-02T04:44:00Z,88b2c50995fffff,88b2c5726bfffff,bus,errand
2,m00002,u0002,t00002,0,-70.613249,-33.439773,-70.527583,-33.403097,2026-03-06T01:19:00Z,2026-03-06T01:42:00Z,88b2c556b1fffff,88b2c519d7fffff,bus,errand
3,m00003,u0001,t00003,0,-70.745929,-33.475299,-70.762186,-33.479935,2026-03-04T13:55:00Z,2026-03-04T15:35:00Z,88b2c542d9fffff,88b2c542c3fffff,bicycle,health
4,m00004,u0001,t00004,0,-70.623125,-33.451344,-70.643615,-33.464194,2026-03-03T13:28:00Z,2026-03-03T14:45:00Z,88b2c554ddfffff,88b2c5548dfffff,train,home

movement_id
m00006    2
m00000    1
m00001    1
m00002    1
m00003    1
Name: count, dtype: Int64

Duplicando filas completas:

In [22]:
df = make_duplicate_movement_id(
    filas=8,
    seed=42,
    full_rows=True,
)
display(df[3:8].head())
df.duplicated()

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose
3,m00003,u0001,t00003,0,-70.745929,-33.475299,-70.762186,-33.479935,2026-03-04T13:55:00Z,2026-03-04T15:35:00Z,88b2c542d9fffff,88b2c542c3fffff,bicycle,health
4,m00004,u0001,t00004,0,-70.623125,-33.451344,-70.643615,-33.464194,2026-03-03T13:28:00Z,2026-03-03T14:45:00Z,88b2c554ddfffff,88b2c5548dfffff,train,home
5,m00006,u0000,t00006,0,-70.572155,-33.379648,-70.547516,-33.363679,2026-03-05T04:50:00Z,2026-03-05T05:06:00Z,88b2c51915fffff,88b2c5182dfffff,metro,education
6,m00006,u0000,t00006,0,-70.572155,-33.379648,-70.547516,-33.363679,2026-03-05T04:50:00Z,2026-03-05T05:06:00Z,88b2c51915fffff,88b2c5182dfffff,metro,education
7,m00007,u0002,t00007,0,-70.664993,-33.387777,-70.619834,-33.376813,2026-03-05T22:31:00Z,2026-03-05T23:11:00Z,88b2c5562bfffff,88b2c55653fffff,walk,work

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
dtype: bool

Con override: útil para volverlo un poco más rico para que no sea solo una tabla mínima con IDs repetidos

In [36]:
df = make_duplicate_movement_id(
    filas=10,
    seed=42,
    base_fields=["mode", "purpose", "trip_weight"],
    extra_columns=["household_id", "travel_time_min"],
)

df.head(10)

,movement_id,user_id,trip_id,movement_seq,origin_longitude,origin_latitude,destination_longitude,destination_latitude,origin_time_utc,destination_time_utc,origin_h3_index,destination_h3_index,mode,purpose,trip_weight,household_id,travel_time_min
0,m00000,u0000,t00000,0,-70.745929,-33.554174,-70.700770,-33.564738,2026-03-07T12:52:00Z,2026-03-07T14:28:00Z,88b2c54549fffff,88b2c54463fffff,train,other,3.479,H00003,96.0
1,m00001,u0003,t00001,0,-70.623125,-33.439773,-70.627683,-33.423803,2026-03-03T06:26:00Z,2026-03-03T08:01:00Z,88b2c556b5fffff,88b2c556a9fffff,ride_hailing,transfer,3.007,H00002,95.0
2,m00009,u0003,t00002,0,-70.755888,-33.475299,-70.789495,-33.464336,2026-03-02T22:14:00Z,2026-03-02T23:48:00Z,88b2c542ddfffff,88b2c54211fffff,walk,home,4.028,H00003,94.0
3,m00003,u0002,t00003,0,-70.572155,-33.451344,-70.605134,-33.438962,2026-03-06T00:39:00Z,2026-03-06T02:00:00Z,88b2c50b0dfffff,88b2c556bbfffff,metro,education,3.489,H00000,81.0
4,m00002,u0002,t00004,0,-70.664993,-33.518244,-70.638969,-33.505319,2026-03-05T16:58:00Z,2026-03-05T17:57:00Z,88b2c54601fffff,88b2c54651fffff,ride_hailing,transfer,2.329,H00004,59.0
5,m00005,u0004,t00005,0,-70.678486,-33.379648,-70.648756,-33.315399,2026-03-02T05:28:00Z,2026-03-02T06:54:00Z,88b2c55667fffff,88b2c5ccedfffff,ride_hailing,home,4.163,H00002,86.0
6,m00006,u0000,t00006,0,-70.728093,-33.387777,-70.706367,-33.399969,2026-03-07T01:53:00Z,2026-03-07T02:29:00Z,88b2c55763fffff,88b2c55715fffff,ride_hailing,transfer,1.251,H00004,36.0
7,m00007,u0003,t00007,0,-70.537746,-33.444718,-70.564366,-33.460085,2026-03-02T15:35:00Z,2026-03-02T17:09:00Z,88b2c50b5bfffff,88b2c50b03fffff,ride_hailing,education,0.602,H00000,94.0
8,m00008,u0001,t00008,0,-70.675453,-33.359821,-70.666166,-33.384234,2026-03-06T21:13:00Z,2026-03-06T22:21:00Z,88b2c5cd97fffff,88b2c55629fffff,walk,other,0.905,H00002,68.0
9,m00009,u0000,t00009,0,-70.702833,-33.412599,-70.698165,-33.394120,2026-03-01T07:14:00Z,2026-03-01T08:11:00Z,88b2c5546dfffff,88b2c5571dfffff,ride_hailing,education,3.751,H00003,57.0